// GENERATED by scripts/build-pa-staleness-ledger.mjs from
// pa-staleness-ledger.json (repo root). Do not edit by hand: edit the
// JSON and re-run the generator (CI fails on drift via
// scripts/check-pa-staleness.mjs).
//
// spec-v52 §8.3: the staleness ledger bundled for the browser so the
// in-tab PA report audit trail can show per-source staleness with no
// runtime fetch (spec-v50 §3.1 no-network).

export const PA_STALENESS_LEDGER = {
  "_comment": "spec-v52 §8.3 dataset-staleness ledger. Most sources back a rule family in lib/pa/rules.js (their `rules` array names R-PA-* anchor ids). spec-v63 OA4 extends the ledger to the non-PA operations rule families (ruleFamily \"ops-v63\"): the dated regulatory constants behind the v63 ops calculators -- federal holidays, Medicare appeal deadlines, the amount-in-controversy thresholds, the timely-filing basis, the CMS-0057-F PA windows, the 2021 E/M edition, and the 60-day overpayment rule. These ops sources carry an empty `rules` array (they anchor no pa-lint rule) but are staleness-tracked like every other source, so check-pa-staleness guards their currency too. The maintainer re-verifies each source on the cadence in docs/pa-maintenance.md and bumps lastVerified to the verification date (ISO YYYY-MM-DD). scripts/check-pa-staleness.mjs enforces the policy window in CI. To suppress a known-stale source without re-verifying, add an entry to acknowledgments with an ackDate and a reason. JSON, not YAML, to keep Sophie's zero-dependency posture (spec-v10 §6).",
  "rulesetVersion": "1.0.0",
  "policy": {
    "warnAfterDays": 90,
    "failAfterDays": 365
  },
  "sources": [
    {
      "id": "ama-cpt",
      "label": "AMA CPT code set (short descriptors)",
      "ruleFamily": "core",
      "rules": [
        "R-PA-007",
        "R-PA-008",
        "R-PA-014",
        "R-PA-051"
      ],
      "url": "https://www.ama-assn.org/practice-management/cpt",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "cms-hcpcs",
      "label": "CMS HCPCS Level II code set",
      "ruleFamily": "core",
      "rules": [
        "R-PA-007",
        "R-PA-009"
      ],
      "url": "https://www.cms.gov/medicare/coding-billing/healthcare-common-procedure-system",
      "lastVerified": "2026-09-14"
    },
    {
      "id": "cms-icd10cm",
      "label": "CMS / CDC ICD-10-CM annual code files (public domain)",
      "ruleFamily": "core",
      "rules": [
        "R-PA-010",
        "R-PA-011"
      ],
      "url": "https://www.cms.gov/medicare/coding-billing/icd-10-codes",
      "lastVerified": "2026-09-14"
    },
    {
      "id": "cms-pos",
      "label": "CMS Place of Service (POS) code set (complete assigned set, incl. telehealth POS 02 / 10 and POS 27)",
      "ruleFamily": "core",
      "rules": [
        "R-PA-013"
      ],
      "url": "https://www.cms.gov/medicare/coding-billing/place-of-service-codes/code-sets",
      "lastVerified": "2026-09-14"
    },
    {
      "id": "cms-ncci",
      "label": "CMS National Correct Coding Initiative (NCCI) PTP edits",
      "ruleFamily": "core",
      "rules": [
        "R-PA-012",
        "R-PA-054"
      ],
      "url": "https://www.cms.gov/medicare/coding-billing/national-correct-coding-initiative-ncci-edits",
      "lastVerified": "2026-09-14"
    },
    {
      "id": "nppes-npi",
      "label": "NPPES NPI standard (Luhn-mod-10 with 80840 issuer prefix)",
      "ruleFamily": "core",
      "rules": [
        "R-PA-016",
        "R-PA-019"
      ],
      "url": "https://www.cms.gov/regulations-and-guidance/administrative-simplification/nationalprovidentstand",
      "lastVerified": "2026-09-14"
    },
    {
      "id": "cms-ncd-lcd",
      "label": "CMS Medicare Coverage Database (NCDs, LCDs, LCAs)",
      "ruleFamily": "cms-ffs",
      "rules": [
        "R-PA-CMS-001",
        "R-PA-CMS-005",
        "R-PA-CMS-006"
      ],
      "url": "https://www.cms.gov/medicare-coverage-database/search.aspx",
      "lastVerified": "2026-09-14"
    },
    {
      "id": "cms-iom-100-08",
      "label": "CMS Internet-Only Manual Pub 100-08 (Program Integrity)",
      "ruleFamily": "cms-ffs",
      "rules": [
        "R-PA-CMS-002",
        "R-PA-CMS-003",
        "R-PA-CMS-004"
      ],
      "url": "https://www.cms.gov/medicare/regulations-guidance/manuals/internet-only-manuals-ioms",
      "lastVerified": "2026-09-14"
    },
    {
      "id": "cms-ma-422",
      "label": "CMS Medicare Advantage rules (42 CFR Part 422, organization determinations)",
      "ruleFamily": "cms-ma",
      "rules": [
        "R-PA-MA-001",
        "R-PA-MA-002"
      ],
      "url": "https://www.ecfr.gov/current/title-42/chapter-IV/subchapter-B/part-422",
      "lastVerified": "2026-09-14"
    },
    {
      "id": "medicaid-core",
      "label": "Medicaid program requirements (state-agnostic core, EPSDT)",
      "ruleFamily": "medicaid-core",
      "rules": [
        "R-PA-MCD-002",
        "R-PA-MCD-006"
      ],
      "url": "https://www.medicaid.gov/federal-policy-guidance/downloads/sho24005.pdf",
      "lastVerified": "2026-09-14"
    },
    {
      "id": "acr-appropriateness",
      "label": "ACR Appropriateness Criteria (advanced imaging)",
      "ruleFamily": "specialty-rad",
      "rules": [
        "R-PA-RAD-001",
        "R-PA-RAD-002"
      ],
      "url": "https://www.acr.org/Clinical-Resources/Clinical-Tools-and-Reference/Appropriateness-Criteria",
      "lastVerified": "2026-09-14"
    },
    {
      "id": "fda-labeling",
      "label": "FDA drug labeling / NDC directory (infusion, specialty drug)",
      "ruleFamily": "specialty-inf",
      "rules": [
        "R-PA-INF-001",
        "R-PA-INF-002"
      ],
      "url": "https://www.fda.gov/drugs/electronic-drug-registration-and-listing-system-edrls/national-drug-code-format",
      "lastVerified": "2026-09-14"
    },
    {
      "id": "cms-tja-lcd",
      "label": "CMS total joint arthroplasty coverage criteria",
      "ruleFamily": "specialty-surg",
      "rules": [
        "R-PA-SURG-001",
        "R-PA-SURG-002"
      ],
      "url": "https://www.cms.gov/medicare-coverage-database/view/lcd.aspx?lcdId=40232&ver=5",
      "lastVerified": "2026-09-14"
    },
    {
      "id": "asa-preanesthesia",
      "label": "ASA Basic Standards for Preanesthesia Care",
      "ruleFamily": "specialty-surg",
      "rules": [
        "R-PA-SURG-003"
      ],
      "url": "https://www.asahq.org/~/media/Sites/ASAHQ/Files/Public/Resources/standards-guidelines/basic-standards-for-preanesthesia-care.pdf",
      "lastVerified": "2026-09-14"
    },
    {
      "id": "asa-physical-status",
      "label": "ASA Physical Status Classification System",
      "ruleFamily": "specialty-surg",
      "rules": [
        "R-PA-SURG-004"
      ],
      "url": "https://www.asahq.org/standards-and-practice-parameters/statement-on-asa-physical-status-classification-system",
      "lastVerified": "2026-09-14"
    },
    {
      "id": "cms-hospital-surgery",
      "label": "CMS hospital surgical-services requirements",
      "ruleFamily": "specialty-surg",
      "rules": [
        "R-PA-SURG-005"
      ],
      "url": "https://www.ecfr.gov/current/title-42/chapter-IV/subchapter-G/part-482/subpart-D/section-482.51",
      "lastVerified": "2026-09-14"
    },
    {
      "id": "apa-dsm",
      "label": "APA DSM-5-TR classification and ICD-10-CM updates",
      "ruleFamily": "specialty-bh",
      "rules": [
        "R-PA-BH-001"
      ],
      "url": "https://www.psychiatry.org/psychiatrists/practice/dsm",
      "lastVerified": "2026-09-14"
    },
    {
      "id": "asam-criteria",
      "label": "ASAM Criteria addiction-treatment level-of-care framework",
      "ruleFamily": "specialty-bh",
      "rules": [
        "R-PA-BH-003"
      ],
      "url": "https://www.asam.org/asam-criteria/asam-criteria-4th-edition",
      "lastVerified": "2026-09-14"
    },
    {
      "id": "joint-commission-suicide-screening",
      "label": "Joint Commission behavioral-health suicide screening scope",
      "ruleFamily": "specialty-bh",
      "rules": [
        "R-PA-BH-004"
      ],
      "url": "https://www.jointcommission.org/en/knowledge-library/support-center/standards-interpretation/standards-faqs/000001215",
      "lastVerified": "2026-09-14"
    },
    {
      "id": "samhsa-mat-act",
      "label": "SAMHSA DATA/X-waiver elimination and OTP requirements",
      "ruleFamily": "specialty-bh",
      "rules": [
        "R-PA-BH-005"
      ],
      "url": "https://www.samhsa.gov/substance-use/treatment/resources/mat-act",
      "lastVerified": "2026-09-14"
    },
    {
      "id": "nci-hereditary-cancer-testing",
      "label": "NCI inherited-cancer genetic testing and counseling guidance",
      "ruleFamily": "specialty-gen",
      "rules": [
        "R-PA-GEN-001",
        "R-PA-GEN-002",
        "R-PA-GEN-003"
      ],
      "url": "https://www.cancer.gov/about-cancer/causes-prevention/genetics/genetic-testing-fact-sheet",
      "lastVerified": "2026-09-14"
    },
    {
      "id": "nhgri-gina",
      "label": "NHGRI Genetic Information Nondiscrimination Act scope",
      "ruleFamily": "specialty-gen",
      "rules": [
        "R-PA-GEN-005"
      ],
      "url": "https://www.genome.gov/genetics-glossary/Genetic-Information-Nondiscrimination-Act-GINA",
      "lastVerified": "2026-09-14"
    },
    {
      "id": "aetna-precert",
      "label": "Aetna participating-provider precertification requirements & Clinical Policy Bulletins",
      "ruleFamily": "commercial-aetna",
      "rules": [
        "R-PA-AETNA-001",
        "R-PA-AETNA-002"
      ],
      "url": "https://www.aetna.com/health-care-professionals/precertification.html",
      "lastVerified": "2026-09-14",
      "alsoCited": [
        "https://www.aetna.com/health-care-professionals/utilization-management/concurrent-review.html",
        "https://www.aetna.com/health-care-professionals/medicare/part-b-drug-um.html",
        "https://www.aetna.com/health-care-professionals/outpatient-surgical-procedures.html",
        "https://www.aetna.com/content/dam/aetna/pdfs/aetnacom/healthcare-professionals/2026_Precert_List.pdf",
        "https://www.aetna.com/health-care-professionals/health-care-professional-forms.html",
        "https://www.aetna.com/content/dam/aetna/pdfs/aetnacom/health-care-professionals/documents-forms/spinal-surgery-precert-form.pdf",
        "https://www.aetna.com/cpb/medical/data/1_99/0084.html",
        "https://www.aetna.com/content/dam/aetna/pdfs/aetnacom/pharmacy-insurance/healthcare-professional/documents/precert-information-request-form.pdf",
        "https://www.aetna.com/cpb/medical/data/100_199/0157.html",
        "https://www.aetna.com/cpb/medical/data/100_199/0140.html",
        "https://www.aetna.com/health-care-professionals/disputes-appeals/disputes-appeals-overview.html",
        "https://www.aetna.com/individuals-families/using-your-aetna-benefits/network-out-of-network-care.html"
      ]
    },
    {
      "id": "uhc-precert",
      "label": "UnitedHealthcare prior-authorization / advance-notification requirements, Medical & Drug Policies, and Coverage Determination Guidelines",
      "ruleFamily": "commercial-uhc",
      "rules": [
        "R-PA-UHC-001",
        "R-PA-UHC-002"
      ],
      "url": "https://www.uhcprovider.com/en/prior-auth-advance-notification.html",
      "lastVerified": "2026-09-13",
      "alsoCited": [
        "https://www.uhcprovider.com/en/policies-protocols.html",
        "https://www.uhcprovider.com/en/prior-auth-advance-notification/adv-notification-plan-reqs.html",
        "https://www.uhcprovider.com/content/dam/provider/docs/public/admin-guides/2026-UHC-Administrative-Guide.pdf",
        "https://www.uhcprovider.com/content/dam/provider/docs/public/prior-auth/radiology/COMM-Exchange-Radiology-Prior-Auth-FAQ.pdf",
        "https://www.uhcprovider.com/content/dam/provider/docs/public/policies/comm-medical-drug/outpatient-surg-procedures-site-service.pdf",
        "https://www.uhcprovider.com/content/dam/provider/docs/public/policies/comm-reimbursement/COMM-National-Drug-Code-Requirement-Policy.pdf",
        "https://www.uhcprovider.com/content/dam/provider/docs/public/prior-auth/genetic-paan-faq.pdf",
        "https://public.providerexpress.com/content/ope-provexpr/us/en/clinical-resources/guidelines-policies/Adoption-of-LOCUS-CASII-ECSII.html",
        "https://www.uhcprovider.com/content/dam/provider/docs/public/policies/comm-medical-drug/off-label-unproven-specialty-drug-treatment.pdf",
        "https://www.uhcprovider.com/en/claims-payments-billing/appeals.html",
        "https://www.uhcprovider.com/content/dam/provider/docs/public/prior-auth/UHC-Commercial-GAP-Application-form.pdf"
      ]
    },
    {
      "id": "anthem-precert",
      "label": "Anthem Blue Cross Blue Shield (Elevance Health) prior-authorization requirements, Clinical UM Guidelines, and Medical Policies",
      "ruleFamily": "commercial-anthem",
      "rules": [
        "R-PA-ANTHEM-001",
        "R-PA-ANTHEM-002"
      ],
      "url": "https://www.anthem.com/provider/individual-commercial/prior-authorization",
      "lastVerified": "2026-09-13",
      "alsoCited": [
        "https://www.anthem.com/provider/policies/clinical-guidelines/",
        "https://www.anthem.com/provider/individual-commercial/availity",
        "https://www.anthem.com/medpolicies/abc/active/gl_pw_a051150.html",
        "https://www.anthem.com/pharmacy-information/for-providers/clinical-criteria",
        "https://www.anthem.com/medpolicies/abc/active/mp_pw_a044153.html",
        "https://www.anthem.com/provider/individual-commercial/reimbursement/definitions"
      ]
    },
    {
      "id": "cigna-precert",
      "label": "Cigna prior-authorization / precertification requirements, Medical Coverage Policies, and eviCore / Evernorth program requirements",
      "ruleFamily": "commercial-cigna",
      "rules": [
        "R-PA-CIGNA-001",
        "R-PA-CIGNA-002"
      ],
      "url": "https://www.cigna.com/health-care-providers/coverage-and-claims/precertification",
      "lastVerified": "2026-09-13",
      "alsoCited": [
        "https://www.cigna.com/health-care-providers/coverage-and-claims/policies",
        "https://www.cigna.com/static/www-cigna-com/docs/master-precertification-list-for-providers.pdf",
        "https://static.cigna.com/assets/chcp/pdf/coveragePolicies/medical/mm_0550_coveragepositioncriteria_soc_htr.pdf",
        "https://static.cigna.com/assets/chcp/resourceLibrary/pharmacyResources/pharmSteptherapy.html",
        "https://www.cigna.com/health-care-providers/resources/genetic-testing-and-counseling-program",
        "https://static.cigna.com/assets/chcp/resourceLibrary/coveragePolicies/index.html",
        "https://static.cigna.com/assets/chcp/resourceLibrary/behavioralResources/medicalMgmt/adminGuide/careAdvocacyPgm.html",
        "https://www.cigna.com/legal/compliance/directory-disclaimer"
      ]
    },
    {
      "id": "humana-precert",
      "label": "Humana prior-authorization / preauthorization requirements, Medical Coverage Policies, and utilization-management / CenterWell program requirements",
      "ruleFamily": "commercial-humana",
      "rules": [
        "R-PA-HUMANA-001",
        "R-PA-HUMANA-002"
      ],
      "url": "https://provider.humana.com/coverage-claims/prior-authorizations",
      "lastVerified": "2026-09-14",
      "alsoCited": [
        "https://provider.humana.com/coverage-claims",
        "https://provider.humana.com/coverage-claims/prior-authorizations/prior-authorization-lists",
        "https://provider.humana.com/coverage-claims/prior-authorizations/prior-authorizations-search-tool",
        "https://provider.humana.com/patient-care/transplant-resources/transplant-services-questions"
      ]
    },
    {
      "id": "hcsc-precert",
      "label": "Health Care Service Corporation (Blue Cross Blue Shield of IL/TX/MT/NM/OK) prior-authorization requirements, Medical Policies, and utilization-management / Prime Therapeutics program requirements",
      "ruleFamily": "commercial-hcsc",
      "rules": [
        "R-PA-HCSC-001",
        "R-PA-HCSC-002"
      ],
      "url": "https://www.bcbsil.com/provider/claims/claims-eligibility/utilization-management/prior-authorization",
      "lastVerified": "2026-09-14",
      "alsoCited": [
        "https://www.bcbsil.com/docs/provider/il/claims/um/2026-commercial-pa-summary.pdf",
        "https://www.bcbsil.com/provider/clinical/clinical-resources/behavioral-health-program",
        "https://ccpa.bcbsil.com/find-care/blue-distinction-specialty-care/blue-distinction/blue-distinction-transplant",
        "https://www.bcbsil.com/provider/standards/standard-requirements/medical-policy",
        "https://www.bcbsil.com/provider/claims/claims-eligibility/claim-review",
        "https://www.bcbsil.com/provider/standards/standard-requirements/caa/caa-continuity-care"
      ]
    },
    {
      "id": "highmark-precert",
      "label": "Highmark (Blue Cross Blue Shield of PA/WV/DE + western NY) prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-highmark",
      "rules": [
        "R-PA-HIGHMARK-001",
        "R-PA-HIGHMARK-002"
      ],
      "url": "https://providers.highmark.com/authorization/obtaining-authorizations.html",
      "lastVerified": "2026-09-15",
      "alsoCited": [
        "https://providers.highmark.com/policies-and-programs/medical-policies.html",
        "https://providers.highmark.com/content/dam/highmark/en/providerresourcecenter/pdfs/multi-region/documents/pdfs/latest-updates/special-bulletins/sb-auth-status-self-service-tools-103123.pdf",
        "https://providers.highmark.com/resources-and-education/highmark-provider-manual/chapter-5-care-and-quality-management/unit-2-authorizations",
        "https://providers.highmark.com/communications-hub/news-and-updates/radcard-authorization-moving-from-evicore-to-highmark-",
        "https://providers.highmark.com/communications-hub/news-and-updates/reminder-changes-occurring-in-2026",
        "https://providers.highmark.com/resources-and-education/forms/pharmacy-prior-authorization-forms",
        "https://providers.highmark.com/content/dam/highmark/en/providerresourcecenter/pdfs/multi-region/documents/pdfs/policies-and-programs/care-management/evicore-quick-ref-guide.pdf",
        "https://providers.highmark.com/communications-hub/news-and-updates/healthhelp-to-manage-molecular-lab-prior-authorization",
        "https://providers.highmark.com/communications-hub/news-and-updates/evolent-to-manage-oncology-prior-authorization-review.html",
        "https://providers.highmark.com/content/dam/highmark/en/providerresourcecenter/pdfs/all/documents/pdfs/authorization/obtaining-authorizations/bh-auth-tip-sheet.pdf",
        "https://providers.highmark.com/resources-and-education/highmark-provider-manual/chapter-5-care-and-quality-management/unit-4-behavioral-health",
        "https://providers.highmark.com/resources-and-education/highmark-provider-manual/chapter-5-care-and-quality-management/unit-1-care-management-overview",
        "https://providers.highmark.com/policies-and-programs/medical-policies/medical-policy-faqs",
        "https://providers.highmark.com/resources-and-education/highmark-provider-manual/chapter-5-care-and-quality-management/unit-5-denials-adverse-benefit-determinations-grievances-and-app",
        "https://providers.highmark.com/content/dam/highmark/en/providerresourcecenter/pdfs/all/documents/pdfs/authorization/obtaining-authorizations/oon-gap-exception-request-guide.pdf"
      ]
    },
    {
      "id": "floridablue-precert",
      "label": "Florida Blue / GuideWell (Blue Cross and Blue Shield of Florida) prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-florida-blue",
      "rules": [
        "R-PA-FLBLUE-001",
        "R-PA-FLBLUE-002"
      ],
      "url": "https://www.floridablue.com/providers/medical-pharmacy-info/prior-authorization",
      "lastVerified": "2026-09-15",
      "alsoCited": [
        "https://www.floridablue.com/providers/medical-pharmacy-info/medical-policies",
        "https://www.floridablue.com/providers/quick-reference-guide",
        "https://www.floridablue.com/providers/medical-pharmacy-info/medical-policy-pre-certification-pre-authorization",
        "https://files.guidewell.com/m/810cd58904247aa/original/providers-provider-manual-03.pdf",
        "https://files.guidewell.com/m/e5087e5b6b69199/original/providers-news-2025-administrative-news-site-of-care-review-05-2025.pdf",
        "https://www.floridablue.com/providers/programs/utilization-management",
        "https://www.floridablue.com/providers/medical-pharmacy-info/pharmacy-utilization-management",
        "https://www.floridablue.com/members/tools-resources/prior-authorization-medical-services"
      ]
    },
    {
      "id": "bcbsm-precert",
      "label": "Blue Cross Blue Shield of Michigan (+ Blue Care Network) prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-bcbsm",
      "rules": [
        "R-PA-BCBSM-001",
        "R-PA-BCBSM-002"
      ],
      "url": "https://authorizations.bcbsm.com/index.shtml",
      "lastVerified": "2026-09-15",
      "alsoCited": [
        "https://authorizations.bcbsm.com/",
        "https://authorizations.bcbsm.com/prov-ref-bcbsm-authorizations.shtml",
        "https://authorizations.bcbsm.com/prov-ref-getting-started.shtml",
        "https://authorizations.bcbsm.com/prov-ref-auth-landing.shtml",
        "https://www.bcbsm.com/content/dam/public/providers/documents/preauthorization-precertification-requirements.pdf",
        "https://authorizations.bcbsm.com/docs/inpatient-admissions-auth-faq.pdf",
        "https://authorizations.bcbsm.com/prov-ref-radiology.shtml",
        "https://authorizations.bcbsm.com/docs/bcn-14bcn-advantage.pdf",
        "https://authorizations.bcbsm.com/docs/msk-faq.pdf",
        "https://authorizations.bcbsm.com/prov-ref-drugs-medical-marf.shtml",
        "https://authorizations.bcbsm.com/prov-ref-drugs-medical-resources.shtml",
        "https://authorizations.bcbsm.com/prov-ref-drugs-pharm-electronic-reqs.shtml",
        "https://authorizations.bcbsm.com/prov-ref-laboratory.shtml",
        "https://authorizations.bcbsm.com/prov-ref-drugs-medical-benefit.shtml",
        "https://authorizations.bcbsm.com/prov-ref-dme-po.shtml",
        "https://authorizations.bcbsm.com/prov-ref-home-health.shtml",
        "https://authorizations.bcbsm.com/prov-ref-behavioral-health.shtml",
        "https://authorizations.bcbsm.com/prov-ref-behavioral-health-provider-resources.shtml",
        "https://authorizations.bcbsm.com/prov-ref-transplants.shtml",
        "https://authorizations.bcbsm.com/docs/e-referral-user-guide.pdf",
        "https://www.bcbsm.com/amslibs/content/dam/public/consumer/forms-documents/bcbsm-appeal-form.pdf",
        "https://authorizations.bcbsm.com/alerts/prov-ref-alerts-landing.shtml"
      ]
    },
    {
      "id": "blueshieldca-precert",
      "label": "Blue Shield of California prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-blue-shield-ca",
      "rules": [
        "R-PA-BSCA-001",
        "R-PA-BSCA-002"
      ],
      "url": "https://www.blueshieldca.com/en/provider/authorizations",
      "lastVerified": "2026-09-15",
      "alsoCited": [
        "https://www.blueshieldca.com/en/provider/authorizations/clinical-policies-ooap",
        "https://www.blueshieldca.com/en/provider/authorizations/policy-medical/list",
        "https://www.blueshieldca.com/en/provider/authorizations/authorization-list",
        "https://www.blueshieldca.com/en/provider/authorizations/how-to-submit-requests",
        "https://www.blueshieldca.com/en/provider/about-pc/contact-us/contacts-authorizations",
        "https://www.blueshieldca.com/en/provider/guidelines-resources/manuals/facilities",
        "https://www.blueshieldca.com/en/provider/authorizations/authorization-forms",
        "https://www.blueshieldca.com/en/provider/authorizations/policy-medications/policy-list",
        "https://www.blueshieldca.com/en/provider/guidelines-resources/guidelines-procedures/utilization-management",
        "https://www.blueshieldca.com/content/dam/bsca/en/provider/docs/1-26-A11504-HG-Manual.pdf",
        "https://www.blueshieldca.com/content/dam/bsca/en/provider/docs/medical-policies/Investigational-Experimental-Services.pdf",
        "https://www.blueshieldca.com/en/provider/claims/disputes/dispute-process",
        "https://www.blueshieldca.com/en/home/find-a-doctor/help/continuity-of-care",
        "https://www.blueshieldca.com/content/dam/bsca/en/shared/documents/2026/Continuity-of-Care-Application-EN.pdf"
      ]
    },
    {
      "id": "ibx-precert",
      "label": "Independence Blue Cross (southeastern Pennsylvania / Philadelphia) prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-ibx",
      "rules": [
        "R-PA-IBX-001",
        "R-PA-IBX-002"
      ],
      "url": "https://www.ibx.com/resources/for-providers/policies-and-guidelines/index.html",
      "lastVerified": "2026-09-15",
      "alsoCited": [
        "https://www.ibx.com/resources/for-providers/policies-and-guidelines/operations-management/medical-policy.html",
        "https://www.ibx.com/resources/for-providers/policies-and-guidelines/operations-management/preapproval-requirements.html",
        "https://www.ibx.com/resources/for-providers/contact-us/index.html",
        "https://provcomm.ibx.com/pnc-ibc/Manuals/Provider/IBX_Provider_06_Clinical-Services-UM.pdf",
        "https://provcomm.ibx.com/pnc-ibc/Manuals/Hospital/IBX_Hospital_06_Clinical-Services-UM.pdf",
        "https://www.ibx.com/documents/35221/56629/carelon-request-form.pdf",
        "https://www.ibx.com/pdfs/resources/for-providers/most-cost-effective.pdf",
        "https://www.ibx.com/resources/for-providers/policies-and-guidelines/pharmacy-information/prior-authorization.html",
        "https://www.ibx.com/pdfs/resources/for-providers/formularies/premium-st-drug-list.pdf",
        "https://www.ibx.com/documents/35221/851945/value-prior-authorization.pdf",
        "https://provcomm.ibx.com/pnc-ibc/Manuals/Provider/IBX_Provider_11_Specialty-Programs.pdf",
        "https://www.ibx.com/ResourceCenter/IBX-direct-ship-drug-request-form.pdf",
        "https://provcomm.ibx.com/pnc-ibc/news/Pages/Reminder-ABA-services-transitioned-to-IBX-on-April-1-2026.aspx",
        "https://www.ibx.com/resources/for-members/quality-management.html",
        "https://provcomm.ibx.com/pnc-ibc/Manuals/Provider/IBX_Provider_15_Appeals.pdf"
      ]
    },
    {
      "id": "carefirst-precert",
      "label": "CareFirst BlueCross BlueShield (Maryland / District of Columbia / Northern Virginia) prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-carefirst",
      "rules": [
        "R-PA-CAREFIRST-001",
        "R-PA-CAREFIRST-002"
      ],
      "url": "https://provider.carefirst.com/providers/medical/in-network-precertification-preauthorization.page",
      "lastVerified": "2026-09-15",
      "alsoCited": [
        "https://provider.carefirst.com/carefirst-resources/provider/pdf/professional-provider-manual-policies-pm0010.pdf",
        "https://provider.carefirst.com/carefirst-resources/provider/newsletters/bluelink-2024-feb.pdf",
        "https://www.evicore.com/sites/default/files/resources/2026-05/CareFirst_Radiology%20and%20Cardiology-%20FAQ%202026.pdf",
        "https://www.carefirst.com/medicare-options/attachments/dsnp/DSNP%20Provider%20Prior%20Aut%20Form.pdf",
        "https://provider.carefirst.com/providers/pharmacy/pharmacy-forms.page",
        "https://provider.carefirst.com/carefirst-resources/provider/pdf/provider-manual-chapter-4-guidelines-by-specialty-service.pdf",
        "https://provider.carefirst.com/carefirst-resources/provider/pdf/prior-auth-fax-form-md.pdf",
        "https://guidelines.carelonmedicalbenefitsmanagement.com/current-genetic-testing-guidelines/",
        "https://provider.carefirst.com/carefirst-resources/provider/pdf/home-care-authorization-cut6137.pdf",
        "https://provider.carefirst.com/carefirst-resources/pdf/nqtl-disclosure-form.pdf",
        "https://provider.carefirst.com/carefirst-resources/provider/pdf/utilization-management-request-authorization-form-prd1108.pdf",
        "https://provider.carefirst.com/carefirst-resources/provider/pdf/pcmh-program-description-guidelines-vol-ii.pdf",
        "https://provider.carefirst.com/carefirst-resources/provider/pdf/provider-manual-chapter-5-claims-billing-and-payments.pdf",
        "https://provider.carefirst.com/carefirst-resources/provider/pdf/programs-and-products.pdf"
      ]
    },
    {
      "id": "bcbsnc-precert",
      "label": "Blue Cross Blue Shield of North Carolina (Blue Cross NC) prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-bcbsnc",
      "rules": [
        "R-PA-BCBSNC-001",
        "R-PA-BCBSNC-002"
      ],
      "url": "https://www.bcbsnc.com/providers/prior-authorization",
      "lastVerified": "2026-09-15",
      "alsoCited": [
        "https://www.bcbsnc.com/providers/policies-guidelines-codes/medical-policies",
        "https://www.bcbsnc.com/content/dam/bcbsnc/pdf/providers/forms-documents/prior-authorization/commercial/general-requests/prior-approval-request-form.pdf",
        "https://www.bcbsnc.com/providers/provider-news/2026/reminder-save-time-on-prior-authorizations-with-care-affiliate-functionality",
        "https://www.bcbsnc.com/providers/prior-authorization/request-ppa",
        "https://www.bcbsnc.com/content/dam/bcbsnc/pdf/providers/forms-documents/prior-authorization/commercial/administrative/in-network-benefit-review-request-prc-fax-form.pdf",
        "https://www.bcbsnc.com/providers/provider-news/2026/manage-prior-authorizations-through-care-affiliate-portal-blue-e",
        "https://www.bcbsnc.com/providers/provider-news/2022/notification-emergency-inpatient-admission",
        "https://www.bcbsnc.com/providers/policies-guidelines-codes/cpt-service-codes",
        "https://www.bcbsnc.com/providers/prior-authorization/metrics",
        "https://www.bcbsnc.com/providers/provider-news/2025/new-site-of-care-program-minor-surgical-procedures-effective-10-01-2025",
        "https://www.bcbsnc.com/providers/provider-news/2025/new-site-of-care-program-musculoskeletal-procedures-effective-07-01-2025",
        "https://www.bcbsnc.com/providers/policies-guidelines-codes/commercial/reimbursement/updates/ndc",
        "https://www.bcbsnc.com/providers/prior-authorization/prescription-drugs",
        "https://www.bcbsnc.com/members/health-plans/drug-search",
        "https://www.bcbsnc.com/providers/provider-news/2024/changes-in-prior-authorizations-for-blue-cross-nc-medicare-advantage-members-effective-01-01-2025",
        "https://www.bcbsnc.com/providers/policies-guidelines-codes/commercial/home-health-dme/updates/durable-medical-equipment-dme",
        "https://www.bluecrossnc.com/content/dam/bcbsnc/pdf/providers/prior-authorization/forms-documents/commercial-forms/behavioral-health/commercial-inpatient-psychiatric-care-fax-form.pdf",
        "https://www.bluecrossnc.com/content/dam/bcbsnc/pdf/providers/policies-guidelines-codes/policies/commercial/administrative/investigational_experimental_services.pdf",
        "https://www.bluecrossnc.com/content/dam/bcbsnc/pdf/providers/policies-guidelines-codes/policies/commercial/administrative/clinical_trial_services.pdf",
        "https://www.bcbsnc.com/providers/provider-news/2025/introducing-blue-home-with-cone-health-for-individual-under-65-market"
      ]
    },
    {
      "id": "horizon-precert",
      "label": "Horizon Blue Cross Blue Shield of New Jersey prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-horizon",
      "rules": [
        "R-PA-HORIZON-001",
        "R-PA-HORIZON-002"
      ],
      "url": "https://www.horizonblue.com/providers/policies-procedures/utilization-management",
      "lastVerified": "2026-09-15",
      "alsoCited": [
        "https://services3.horizon-bcbsnj.com/hcm/MedPol2.nsf/homePage",
        "https://www.availity.com/horizon/Availity/",
        "https://learnmore.horizonblue.com/affordability",
        "https://www.myprime.com/en/forms/coverage-determination/step-therapy.html"
      ]
    },
    {
      "id": "bcbst-precert",
      "label": "Blue Cross Blue Shield of Tennessee prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-bcbst",
      "rules": [
        "R-PA-BCBST-001",
        "R-PA-BCBST-002"
      ],
      "url": "https://provider.bcbst.com/tools-resources/authorizations-appeals",
      "lastVerified": "2026-09-15",
      "alsoCited": [
        "https://provider.bcbst.com/tools-resources/manuals-policies-guidelines",
        "https://content.bcbst.com/api/public/content/commercial_auth_fax_form.pdf",
        "https://www.bcbst.com/docs/providers/Commercial-Prior-Auth-Requirements.pdf",
        "https://www.bcbst.com/providers/manuals/bcbstpam.pdf",
        "https://www.bcbst.com/docs/providers/commercial_high_tech_imaging_authorization_request_form.pdf",
        "https://www.bcbst.com/docs/providers/hti/high_tech_imaging_auth_code_list.pdf",
        "https://content.bcbst.com/api/public/content/comm_bc_pad_step_therapy_guide.pdf",
        "https://content.bcbst.com/api/public/content/commercial_genetic_testing_request_form.pdf",
        "https://content.bcbst.com/api/public/content/provider-administered-medication-auth.pdf",
        "https://content.bcbst.com/api/public/content/commercial_dme_services_auth_request_re.pdf",
        "https://content.bcbst.com/api/public/content/prov-psychiatric-clinical-service-authorization.pdf",
        "https://content.bcbst.com/api/public/content/commercial-transplant-authorization-request-form.pdf",
        "https://content.bcbst.com/api/public/content/medical-policy-appeals-process.pdf",
        "https://content.bcbst.com/api/public/content/commercial-utilization-management-appeal.pdf",
        "https://content.bcbst.com/api/public/content/commercial_predetermination_request_re.pdf"
      ]
    },
    {
      "id": "bcbsma-precert",
      "label": "Blue Cross Blue Shield of Massachusetts prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-bcbsma",
      "rules": [
        "R-PA-BCBSMA-001",
        "R-PA-BCBSMA-002"
      ],
      "url": "https://provider.bluecrossma.com/",
      "lastVerified": "2026-06-04",
      "alsoCited": [
        "https://provider.bluecrossma.com/ProviderHome/portal/home/News2/!ut/p/z0/fY9BTwJBDIX_Si-byIHMAMZ4NagBORjjBeZiyjCyA7Pt0pll3X9v1xiP3tq-772XGme2xhFe4xFLZMKk-87dfazm6-Vsc29f7Xr-aN-eZqv3xfNmYZe35sW4_wFNiKfLxT0Y55lK-Cpm2wpf4yEItCwFE_wIVCDFvaAMlf0DvJ4FU2Up9LmyPkWKXh1IB2hrlAa94pgSUCg9y3mEOCXcs-gPdIQ-lhoG7gC9cM5Q6gCNpmpIHTCpOLZH6roG-BM8SoAbYprm4Dudx6bfcQqZG3XXUIY25Ilpz273DZgl9JY!/",
        "https://provider.bluecrossma.com/ProviderHome/portal/home/clinical-resources/prior-authorization/cancer-care/",
        "https://provider.bluecrossma.com/ProviderHome/portal/home/clinical-resources/prior-authorization/genetic-testing/",
        "https://provider.bluecrossma.com/ProviderHome/portal/home/clinical-resources/prior-authorization/high-tech-radiology/",
        "https://provider.bluecrossma.com/ProviderHome/portal/home/clinical-resources/prior-authorization/prior-auth-overview/",
        "https://provider.bluecrossma.com/ProviderHome/portal/home/clinical-resources/clinical-criteria-and-guidelines/medical-policies/",
        "https://provider.bluecrossma.com/ProviderHome/portal/home/quality-and-performance/quality-indicators/blue-distinction/",
        "https://provider.bluecrossma.com/ProviderHome/wcm/connect/11593699-ec02-45ea-b5fe-f0a70c8b839d/MPC_031016-1x-F_Out-of-Network-Form-for-BH-MedSurg_Final.pdf?MOD=AJPERES",
        "https://provider.bluecrossma.com/ProviderHome/wcm/connect/provider%2Bportal%2Bcontent%2Blibrary/provider%2Bcentral/etools/etools",
        "https://provider.bluecrossma.com/eforms/medication-prior-auth?secure=true"
      ]
    },
    {
      "id": "bcbsal-precert",
      "label": "Blue Cross Blue Shield of Alabama prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-bcbsal",
      "rules": [
        "R-PA-BCBSAL-001",
        "R-PA-BCBSAL-002"
      ],
      "url": "https://www.bcbsal.org/web/precertification.html",
      "lastVerified": "2026-06-04",
      "alsoCited": [
        "https://providers.bcbsal.org/portal/resources/-/resources/category/3772311",
        "https://providers.bcbsal.org/portal/resources/-/resources/category/994514",
        "https://providers.bcbsal.org/portal/resources/-/resources/category/1564136",
        "https://providers.bcbsal.org/portal/documents/10226/306297/Preferred%2BRadiology%2BProvider%2BProgram%2B2015%2BFrequently%2BAsked%2BQuestions%2Band%2BAnswers/8ef70674-f389-45f0-befe-64a53847d6a9?t=1677698583470",
        "https://providers.bcbsal.org/portal/documents/10226/305944/blue%2Badvantage%2Bprovider%2Bmanual/db5b8fd0-d9a3-436a-bab0-db5f662b4919",
        "https://providers.bcbsal.org/portal/resources/-/resource/viewArticle/NGAW9UB5TT",
        "https://providers.bcbsal.org/portal/web/pa/resources/-/resource/viewArticle/TBUFOONPGI",
        "https://providers.bcbsal.org/portal/resources/-/resource/viewArticle/JDAFGFPZ5Y",
        "https://providers.bcbsal.org/portal/documents/10226/306297/InterQual%2BConnect%2BFrequently%2BAsked%2BQuestions/288c8d37-d119-e320-f301-708bd95c87b0",
        "https://providers.bcbsal.org/portal/web/pa/resources/-/resource/viewArticle/FYP640IW0U",
        "https://providers.bcbsal.org/portal/web/pa/resources?_resourcesportlet_WAR_paresourcesportlet_action=expandResource&_resourcesportlet_WAR_paresourcesportlet_expanded=true&p_p_id=resourcesportlet_WAR_paresourcesportlet&p_p_lifecycle=1&p_p_mode=view&p_p_state=normal&p_r_p_p_http%3A%2F%2Fproviders.bcbsal.org%2Fpublic-render-parameters_categoryId=1415159403",
        "https://providers.bcbsal.org/portal/resources/-/resources/category/360722",
        "https://providers.bcbsal.org/portal/documents/10226/306297/Preservice%2BAppeals%2Band%2BConcurrent%2BAppeal%2BProcess/d52f32fb-40be-45ff-bf8f-de5b1fa607f1"
      ]
    },
    {
      "id": "bcbssc-precert",
      "label": "Blue Cross Blue Shield of South Carolina prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-bcbssc",
      "rules": [
        "R-PA-BCBSSC-001",
        "R-PA-BCBSSC-002"
      ],
      "url": "https://www.southcarolinablues.com/en/home/providers.html",
      "lastVerified": "2026-06-05",
      "alsoCited": [
        "https://www.southcarolinablues.com/en/home/providers/policies-and-authorizations/prior-authorization.html",
        "https://www.southcarolinablues.com/en/home/providers/policies-and-authorizations/medical-policies.html",
        "https://www.southcarolinablues.com/web/public/brands/sc/providers/news-and-events/current-news/",
        "https://www.southcarolinablues.com/web/public/brands/sc/providers/news-and-events/news-archive/2023-news/blue-distinction-centers/",
        "https://www.southcarolinablues.com/web/public/resources/a2889cf1-bac0-4ff6-8362-b0300457f315/2026%2BProvider%2BAdministrative%2BOffice%2BManual.pdf?CVID=pSb97W5&MOD=AJPERES"
      ]
    },
    {
      "id": "arkbcbs-precert",
      "label": "Arkansas Blue Cross and Blue Shield prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-arkbcbs",
      "rules": [
        "R-PA-ARKBCBS-001",
        "R-PA-ARKBCBS-002"
      ],
      "url": "https://www.arkansasbluecross.com/providers",
      "lastVerified": "2026-06-05",
      "alsoCited": [
        "https://www.arkansasbluecross.com/providers/resource-center/prior-approval-for-requested-services",
        "https://www.arkansasbluecross.com/providers/medical-providers/approval-information-for-radiological-services",
        "https://www.arkansasbluecross.com/docs/librariesprovider9/providers/arkbluecross/abcbs-provider-manual.pdf"
      ]
    },
    {
      "id": "bluekc-precert",
      "label": "Blue Cross and Blue Shield of Kansas City (Blue KC) prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-bluekc",
      "rules": [
        "R-PA-BLUEKC-001",
        "R-PA-BLUEKC-002"
      ],
      "url": "https://providers.bluekc.com/Content/PDFs/PRG/2026-ProviderReferenceGuide.pdf",
      "lastVerified": "2026-09-17",
      "alsoCited": [
        "https://providers.bluekc.com/Authorizations"
      ]
    },
    {
      "id": "bcbsmn-precert",
      "label": "Blue Cross and Blue Shield of Minnesota prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-bcbsmn",
      "rules": [
        "R-PA-BCBSMN-001",
        "R-PA-BCBSMN-002"
      ],
      "url": "https://www.bluecrossmn.com/providers",
      "lastVerified": "2026-09-17",
      "alsoCited": [
        "https://www.bluecrossmn.com/sites/default/files/DAM/2023-05/bcbsmn-provider-policy-and-procedure-manual.pdf"
      ]
    },
    {
      "id": "bcbsla-precert",
      "label": "Blue Cross and Blue Shield of Louisiana prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-bcbsla",
      "rules": [
        "R-PA-BCBSLA-001",
        "R-PA-BCBSLA-002"
      ],
      "url": "https://www.lablue.com/providers",
      "lastVerified": "2026-09-17",
      "alsoCited": [
        "https://providers.lablue.com/-/media/Files/Providers/Professional%20Provider%20Office%20Manual/2025/Prof%20Manual%202025%20Section%204%20pdf.pdf"
      ]
    },
    {
      "id": "hmsa-precert",
      "label": "HMSA (Hawaii Medical Service Association, Blue Cross Blue Shield of Hawaii) prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-hmsa",
      "rules": [
        "R-PA-HMSA-001",
        "R-PA-HMSA-002"
      ],
      "url": "https://prc.hmsa.com/s/article/Provider-Manual-for-Prior-Authorization",
      "lastVerified": "2026-09-18",
      "alsoCited": [
        "https://prc.hmsa.com/s/article/Services-That-Require-Precertification"
      ]
    },
    {
      "id": "medi-cal-precert",
      "label": "Medi-Cal (California Medicaid) prior-authorization / Treatment Authorization Request requirements, provider manuals, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-ca",
      "rules": [
        "R-PA-MCAL-001",
        "R-PA-MCAL-002"
      ],
      "url": "https://mcweb.apps.prd.cammis.medi-cal.ca.gov/",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "ny-medicaid-precert",
      "label": "New York State Medicaid (eMedNY) prior-authorization requirements, provider manuals, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-ny",
      "rules": [
        "R-PA-MCNY-001",
        "R-PA-MCNY-002"
      ],
      "url": "https://www.emedny.org/",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "tx-medicaid-precert",
      "label": "Texas Medicaid (TMHP -- Texas Medicaid & Healthcare Partnership) prior-authorization requirements, provider manuals, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-tx",
      "rules": [
        "R-PA-MCTX-001",
        "R-PA-MCTX-002"
      ],
      "url": "https://www.tmhp.com/",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "fl-medicaid-precert",
      "label": "Florida Medicaid (AHCA -- Agency for Health Care Administration / FMMIS) prior-authorization requirements, provider manuals, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-fl",
      "rules": [
        "R-PA-MCFL-001",
        "R-PA-MCFL-002"
      ],
      "url": "https://ahca.myflorida.com/medicaid.html",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "oh-medicaid-precert",
      "label": "Ohio Medicaid (Ohio Department of Medicaid / Provider Network Management) prior-authorization requirements, provider manuals, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-oh",
      "rules": [
        "R-PA-MCOH-001",
        "R-PA-MCOH-002"
      ],
      "url": "https://medicaid.ohio.gov/providers",
      "lastVerified": "2026-09-18",
      "alsoCited": [
        "https://codes.ohio.gov/ohio-administrative-code/rule-5160-1-31",
        "https://codes.ohio.gov/ohio-revised-code/section-5160.34",
        "https://codes.ohio.gov/ohio-revised-code/section-5164.7514",
        "https://codes.ohio.gov/ohio-administrative-code/rule-5160-1-11"
      ]
    },
    {
      "id": "il-medicaid-precert",
      "label": "Illinois Medicaid (HFS -- Department of Healthcare and Family Services / IMPACT / MEDI) prior-authorization requirements, provider manuals, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-il",
      "rules": [
        "R-PA-MCIL-001",
        "R-PA-MCIL-002"
      ],
      "url": "https://hfs.illinois.gov/medicalproviders.html",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "wa-medicaid-precert",
      "label": "Washington Apple Health / Medicaid (Health Care Authority / ProviderOne) prior-authorization requirements, provider manuals, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-wa",
      "rules": [
        "R-PA-MCWA-001",
        "R-PA-MCWA-002"
      ],
      "url": "https://www.hca.wa.gov/billers-providers-partners",
      "lastVerified": "2026-09-18",
      "alsoCited": [
        "https://www.hca.wa.gov/assets/billers-and-providers/inpatient-hospital-bg-20260401.pdf",
        "https://www.hca.wa.gov/assets/billers-and-providers/Home-Health-Services-bg-20231001.pdf"
      ]
    },
    {
      "id": "ga-medicaid-precert",
      "label": "Georgia Medicaid (Department of Community Health / GAMMIS) prior-authorization requirements, provider manuals, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-ga",
      "rules": [
        "R-PA-MCGA-001",
        "R-PA-MCGA-002"
      ],
      "url": "https://medicaid.georgia.gov/providers",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "nc-medicaid-precert",
      "label": "North Carolina Medicaid (NC DHHS / NCTracks) prior-authorization requirements, provider manuals, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-nc",
      "rules": [
        "R-PA-MCNC-001",
        "R-PA-MCNC-002"
      ],
      "url": "https://medicaid.ncdhhs.gov/providers",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "pa-medicaid-precert",
      "label": "Pennsylvania Medicaid / Medical Assistance (PA DHS / PROMISe / HealthChoices) prior-authorization requirements, provider handbooks, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-pa",
      "rules": [
        "R-PA-MCPA-001",
        "R-PA-MCPA-002"
      ],
      "url": "https://www.pa.gov/agencies/dhs",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "mi-medicaid-precert",
      "label": "Michigan Medicaid (MDHHS / CHAMPS / Healthy Michigan Plan) prior-authorization requirements, Medicaid Provider Manual, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-mi",
      "rules": [
        "R-PA-MCMI-001",
        "R-PA-MCMI-002"
      ],
      "url": "https://www.michigan.gov/mdhhs/doing-business/providers",
      "lastVerified": "2026-09-18",
      "alsoCited": [
        "https://www.mdch.state.mi.us/dch-medicaid/manuals/MedicaidProviderManual.pdf"
      ]
    },
    {
      "id": "nj-medicaid-precert",
      "label": "New Jersey Medicaid / NJ FamilyCare (NJ DHS / DMAHS / NJMMIS) prior-authorization requirements, provider manuals, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-nj",
      "rules": [
        "R-PA-MCNJ-001",
        "R-PA-MCNJ-002"
      ],
      "url": "https://www.nj.gov/humanservices/dmahs/",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "az-medicaid-precert",
      "label": "Arizona Medicaid / AHCCCS (Arizona Health Care Cost Containment System / AHCCCS Online) prior-authorization requirements, provider manuals, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-az",
      "rules": [
        "R-PA-MCAZ-001",
        "R-PA-MCAZ-002"
      ],
      "url": "https://www.azahcccs.gov/",
      "lastVerified": "2026-09-18",
      "alsoCited": [
        "https://www.azahcccs.gov/shared/Downloads/MedicalPolicyManual/800/820.pdf",
        "https://www.azahcccs.gov/shared/Downloads/MedicalPolicyManual/800/810.pdf"
      ]
    },
    {
      "id": "in-medicaid-precert",
      "label": "Indiana Medicaid / Indiana Health Coverage Programs (FSSA / OMPP / Healthy Indiana Plan / IHCP / CoreMMIS) prior-authorization requirements, provider manuals, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-in",
      "rules": [
        "R-PA-MCIN-001",
        "R-PA-MCIN-002"
      ],
      "url": "https://www.in.gov/medicaid/providers/",
      "lastVerified": "2026-09-18",
      "alsoCited": [
        "https://www.in.gov/medicaid/providers/files/modules/prior-authorization.pdf"
      ]
    },
    {
      "id": "cms-opd-pa-list",
      "label": "CMS Hospital Outpatient Department (OPD) Prior Authorization required-services list (blepharoplasty, botulinum toxin, panniculectomy, rhinoplasty, vein ablation, cervical fusion with disc removal, implanted spinal neurostimulators, facet joint interventions) -- the bundled CPT list backing the first real -004-style membership test",
      "ruleFamily": "cms-opd-pa",
      "rules": [
        "R-PA-OPD-001"
      ],
      "url": "https://www.cms.gov/data-research/monitoring-programs/medicare-fee-service-compliance-programs/prior-authorization-pre-claim-review-initiatives/prior-authorization-certain-hospital-outpatient-department-opd-services",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "ops-fed-holidays",
      "label": "Federal holidays (5 U.S.C. 6103) backing lib/deadline.js business-day deadline math (fixed + floating holidays, federal weekend observance)",
      "ruleFamily": "ops-v63",
      "rules": [],
      "url": "https://www.law.cornell.edu/uscode/text/5/6103",
      "lastVerified": "2026-06-10"
    },
    {
      "id": "ops-medicare-appeal-deadlines",
      "label": "Medicare claim appeal-level filing deadlines (42 CFR Part 405 Subpart I: redetermination 120 d, QIC 180 d, ALJ/OMHA 60 d, Council 60 d, federal court 60 d) backing appeal-deadline and the OA2 denial routing",
      "ruleFamily": "ops-v63",
      "rules": [],
      "url": "https://www.ecfr.gov/current/title-42/chapter-IV/subchapter-B/part-405/subpart-I",
      "lastVerified": "2026-06-10"
    },
    {
      "id": "ops-medicare-aic",
      "label": "Medicare appeal amount-in-controversy thresholds (CY2026: ALJ $200, federal court $1,960; annually indexed, Fed Reg 2025-21879) backing appeal-deadline",
      "ruleFamily": "ops-v63",
      "rules": [],
      "url": "https://www.federalregister.gov/documents/2025/12/04/2025-21879/medicare-program-medicare-appeals-adjustment-to-the-amount-in-controversy-threshold-amounts-for",
      "lastVerified": "2026-06-10"
    },
    {
      "id": "ops-medicare-timely-filing",
      "label": "Medicare claim timely-filing one-calendar-year basis (42 CFR 424.44; ACA 6404) backing timely-filing",
      "ruleFamily": "ops-v63",
      "rules": [],
      "url": "https://www.ecfr.gov/current/title-42/chapter-IV/subchapter-B/part-424/subpart-C/section-424.44",
      "lastVerified": "2026-06-10"
    },
    {
      "id": "ops-cms-0057f-pa-windows",
      "label": "CMS Interoperability and Prior Authorization Final Rule (CMS-0057-F, 2024) decision windows (standard 7 calendar days, expedited 72 hours; effective 2026 for impacted payers) backing pa-turnaround",
      "ruleFamily": "ops-v63",
      "rules": [],
      "url": "https://www.federalregister.gov/documents/2024/02/08/2024-00895/medicare-and-medicaid-programs-patient-protection-and-affordable-care-act-advancing-interoperability",
      "lastVerified": "2026-06-10"
    },
    {
      "id": "ops-ama-em-2021",
      "label": "AMA CPT 2021 office/outpatient E/M guidelines edition (2-of-3 Medical Decision Making grid; extended to other E/M settings 2023) backing em-mdm",
      "ruleFamily": "ops-v63",
      "rules": [],
      "url": "https://www.ama-assn.org/practice-management/cpt/cpt-evaluation-and-management",
      "lastVerified": "2026-06-10"
    },
    {
      "id": "ops-medicare-overpayment-60day",
      "label": "Medicare 60-day overpayment report-and-return rule (42 CFR 401.305; ACA 6402(a) / 42 U.S.C. 1320a-7k(d)) backing overpayment-60day",
      "ruleFamily": "ops-v63",
      "rules": [],
      "url": "https://www.ecfr.gov/current/title-42/chapter-IV/subchapter-A/part-401/subpart-D/section-401.305",
      "lastVerified": "2026-06-10"
    },
    {
      "id": "billing-pfs-conversion-factor",
      "label": "CMS Physician Fee Schedule conversion factor (CY2026: $32.7442 per RVU; annual PFS Final Rule) backing rvu-payment. Overridable per call to model a percent-of-Medicare contract.",
      "ruleFamily": "billing-v78",
      "rules": [],
      "url": "https://www.cms.gov/medicare/payment/fee-schedules/physician",
      "lastVerified": "2026-06-13"
    },
    {
      "id": "billing-sequestration-rate",
      "label": "Medicare sequestration rate (2% of the program-payment portion; Budget Control Act of 2011 Pub. L. 112-25 251A) backing sequestration-adjust. Overridable to model the suspended/phased rates Congress has set.",
      "ruleFamily": "billing-v78",
      "rules": [],
      "url": "https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title2-section901a&num=0&edition=prelim",
      "lastVerified": "2026-06-13"
    },
    {
      "id": "billing-surgical-payment-percentages",
      "label": "MPFS surgical payment percentages (assistant at surgery 16%; co-surgeon 62.5% to each; CMS Pub. 100-04 Ch. 12 20.4.3/40.8) backing multi-surgeon-pay.",
      "ruleFamily": "billing-v78",
      "rules": [],
      "url": "https://www.cms.gov/regulations-and-guidance/guidance/manuals/downloads/clm104c12.pdf",
      "lastVerified": "2026-06-13"
    },
    {
      "id": "billing-mppr-bilateral-factors",
      "label": "Multiple-procedure (100% highest / 50% each subsequent) and bilateral (150%) reduction factors and the MPFS MULT PROC / BILAT SURG indicator semantics (CMS Pub. 100-04 Ch. 12 40.6/40.7) backing mppr and bilateral-pay.",
      "ruleFamily": "billing-v78",
      "rules": [],
      "url": "https://www.cms.gov/regulations-and-guidance/guidance/manuals/downloads/clm104c12.pdf",
      "lastVerified": "2026-06-13"
    },
    {
      "id": "billing-ncci-ptp-indicators",
      "label": "NCCI procedure-to-procedure modifier-indicator semantics (0 = no modifier permitted; 1 = a permitted NCCI-associated modifier may bypass; 9 = edit deleted/not active) and the NCCI-associated-modifier set (anatomic, global-surgery, 59/X{EPSU}) backing ncci-ptp. NCCI Policy Manual Ch. I; Pub. 100-04 Ch. 23. No PTP edit file ships -- the indicator is entered.",
      "ruleFamily": "billing-v79",
      "rules": [],
      "url": "https://www.cms.gov/medicare/coding-billing/national-correct-coding-initiative-ncci-edits",
      "lastVerified": "2026-06-13"
    },
    {
      "id": "billing-mue-mai-semantics",
      "label": "MUE Adjudication Indicator (MAI) semantics (1 = claim-line edit; 2 = date-of-service absolute, never payable; 3 = date-of-service reviewable with documentation) backing mue-check. CMS Medically Unlikely Edits program. No MUE value table ships -- the value and MAI are entered.",
      "ruleFamily": "billing-v79",
      "rules": [],
      "url": "https://www.cms.gov/medicare/coding-billing/national-correct-coding-initiative-ncci-edits/medicare-ncci-medically-unlikely-edits-mues",
      "lastVerified": "2026-06-13"
    },
    {
      "id": "billing-modifier-59-xepsu",
      "label": "The 59 / X{EPSU} distinct-procedural-service hierarchy (XE separate encounter, XS separate structure, XP separate practitioner, XU unusual non-overlapping; 59 only when no X-modifier fits) backing modifier-x-selector. CMS MLN 'Proper Use of Modifiers 59 & X{EPSU}'.",
      "ruleFamily": "billing-v79",
      "rules": [],
      "url": "https://www.cms.gov/files/document/mln1783722-proper-use-modifiers-59-xe-xp-xs-xu.pdf",
      "lastVerified": "2026-06-13"
    },
    {
      "id": "billing-global-surgery-days",
      "label": "MPFS GLOB DAYS definitions (000/010/090 = 0/10/90 postoperative days, 090 adds 1 preoperative day; XXX/YYY/ZZZ/MMM non-numeric) and the global-package modifiers (24/25/57/58/78/79) backing global-period. CMS Pub. 100-04 Ch. 12 40; MLN Global Surgery Booklet.",
      "ruleFamily": "billing-v79",
      "rules": [],
      "url": "https://www.cms.gov/files/document/mln907166-global-surgery-booklet.pdf",
      "lastVerified": "2026-06-13"
    },
    {
      "id": "billing-modifier-ordering",
      "label": "The pricing-before-informational modifier-sequencing convention and the pricing/informational classification of the common CPT/HCPCS modifiers backing modifier-order. CMS Pub. 100-04 Ch. 12 / 23 modifier-reporting guidance and payer claim-editing convention.",
      "ruleFamily": "billing-v79",
      "rules": [],
      "url": "https://www.cms.gov/regulations-and-guidance/guidance/manuals/downloads/clm104c12.pdf",
      "lastVerified": "2026-06-13"
    },
    {
      "id": "billing-em-mdm-2023-edition",
      "label": "The CPT 2023 E/M edition and the setting-specific MDM code maps (inpatient/observation 99221-99233, ED 99281-99285, nursing facility 99304-99310, home/residence 99341-99350; 99343 deleted 2023) backing em-mdm-2023. AMA CPT 2023 E/M Guidelines. No CPT descriptor file ships -- the MDM elements are entered.",
      "ruleFamily": "billing-v80",
      "rules": [],
      "url": "https://www.ama-assn.org/practice-management/cpt/cpt-evaluation-and-management",
      "lastVerified": "2026-06-15"
    },
    {
      "id": "billing-critical-care-bands",
      "label": "The 99291 (first 30-74 min) / 99292 (each additional 30 min) critical-care time bands and the separately-reported-procedure subtraction rule backing critical-care-time. AMA CPT; CMS Pub. 100-04 Ch. 12 30.6.12.",
      "ruleFamily": "billing-v80",
      "rules": [],
      "url": "https://www.cms.gov/regulations-and-guidance/guidance/manuals/downloads/clm104c12.pdf",
      "lastVerified": "2026-06-15"
    },
    {
      "id": "billing-split-shared-fs",
      "label": "The split (or shared) visit substantive-portion policy, the FS modifier, and the 85% NPP payment percentage backing split-shared. CMS Pub. 100-04 Ch. 12 30.6.18; PFS split/shared visit policy (2024 rule).",
      "ruleFamily": "billing-v80",
      "rules": [],
      "url": "https://www.cms.gov/regulations-and-guidance/guidance/manuals/downloads/clm104c12.pdf",
      "lastVerified": "2026-06-15"
    },
    {
      "id": "billing-prolonged-thresholds",
      "label": "The prolonged-service add-on codes (AMA 99417/99418 vs Medicare G2212/G0316) and their per-primary-code time thresholds (99205 75/89, 99215 55/69, 99223 90/104, 99233 65/79; each unit +15 min) backing prolonged-services. AMA CPT; CMS Pub. 100-04 Ch. 12.",
      "ruleFamily": "billing-v80",
      "rules": [],
      "url": "https://www.cms.gov/medicare/payment/fee-schedules/physician",
      "lastVerified": "2026-06-15"
    },
    {
      "id": "billing-therapy-8minute",
      "label": "The Medicare 8-minute rule band table (8-22=1, 23-37=2, 38-52=3, 53-67=4, each +15 adds a unit) and the AMA Rule of Eights per-service contrast backing therapy-units. CMS Pub. 100-04 Ch. 5 20.2; 42 CFR 410.",
      "ruleFamily": "billing-v80",
      "rules": [],
      "url": "https://www.cms.gov/regulations-and-guidance/guidance/manuals/downloads/clm104c05.pdf",
      "lastVerified": "2026-06-15"
    },
    {
      "id": "billing-anesthesia-cf-direction",
      "label": "The anesthesia payment formula ((base+time+modifying units) x CF; time unit = 15 min), the default national anesthesia conversion factor (CY2025 $20.3178, overridable), and the medical-direction percentages (AA/QZ 100%, QK/QY/QX 50%, AD flat 3 base units) backing anesthesia-units. CMS Pub. 100-04 Ch. 12 50; ASA RVG base units entered, not shipped.",
      "ruleFamily": "billing-v80",
      "rules": [],
      "url": "https://www.cms.gov/regulations-and-guidance/guidance/manuals/downloads/clm104c12.pdf",
      "lastVerified": "2026-06-15"
    },
    {
      "id": "billing-hcpcs-drug-units",
      "label": "The HCPCS Level II drug billing-unit-of-measure convention (dose / code billing-unit size, rounded per the descriptor's rule) backing ndc-hcpcs-units. The unit size is entered from the code descriptor -- no drug-pricing file ships. CMS HCPCS Level II descriptors; CMS Pub. 100-04 Ch. 17.",
      "ruleFamily": "billing-v81",
      "rules": [],
      "url": "https://www.cms.gov/medicare/coding-billing/healthcare-common-procedure-system",
      "lastVerified": "2026-06-15"
    },
    {
      "id": "billing-jw-jz-wastage",
      "label": "The single-dose-vial drug-wastage rule (administered on one line, discarded with modifier JW; JZ to attest zero waste, required since 2023-07-01) and the multi-dose-vial JW ineligibility gate backing drug-wastage. CMS Pub. 100-04 Ch. 17 §40; CMS JW/JZ modifier guidance.",
      "ruleFamily": "billing-v81",
      "rules": [],
      "url": "https://www.cms.gov/medicare/payment/part-b-drugs/discarded-drugs",
      "lastVerified": "2026-06-15"
    },
    {
      "id": "billing-infusion-hierarchy",
      "label": "The CPT 96360-96379 infusion/injection/hydration initial-code hierarchy (chemo > therapeutic > hydration; within a category, infusion > push), the one-initial-per-encounter rule, and the 16-minute infusion-to-push reclassification floor backing infusion-hierarchy. AMA CPT 96360-96379; CMS Pub. 100-04 Ch. 12.",
      "ruleFamily": "billing-v81",
      "rules": [],
      "url": "https://www.cms.gov/regulations-and-guidance/guidance/manuals/downloads/clm104c12.pdf",
      "lastVerified": "2026-06-15"
    },
    {
      "id": "billing-medicare-cost-share",
      "label": "The CMS CY2026 Medicare cost-sharing amounts (announced 2025-11-14) backing medicare-cost-share: Part A inpatient deductible $1,736/benefit period, days 61-90 coinsurance $434/day, lifetime-reserve $868/day, SNF days 21-100 $217/day; Part B annual deductible $283 then 20% of the approved amount. SSA Title XVIII; CMS annual cost-sharing notice. Overridable per call for a prior year.",
      "ruleFamily": "billing-v82",
      "rules": [],
      "url": "https://www.cms.gov/newsroom/fact-sheets/2026-medicare-parts-b-premiums-deductibles",
      "lastVerified": "2026-06-15"
    },
    {
      "id": "billing-cob-msp-methods",
      "label": "The coordination-of-benefits methods (lesser-of, come-out-whole / benefits-less-paid, non-duplication) and the Medicare Secondary Payer calculation backing cob-calc. 42 CFR Part 411; CMS Pub. 100-05 (Medicare Secondary Payer Manual).",
      "ruleFamily": "billing-v82",
      "rules": [],
      "url": "https://www.cms.gov/medicare/coordination-benefits-recovery/overview",
      "lastVerified": "2026-06-15"
    },
    {
      "id": "billing-nsa-qpa-cost-share",
      "label": "The No Surprises Act QPA-based patient cost-share rule (protected emergency / ancillary-at-in-network-facility services are cost-shared as if in-network off the Qualifying Payment Amount; balance billing prohibited) backing nsa-cost-share. PHS Act §2799A-1/§2799A-2; 45 CFR Part 149.",
      "ruleFamily": "billing-v82",
      "rules": [],
      "url": "https://www.cms.gov/nosurprises",
      "lastVerified": "2026-06-15"
    },
    {
      "id": "billing-ipps-base-rates",
      "label": "The IPPS operating and capital standardized base rates (wage-index adjusted) that, times the MS-DRG relative weight, give the base DRG payment backing drg-payment, before outlier/IME/DSH add-ons. The relative-weight table is the bundled data/drg corpus; the base rates are entered/dated constants. 42 CFR Part 412; CMS IPPS Final Rule.",
      "ruleFamily": "billing-v83",
      "rules": [],
      "url": "https://www.cms.gov/medicare/payment/prospective-payment-systems/acute-inpatient-pps",
      "lastVerified": "2026-06-15"
    },
    {
      "id": "billing-opps-conversion-factor",
      "label": "The OPPS conversion factor (wage adjusted) that, times the APC relative weight, gives the APC payment backing apc-payment, plus the status-indicator packaging set and the multiple-procedure discount. The relative-weight/status table is the bundled data/apc corpus; the conversion factor is an entered/dated constant. 42 CFR Part 419; CMS OPPS Final Rule.",
      "ruleFamily": "billing-v83",
      "rules": [],
      "url": "https://www.cms.gov/medicare/payment/prospective-payment-systems/hospital-outpatient",
      "lastVerified": "2026-06-15"
    },
    {
      "id": "billing-mbi-grammar",
      "label": "The CMS Medicare Beneficiary Identifier (MBI) 11-character position grammar (numeric / alphabetic / alphanumeric by position) and the excluded-letter set S, L, O, I, B, Z backing mbi-validate. Validates format only, not active entitlement. CMS new Medicare card specification.",
      "ruleFamily": "billing-v83",
      "rules": [],
      "url": "https://www.cms.gov/training-education/partner-outreach-resources/new-medicare-card/medical-beneficiary-identifiers-mbis",
      "lastVerified": "2026-06-15"
    }
  ],
  "acknowledgments": []
};
