// GENERATED by scripts/build-pa-staleness-ledger.mjs from
// pa-staleness-ledger.json (repo root). Do not edit by hand: edit the
// JSON and re-run the generator (CI fails on drift via
// scripts/check-pa-staleness.mjs).
//
// spec-v52 §8.3: the staleness ledger bundled for the browser so the
// in-tab PA report audit trail can show per-source staleness with no
// runtime fetch (spec-v50 §3.1 no-network).

export const PA_STALENESS_LEDGER = {
  "_comment": "spec-v52 §8.3 dataset-staleness ledger for the Prior-Auth Packet Linter (pa-lint). Each source backs one or more rule families in lib/pa/rules.js. The maintainer re-verifies each source on the cadence in docs/pa-maintenance.md and bumps lastVerified to the verification date (ISO YYYY-MM-DD). scripts/check-pa-staleness.mjs enforces the policy window in CI. To suppress a known-stale source without re-verifying, add an entry to acknowledgments with an ackDate and a reason. JSON, not YAML, to keep Sophie's zero-dependency posture (spec-v10 §6).",
  "rulesetVersion": "1.0.0",
  "policy": {
    "warnAfterDays": 90,
    "failAfterDays": 365
  },
  "sources": [
    {
      "id": "ama-cpt",
      "label": "AMA CPT code set (short descriptors)",
      "ruleFamily": "core",
      "rules": [
        "R-PA-007",
        "R-PA-008",
        "R-PA-014",
        "R-PA-051"
      ],
      "url": "https://www.ama-assn.org/practice-management/cpt",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "cms-hcpcs",
      "label": "CMS HCPCS Level II code set",
      "ruleFamily": "core",
      "rules": [
        "R-PA-007",
        "R-PA-009"
      ],
      "url": "https://www.cms.gov/medicare/coding-billing/healthcare-common-procedure-system",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "cms-icd10cm",
      "label": "CMS / CDC ICD-10-CM annual code files (public domain)",
      "ruleFamily": "core",
      "rules": [
        "R-PA-010",
        "R-PA-011"
      ],
      "url": "https://www.cms.gov/medicare/coding-billing/icd-10-codes",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "cms-pos",
      "label": "CMS Place of Service (POS) code set",
      "ruleFamily": "core",
      "rules": [
        "R-PA-013"
      ],
      "url": "https://www.cms.gov/medicare/coding-billing/place-of-service-codes/code-sets",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "cms-ncci",
      "label": "CMS National Correct Coding Initiative (NCCI) PTP edits",
      "ruleFamily": "core",
      "rules": [
        "R-PA-012",
        "R-PA-054"
      ],
      "url": "https://www.cms.gov/medicare/coding-billing/national-correct-coding-initiative-ncci-edits",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "nppes-npi",
      "label": "NPPES NPI standard (Luhn-mod-10 with 80840 issuer prefix)",
      "ruleFamily": "core",
      "rules": [
        "R-PA-016",
        "R-PA-019"
      ],
      "url": "https://nppes.cms.hhs.gov/",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "cms-ncd-lcd",
      "label": "CMS Medicare Coverage Database (NCDs, LCDs, LCAs)",
      "ruleFamily": "cms-ffs",
      "rules": [
        "R-PA-CMS-001",
        "R-PA-CMS-005",
        "R-PA-CMS-006"
      ],
      "url": "https://www.cms.gov/medicare-coverage-database/",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "cms-iom-100-08",
      "label": "CMS Internet-Only Manual Pub 100-08 (Program Integrity)",
      "ruleFamily": "cms-ffs",
      "rules": [
        "R-PA-CMS-002",
        "R-PA-CMS-003",
        "R-PA-CMS-004"
      ],
      "url": "https://www.cms.gov/regulations-and-guidance/guidance/manuals/internet-only-manuals-ioms",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "cms-ma-422",
      "label": "CMS Medicare Advantage rules (42 CFR Part 422, organization determinations)",
      "ruleFamily": "cms-ma",
      "rules": [
        "R-PA-MA-001",
        "R-PA-MA-002"
      ],
      "url": "https://www.ecfr.gov/current/title-42/chapter-IV/subchapter-B/part-422",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "medicaid-core",
      "label": "Medicaid program requirements (state-agnostic core, EPSDT)",
      "ruleFamily": "medicaid-core",
      "rules": [
        "R-PA-MCD-001",
        "R-PA-MCD-006"
      ],
      "url": "https://www.medicaid.gov/medicaid/benefits/early-and-periodic-screening-diagnostic-and-treatment/index.html",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "acr-appropriateness",
      "label": "ACR Appropriateness Criteria (advanced imaging)",
      "ruleFamily": "specialty-rad",
      "rules": [
        "R-PA-RAD-001",
        "R-PA-RAD-002"
      ],
      "url": "https://www.acr.org/Clinical-Resources/Clinical-Tools-and-Reference/Appropriateness-Criteria",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "fda-labeling",
      "label": "FDA drug labeling / NDC directory (infusion, specialty drug)",
      "ruleFamily": "specialty-inf",
      "rules": [
        "R-PA-INF-001",
        "R-PA-INF-002"
      ],
      "url": "https://www.accessdata.fda.gov/scripts/cder/ndc/",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "surgical-indication-policy",
      "label": "Payer surgical-indication policy anchors (conservative management, ASA)",
      "ruleFamily": "specialty-surg",
      "rules": [
        "R-PA-SURG-001",
        "R-PA-SURG-003"
      ],
      "url": "https://www.asahq.org/standards-and-practice-parameters/statement-on-asa-physical-status-classification-system",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "dsm-5-tr",
      "label": "APA DSM-5-TR / ASAM / Joint Commission (behavioral health)",
      "ruleFamily": "specialty-bh",
      "rules": [
        "R-PA-BH-001",
        "R-PA-BH-003",
        "R-PA-BH-004"
      ],
      "url": "https://www.psychiatry.org/psychiatrists/practice/dsm",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "nccn-acmg-genetic",
      "label": "NCCN / ACMG / NSGC genetic-testing criteria",
      "ruleFamily": "specialty-gen",
      "rules": [
        "R-PA-GEN-001",
        "R-PA-GEN-002"
      ],
      "url": "https://www.acmg.net/ACMG/Medical-Genetics-Practice-Resources/Practice-Guidelines.aspx",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "aetna-precert",
      "label": "Aetna participating-provider precertification requirements & Clinical Policy Bulletins",
      "ruleFamily": "commercial-aetna",
      "rules": [
        "R-PA-AETNA-001",
        "R-PA-AETNA-002"
      ],
      "url": "https://www.aetna.com/health-care-professionals/precertification.html",
      "lastVerified": "2026-05-30"
    },
    {
      "id": "uhc-precert",
      "label": "UnitedHealthcare prior-authorization / advance-notification requirements, Medical & Drug Policies, and Coverage Determination Guidelines",
      "ruleFamily": "commercial-uhc",
      "rules": [
        "R-PA-UHC-001",
        "R-PA-UHC-002"
      ],
      "url": "https://www.uhcprovider.com/en/prior-auth-advance-notification.html",
      "lastVerified": "2026-06-01"
    },
    {
      "id": "anthem-precert",
      "label": "Anthem Blue Cross Blue Shield (Elevance Health) prior-authorization requirements, Clinical UM Guidelines, and Medical Policies",
      "ruleFamily": "commercial-anthem",
      "rules": [
        "R-PA-ANTHEM-001",
        "R-PA-ANTHEM-002"
      ],
      "url": "https://www.anthem.com/provider/prior-authorization/",
      "lastVerified": "2026-06-01"
    },
    {
      "id": "cigna-precert",
      "label": "Cigna prior-authorization / precertification requirements, Medical Coverage Policies, and eviCore / Evernorth program requirements",
      "ruleFamily": "commercial-cigna",
      "rules": [
        "R-PA-CIGNA-001",
        "R-PA-CIGNA-002"
      ],
      "url": "https://www.cigna.com/health-care-providers/coverage-and-claims/prior-authorization",
      "lastVerified": "2026-06-01"
    },
    {
      "id": "humana-precert",
      "label": "Humana prior-authorization / preauthorization requirements, Medical Coverage Policies, and utilization-management / CenterWell program requirements",
      "ruleFamily": "commercial-humana",
      "rules": [
        "R-PA-HUMANA-001",
        "R-PA-HUMANA-002"
      ],
      "url": "https://www.humana.com/provider/medical-resources/authorizations-referrals",
      "lastVerified": "2026-06-02"
    },
    {
      "id": "hcsc-precert",
      "label": "Health Care Service Corporation (Blue Cross Blue Shield of IL/TX/MT/NM/OK) prior-authorization requirements, Medical Policies, and utilization-management / Prime Therapeutics program requirements",
      "ruleFamily": "commercial-hcsc",
      "rules": [
        "R-PA-HCSC-001",
        "R-PA-HCSC-002"
      ],
      "url": "https://www.bcbsil.com/provider/clinical/clinical-resources/prior-authorization",
      "lastVerified": "2026-06-02"
    },
    {
      "id": "highmark-precert",
      "label": "Highmark (Blue Cross Blue Shield of PA/WV/DE + western NY) prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-highmark",
      "rules": [
        "R-PA-HIGHMARK-001",
        "R-PA-HIGHMARK-002"
      ],
      "url": "https://www.highmark.com/provider/resource-center",
      "lastVerified": "2026-06-03"
    },
    {
      "id": "floridablue-precert",
      "label": "Florida Blue / GuideWell (Blue Cross and Blue Shield of Florida) prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-florida-blue",
      "rules": [
        "R-PA-FLBLUE-001",
        "R-PA-FLBLUE-002"
      ],
      "url": "https://www.floridablue.com/providers/tools-resources/authorizations",
      "lastVerified": "2026-06-03"
    },
    {
      "id": "bcbsm-precert",
      "label": "Blue Cross Blue Shield of Michigan (+ Blue Care Network) prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-bcbsm",
      "rules": [
        "R-PA-BCBSM-001",
        "R-PA-BCBSM-002"
      ],
      "url": "https://www.bcbsm.com/providers/help/authorization-requirements-criteria/",
      "lastVerified": "2026-06-04"
    },
    {
      "id": "blueshieldca-precert",
      "label": "Blue Shield of California prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-blue-shield-ca",
      "rules": [
        "R-PA-BSCA-001",
        "R-PA-BSCA-002"
      ],
      "url": "https://www.blueshieldca.com/en/provider/authorizations",
      "lastVerified": "2026-06-04"
    },
    {
      "id": "ibx-precert",
      "label": "Independence Blue Cross (southeastern Pennsylvania / Philadelphia) prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-ibx",
      "rules": [
        "R-PA-IBX-001",
        "R-PA-IBX-002"
      ],
      "url": "https://www.ibx.com/resources/for-providers/authorizations",
      "lastVerified": "2026-06-04"
    },
    {
      "id": "carefirst-precert",
      "label": "CareFirst BlueCross BlueShield (Maryland / District of Columbia / Northern Virginia) prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-carefirst",
      "rules": [
        "R-PA-CAREFIRST-001",
        "R-PA-CAREFIRST-002"
      ],
      "url": "https://provider.carefirst.com/providers/preauth-precert.page",
      "lastVerified": "2026-06-04"
    },
    {
      "id": "bcbsnc-precert",
      "label": "Blue Cross Blue Shield of North Carolina (Blue Cross NC) prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-bcbsnc",
      "rules": [
        "R-PA-BCBSNC-001",
        "R-PA-BCBSNC-002"
      ],
      "url": "https://www.bluecrossnc.com/providers/prior-authorization",
      "lastVerified": "2026-06-04"
    },
    {
      "id": "horizon-precert",
      "label": "Horizon Blue Cross Blue Shield of New Jersey prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-horizon",
      "rules": [
        "R-PA-HORIZON-001",
        "R-PA-HORIZON-002"
      ],
      "url": "https://www.horizonblue.com/providers/prior-authorizations",
      "lastVerified": "2026-06-04"
    },
    {
      "id": "bcbst-precert",
      "label": "Blue Cross Blue Shield of Tennessee prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-bcbst",
      "rules": [
        "R-PA-BCBST-001",
        "R-PA-BCBST-002"
      ],
      "url": "https://www.bcbst.com/providers/authorizations/",
      "lastVerified": "2026-06-04"
    },
    {
      "id": "bcbsma-precert",
      "label": "Blue Cross Blue Shield of Massachusetts prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-bcbsma",
      "rules": [
        "R-PA-BCBSMA-001",
        "R-PA-BCBSMA-002"
      ],
      "url": "https://provider.bluecrossma.com/",
      "lastVerified": "2026-06-04"
    },
    {
      "id": "bcbsal-precert",
      "label": "Blue Cross Blue Shield of Alabama prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-bcbsal",
      "rules": [
        "R-PA-BCBSAL-001",
        "R-PA-BCBSAL-002"
      ],
      "url": "https://www.bcbsal.org/web/providers/",
      "lastVerified": "2026-06-04"
    },
    {
      "id": "bcbssc-precert",
      "label": "Blue Cross Blue Shield of South Carolina prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-bcbssc",
      "rules": [
        "R-PA-BCBSSC-001",
        "R-PA-BCBSSC-002"
      ],
      "url": "https://www.southcarolinablues.com/web/public/brands/sc/providers/",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "arkbcbs-precert",
      "label": "Arkansas Blue Cross and Blue Shield prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-arkbcbs",
      "rules": [
        "R-PA-ARKBCBS-001",
        "R-PA-ARKBCBS-002"
      ],
      "url": "https://www.arkansasbluecross.com/providers",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "bluekc-precert",
      "label": "Blue Cross and Blue Shield of Kansas City (Blue KC) prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-bluekc",
      "rules": [
        "R-PA-BLUEKC-001",
        "R-PA-BLUEKC-002"
      ],
      "url": "https://providers.bluekc.com/",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "bcbsmn-precert",
      "label": "Blue Cross and Blue Shield of Minnesota prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-bcbsmn",
      "rules": [
        "R-PA-BCBSMN-001",
        "R-PA-BCBSMN-002"
      ],
      "url": "https://www.bluecrossmn.com/providers",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "bcbsla-precert",
      "label": "Blue Cross and Blue Shield of Louisiana prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-bcbsla",
      "rules": [
        "R-PA-BCBSLA-001",
        "R-PA-BCBSLA-002"
      ],
      "url": "https://www.bcbsla.com/providers",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "hmsa-precert",
      "label": "HMSA (Hawaii Medical Service Association, Blue Cross Blue Shield of Hawaii) prior-authorization requirements, Medical Policies, and utilization-management / pharmacy program requirements",
      "ruleFamily": "commercial-hmsa",
      "rules": [
        "R-PA-HMSA-001",
        "R-PA-HMSA-002"
      ],
      "url": "https://hmsa.com/providers/",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "medi-cal-precert",
      "label": "Medi-Cal (California Medicaid) prior-authorization / Treatment Authorization Request requirements, provider manuals, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-ca",
      "rules": [
        "R-PA-MCAL-001",
        "R-PA-MCAL-002"
      ],
      "url": "https://www.medi-cal.ca.gov/",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "ny-medicaid-precert",
      "label": "New York State Medicaid (eMedNY) prior-authorization requirements, provider manuals, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-ny",
      "rules": [
        "R-PA-MCNY-001",
        "R-PA-MCNY-002"
      ],
      "url": "https://www.emedny.org/",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "tx-medicaid-precert",
      "label": "Texas Medicaid (TMHP -- Texas Medicaid & Healthcare Partnership) prior-authorization requirements, provider manuals, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-tx",
      "rules": [
        "R-PA-MCTX-001",
        "R-PA-MCTX-002"
      ],
      "url": "https://www.tmhp.com/",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "fl-medicaid-precert",
      "label": "Florida Medicaid (AHCA -- Agency for Health Care Administration / FMMIS) prior-authorization requirements, provider manuals, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-fl",
      "rules": [
        "R-PA-MCFL-001",
        "R-PA-MCFL-002"
      ],
      "url": "https://ahca.myflorida.com/medicaid",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "oh-medicaid-precert",
      "label": "Ohio Medicaid (Ohio Department of Medicaid / Provider Network Management) prior-authorization requirements, provider manuals, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-oh",
      "rules": [
        "R-PA-MCOH-001",
        "R-PA-MCOH-002"
      ],
      "url": "https://medicaid.ohio.gov/providers",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "il-medicaid-precert",
      "label": "Illinois Medicaid (HFS -- Department of Healthcare and Family Services / IMPACT / MEDI) prior-authorization requirements, provider manuals, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-il",
      "rules": [
        "R-PA-MCIL-001",
        "R-PA-MCIL-002"
      ],
      "url": "https://hfs.illinois.gov/medicalproviders.html",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "wa-medicaid-precert",
      "label": "Washington Apple Health / Medicaid (Health Care Authority / ProviderOne) prior-authorization requirements, provider manuals, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-wa",
      "rules": [
        "R-PA-MCWA-001",
        "R-PA-MCWA-002"
      ],
      "url": "https://www.hca.wa.gov/billers-providers-partners",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "ga-medicaid-precert",
      "label": "Georgia Medicaid (Department of Community Health / GAMMIS) prior-authorization requirements, provider manuals, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-ga",
      "rules": [
        "R-PA-MCGA-001",
        "R-PA-MCGA-002"
      ],
      "url": "https://medicaid.georgia.gov/providers",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "nc-medicaid-precert",
      "label": "North Carolina Medicaid (NC DHHS / NCTracks) prior-authorization requirements, provider manuals, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-nc",
      "rules": [
        "R-PA-MCNC-001",
        "R-PA-MCNC-002"
      ],
      "url": "https://medicaid.ncdhhs.gov/providers",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "pa-medicaid-precert",
      "label": "Pennsylvania Medicaid / Medical Assistance (PA DHS / PROMISe / HealthChoices) prior-authorization requirements, provider handbooks, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-pa",
      "rules": [
        "R-PA-MCPA-001",
        "R-PA-MCPA-002"
      ],
      "url": "https://www.dhs.pa.gov/providers",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "mi-medicaid-precert",
      "label": "Michigan Medicaid (MDHHS / CHAMPS / Healthy Michigan Plan) prior-authorization requirements, Medicaid Provider Manual, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-mi",
      "rules": [
        "R-PA-MCMI-001",
        "R-PA-MCMI-002"
      ],
      "url": "https://www.michigan.gov/mdhhs/doing-business/providers",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "nj-medicaid-precert",
      "label": "New Jersey Medicaid / NJ FamilyCare (NJ DHS / DMAHS / NJMMIS) prior-authorization requirements, provider manuals, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-nj",
      "rules": [
        "R-PA-MCNJ-001",
        "R-PA-MCNJ-002"
      ],
      "url": "https://www.nj.gov/humanservices/dmahs/",
      "lastVerified": "2026-06-05"
    },
    {
      "id": "az-medicaid-precert",
      "label": "Arizona Medicaid / AHCCCS (Arizona Health Care Cost Containment System / AHCCCS Online) prior-authorization requirements, provider manuals, and utilization-management / pharmacy program requirements",
      "ruleFamily": "medicaid-az",
      "rules": [
        "R-PA-MCAZ-001",
        "R-PA-MCAZ-002"
      ],
      "url": "https://www.azahcccs.gov/",
      "lastVerified": "2026-06-05"
    }
  ],
  "acknowledgments": []
};
