// GENERATED by scripts/build-pa-staleness-ledger.mjs from
// pa-staleness-ledger.json (repo root). Do not edit by hand: edit the
// JSON and re-run the generator (CI fails on drift via
// scripts/check-pa-staleness.mjs).
//
// spec-v52 §8.3: the staleness ledger bundled for the browser so the
// in-tab PA report audit trail can show per-source staleness with no
// runtime fetch (spec-v50 §3.1 no-network).

export const PA_STALENESS_LEDGER = {
  "_comment": "spec-v52 §8.3 dataset-staleness ledger for the Prior-Auth Packet Linter (pa-lint). Each source backs one or more rule families in lib/pa/rules.js. The maintainer re-verifies each source on the cadence in docs/pa-maintenance.md and bumps lastVerified to the verification date (ISO YYYY-MM-DD). scripts/check-pa-staleness.mjs enforces the policy window in CI. To suppress a known-stale source without re-verifying, add an entry to acknowledgments with an ackDate and a reason. JSON, not YAML, to keep Sophie's zero-dependency posture (spec-v10 §6).",
  "rulesetVersion": "1.0.0",
  "policy": {
    "warnAfterDays": 90,
    "failAfterDays": 365
  },
  "sources": [
    {
      "id": "ama-cpt",
      "label": "AMA CPT code set (short descriptors)",
      "ruleFamily": "core",
      "rules": [
        "R-PA-007",
        "R-PA-008",
        "R-PA-014",
        "R-PA-051"
      ],
      "url": "https://www.ama-assn.org/practice-management/cpt",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "cms-hcpcs",
      "label": "CMS HCPCS Level II code set",
      "ruleFamily": "core",
      "rules": [
        "R-PA-007",
        "R-PA-009"
      ],
      "url": "https://www.cms.gov/medicare/coding-billing/healthcare-common-procedure-system",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "cms-icd10cm",
      "label": "CMS / CDC ICD-10-CM annual code files (public domain)",
      "ruleFamily": "core",
      "rules": [
        "R-PA-010",
        "R-PA-011"
      ],
      "url": "https://www.cms.gov/medicare/coding-billing/icd-10-codes",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "cms-pos",
      "label": "CMS Place of Service (POS) code set",
      "ruleFamily": "core",
      "rules": [
        "R-PA-013"
      ],
      "url": "https://www.cms.gov/medicare/coding-billing/place-of-service-codes/code-sets",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "cms-ncci",
      "label": "CMS National Correct Coding Initiative (NCCI) PTP edits",
      "ruleFamily": "core",
      "rules": [
        "R-PA-012",
        "R-PA-054"
      ],
      "url": "https://www.cms.gov/medicare/coding-billing/national-correct-coding-initiative-ncci-edits",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "nppes-npi",
      "label": "NPPES NPI standard (Luhn-mod-10 with 80840 issuer prefix)",
      "ruleFamily": "core",
      "rules": [
        "R-PA-016",
        "R-PA-019"
      ],
      "url": "https://nppes.cms.hhs.gov/",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "cms-ncd-lcd",
      "label": "CMS Medicare Coverage Database (NCDs, LCDs, LCAs)",
      "ruleFamily": "cms-ffs",
      "rules": [
        "R-PA-CMS-001",
        "R-PA-CMS-005",
        "R-PA-CMS-006"
      ],
      "url": "https://www.cms.gov/medicare-coverage-database/",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "cms-iom-100-08",
      "label": "CMS Internet-Only Manual Pub 100-08 (Program Integrity)",
      "ruleFamily": "cms-ffs",
      "rules": [
        "R-PA-CMS-002",
        "R-PA-CMS-003",
        "R-PA-CMS-004"
      ],
      "url": "https://www.cms.gov/regulations-and-guidance/guidance/manuals/internet-only-manuals-ioms",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "cms-ma-422",
      "label": "CMS Medicare Advantage rules (42 CFR Part 422, organization determinations)",
      "ruleFamily": "cms-ma",
      "rules": [
        "R-PA-MA-001",
        "R-PA-MA-002"
      ],
      "url": "https://www.ecfr.gov/current/title-42/chapter-IV/subchapter-B/part-422",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "medicaid-core",
      "label": "Medicaid program requirements (state-agnostic core, EPSDT)",
      "ruleFamily": "medicaid-core",
      "rules": [
        "R-PA-MCD-001",
        "R-PA-MCD-006"
      ],
      "url": "https://www.medicaid.gov/medicaid/benefits/early-and-periodic-screening-diagnostic-and-treatment/index.html",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "acr-appropriateness",
      "label": "ACR Appropriateness Criteria (advanced imaging)",
      "ruleFamily": "specialty-rad",
      "rules": [
        "R-PA-RAD-001",
        "R-PA-RAD-002"
      ],
      "url": "https://www.acr.org/Clinical-Resources/Clinical-Tools-and-Reference/Appropriateness-Criteria",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "fda-labeling",
      "label": "FDA drug labeling / NDC directory (infusion, specialty drug)",
      "ruleFamily": "specialty-inf",
      "rules": [
        "R-PA-INF-001",
        "R-PA-INF-002"
      ],
      "url": "https://www.accessdata.fda.gov/scripts/cder/ndc/",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "surgical-indication-policy",
      "label": "Payer surgical-indication policy anchors (conservative management, ASA)",
      "ruleFamily": "specialty-surg",
      "rules": [
        "R-PA-SURG-001",
        "R-PA-SURG-003"
      ],
      "url": "https://www.asahq.org/standards-and-practice-parameters/statement-on-asa-physical-status-classification-system",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "dsm-5-tr",
      "label": "APA DSM-5-TR / ASAM / Joint Commission (behavioral health)",
      "ruleFamily": "specialty-bh",
      "rules": [
        "R-PA-BH-001",
        "R-PA-BH-003",
        "R-PA-BH-004"
      ],
      "url": "https://www.psychiatry.org/psychiatrists/practice/dsm",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "nccn-acmg-genetic",
      "label": "NCCN / ACMG / NSGC genetic-testing criteria",
      "ruleFamily": "specialty-gen",
      "rules": [
        "R-PA-GEN-001",
        "R-PA-GEN-002"
      ],
      "url": "https://www.acmg.net/ACMG/Medical-Genetics-Practice-Resources/Practice-Guidelines.aspx",
      "lastVerified": "2026-05-28"
    },
    {
      "id": "aetna-precert",
      "label": "Aetna participating-provider precertification requirements & Clinical Policy Bulletins",
      "ruleFamily": "commercial-aetna",
      "rules": [
        "R-PA-AETNA-001",
        "R-PA-AETNA-002"
      ],
      "url": "https://www.aetna.com/health-care-professionals/precertification.html",
      "lastVerified": "2026-05-30"
    },
    {
      "id": "uhc-precert",
      "label": "UnitedHealthcare prior-authorization / advance-notification requirements, Medical & Drug Policies, and Coverage Determination Guidelines",
      "ruleFamily": "commercial-uhc",
      "rules": [
        "R-PA-UHC-001",
        "R-PA-UHC-002"
      ],
      "url": "https://www.uhcprovider.com/en/prior-auth-advance-notification.html",
      "lastVerified": "2026-06-01"
    }
  ],
  "acknowledgments": []
};
