// Per-utility metadata: inline citation (spec-v2 5.1), test-with-example
// values (spec-v2 5.3), and primary data source for the inline source stamp
// (spec-v2 5.2).
//
// The router renders these in a uniform block above each utility body, so
// the citation, example, and source stamp are present and styled the same
// way on every view without each renderer having to remember to add them.

export const META = {
  // ---- Group A: Code lookups (data source stamps only; no formula). ----
  icd10:           { source: { dataset: 'icd10cm', label: 'CMS / NCHS ICD-10-CM' } },
  hcpcs:           { source: { dataset: 'hcpcs', label: 'CMS HCPCS Level II' } },
  cpt:             { source: { dataset: 'mpfs',  label: 'CMS Medicare Physician Fee Schedule (structural rows; no AMA descriptors)' } },
  ndc:             { source: { dataset: 'ndc',   label: 'FDA National Drug Code Directory' } },
  'pos-codes':     { source: { dataset: 'crosswalks', label: 'CMS Place of Service codes' } },
  'modifier-codes':{ source: { dataset: 'crosswalks', label: 'CMS / X12 modifier codes' } },
  'revenue-codes': { source: { dataset: 'crosswalks', label: 'CMS UB-04 revenue codes' } },
  carc:            { source: { dataset: 'crosswalks', label: 'X12 Claim Adjustment Reason Codes' } },
  rarc:            { source: { dataset: 'crosswalks', label: 'X12 Remittance Advice Remark Codes' } },
  ncci:            { source: { dataset: 'ncci', label: 'CMS NCCI Procedure-to-Procedure edits' } },
  mue:             { source: { dataset: 'mue',  label: 'CMS Medically Unlikely Edits' } },
  lcd:             { source: { dataset: 'coverage', label: 'CMS Medicare Coverage Database (LCD/NCD)' } },

  // ---- Group B: Pricing ----
  mpfs:  { source: { dataset: 'mpfs',  label: 'CMS Medicare Physician Fee Schedule' },
           example: { fields: { 'mpfs-code': '99213', 'mpfs-loc': '0000099' }, expected: 'Allowable for 99213 in Rest of US' } },
  nadac: { source: { dataset: 'nadac', label: 'CMS NADAC weekly file' },
           example: { fields: { q: 'lisinopril', qty: '30' }, expected: 'NADAC per-unit pricing for lisinopril' } },
  ratio: { source: { dataset: 'mpfs', label: 'CMS Medicare Physician Fee Schedule' },
           example: { fields: { 'r-code': '99213', 'r-charge': '350', 'r-loc': '0000099' }, expected: 'Charge $350 vs Medicare ratio' } },
  'hospital-prices': { source: { dataset: 'hospital-prices', label: 'Bundled hospital machine-readable price files (curated subset)' } },
  oop:   { source: null,
           example: { fields: { allowed: '1000', deductible: '500', deductibleMet: '250', coinsurance: '20', copay: '0', oopMax: '5000', oopMet: '1000' }, expected: 'Patient responsibility: $400.00' } },

  // ---- Group C: Patient tools ----
  decoder:        { source: null },
  insurance:      { source: null },
  'eob-decoder':  { source: { dataset: 'crosswalks', label: 'X12 CARC and RARC code lists' } },
  'no-surprises': { source: { dataset: 'no-surprises', label: 'CMS / HHS No Surprises Act regulatory text' } },
  gfe:            { citation: 'Public Health Service Act Section 2799B-7 (No Surprises Act). Federal Patient-Provider Dispute Resolution threshold is $400 over the Good Faith Estimate.',
                    source: { dataset: 'no-surprises', label: 'CMS / HHS No Surprises Act regulatory text' },
                    example: { fields: { 'gfe-est': '1000', 'gfe-bill': '1500', 'gfe-status': 'uninsured' }, expected: 'Eligible: bill exceeds GFE by $500' } },
  'state-rights': { source: { dataset: 'state-rights', label: 'State AG publications and NCLC summaries (curated)' } },

  // ---- Group D: Provider lookup ----
  npi:       { source: { dataset: 'npi', label: 'CMS NPPES NPI registry (compact subset)' } },
  oig:       { source: { dataset: 'enforcement', label: 'HHS OIG List of Excluded Individuals/Entities' } },
  'opt-out': { source: { dataset: 'enforcement', label: 'CMS Medicare Opt-Out Affidavits' } },

  // ---- Group E: Clinical math (citations + examples) ----
  'unit-converter':    { citation: 'Standard SI and US customary unit definitions.',
                         example: { fields: { kind: 'weight', val: '70', from: 'kg', to: 'lb' }, expected: '70 kg = 154.32 lb' } },
  bmi:                 { citation: 'Quetelet 1835; Keys A, et al. Indices of relative weight and obesity. J Chronic Dis. 1972;25(6).',
                         example: { fields: { w: '70', h: '1.75' }, expected: 'BMI 22.9 (Normal)' } },
  bsa:                 { citation: 'Du Bois D, Du Bois EF. Arch Intern Med. 1916;17:863. Mosteller RD. N Engl J Med. 1987;317(17):1098.',
                         example: { fields: { w: '70', h: '175' }, expected: 'Du Bois ~1.85 m^2; Mosteller ~1.84 m^2' } },
  map:                 { citation: 'Standard physiology: MAP = ((2 * DBP) + SBP) / 3.',
                         example: { fields: { s: '120', d: '80' }, expected: 'MAP 93.3 mmHg' } },
  'anion-gap':         { citation: 'Emmett M, Narins RG. Clinical use of the anion gap. Medicine (Baltimore). 1977;56(1):38-54.',
                         example: { fields: { na: '140', cl: '100', hco3: '24', alb: '4' }, expected: 'AG 16; corrected AG 16' } },
  'corrected-calcium': { citation: 'Payne RB, et al. Interpretation of serum calcium in patients with abnormal serum proteins. BMJ. 1973;4(5893):643-646.',
                         example: { fields: { ca: '8.0', alb: '2.0' }, expected: 'Corrected Ca 9.6 mg/dL' } },
  'corrected-sodium':  { citation: 'Katz MA. NEJM. 1973. Hillier TA, Abbott RD, Barrett EJ. Am J Med. 1999;106(4):399-403.',
                         example: { fields: { na: '130', g: '600' }, expected: 'Corrected Na 138 (1.6); 142 (2.4)' } },
  'aa-gradient':       { citation: 'West JB. Respiratory Physiology: The Essentials. PAO2 = (FiO2 * (760-47)) - (PaCO2 / 0.8).',
                         example: { fields: { fio2: '0.21', paco2: '40', pao2: '90' }, expected: 'A-a gradient ~9.7 mmHg' } },
  egfr:                { citation: 'Inker LA, Eneanya ND, Coresh J, et al. New creatinine and cystatin C-based equations to estimate GFR without race. NEJM. 2021;385(19):1737-1749. Implements the 2021 race-free creatinine-only equation.',
                         example: { fields: { scr: '1.0', age: '60', sex: 'F' }, expected: 'eGFR ~60 mL/min/1.73m^2' } },
  'cockcroft-gault':   { citation: 'Cockcroft DW, Gault MH. Prediction of creatinine clearance from serum creatinine. Nephron. 1976;16(1):31-41.',
                         example: { fields: { age: '60', w: '80', scr: '1.0', sex: 'M' }, expected: 'CrCl 88.89 mL/min' } },
  'pack-years':        { citation: 'Standard tobacco-history measure: pack-years = packs per day x years smoked.',
                         example: { fields: { p: '1.5', y: '20' }, expected: 'Pack-years 30' } },
  'due-date':          { citation: 'Naegele rule: due date = LMP + 280 days.',
                         example: { fields: { lmp: '2025-01-01' }, expected: 'Due date 2025-10-08' } },
  qtc:                 { citation: 'Bazett 1920; Fridericia 1920; Sagie (Framingham) 1992; Hodges 1983. All four formulas reported side by side.',
                         example: { fields: { qt: '400', hr: '60' }, expected: 'All four formulas ~400 ms' } },
  'pf-ratio':          { citation: 'ARDS Definition Task Force. Berlin Definition. JAMA. 2012;307(23):2526-2533.',
                         example: { fields: { pao2: '90', fio2: '0.5' }, expected: 'P/F 180 (Moderate ARDS)' } },

  // ---- Group F: Medication math ----
  'drip-rate':         { citation: 'Standard infusion arithmetic: rate (mL/hr) = volume * 60 / duration; gtts/min = volume * drop factor / duration.',
                         example: { fields: { v: '1000', t: '480', df: '15' }, expected: '125 mL/hr; 31 gtts/min' } },
  'weight-dose':       { citation: 'Standard weight-based dose: total = weight * per-kg dose. Verify against your formulary.',
                         example: { fields: { w: '70', d: '5', u: 'mg/kg' }, expected: 'Total 350 mg' } },
  'conc-rate':         { citation: 'Standard infusion math: rate (mL/hr) = (dose per minute / concentration per mL) * 60. Bag presets per common institutional protocols.',
                         example: { fields: { dv: '0.1', du: 'mcg/kg/min', w: '70', cv: '0.064', cu: 'mg/mL' }, expected: 'Norepi at 0.1 mcg/kg/min, 70 kg, 64 mcg/mL: ~6.56 mL/hr' } },
  'peds-dose':         { citation: 'AAP, NLM/DailyMed, manufacturer labels. Reference table only.' },
  'insulin-drip':      { citation: 'Example protocols only. Use your institution\'s active insulin protocol.' },
  'anticoag-reversal': { citation: 'Standard reversal references; verify against your institution\'s protocol and current literature.' },
  'high-alert':        { citation: 'Identities are factual. ISMP maintains the authoritative list and formatting: https://www.ismp.org/' },

  // ---- Group G: Scoring ----
  gcs:         { citation: 'Teasdale G, Jennett B. Assessment of coma and impaired consciousness. Lancet. 1974;2(7872):81-84.',
                 example: { fields: { eye: '3', verbal: '4', motor: '5' }, expected: 'GCS 12' } },
  apgar:       { citation: 'Apgar V. A proposal for a new method of evaluation of the newborn infant. Curr Res Anesth Analg. 1953;32(4):260-267.',
                 example: { fields: { appearance: '2', pulse: '2', grimace: '2', activity: '2', respiration: '2' }, expected: 'APGAR 10' } },
  'peds-vitals': { source: { dataset: 'clinical', label: 'PALS reference values; AHA' } },
  'lab-ranges':  { source: { dataset: 'clinical', label: 'Common adult reference ranges; lab-specific ranges supersede.' } },
  abg:         { citation: 'Acid-base interpretation per standard physiology; Winter formula compensation; ARDS Berlin definition for P/F bands.',
                 example: { fields: { pH: '7.30', paco2: '30', hco3: '14' }, expected: 'Metabolic acidosis with appropriate respiratory compensation' } },
  'wells-pe':  { citation: 'Wells PS, et al. Derivation of a simple clinical model to categorize patients\' probability of pulmonary embolism. Thromb Haemost. 2000;83(3):416-420.' },
  'wells-dvt': { citation: 'Wells PS, et al. Value of assessment of pretest probability of deep-vein thrombosis. Lancet. 1997;350(9094):1795-1798.' },
  chads:       { citation: 'Lip GYH, et al. Refining clinical risk stratification for predicting stroke and thromboembolism in atrial fibrillation. Chest. 2010;137(2):263-272.' },
  hasbled:     { citation: 'Pisters R, et al. A novel user-friendly score (HAS-BLED). Chest. 2010;138(5):1093-1100.' },
  nihss:       { citation: 'Brott T, Adams HP Jr, et al. Measurements of acute cerebral infarction: a clinical examination scale. Stroke. 1989;20(7):864-870. Public-domain instrument maintained by NIH/NINDS.' },
  asa:         { source: { dataset: 'clinical', label: 'ASA Physical Status Classification; original short summaries by project author.' } },
  mallampati:  { citation: 'Mallampati SR, et al. A clinical sign to predict difficult tracheal intubation. Can Anaesth Soc J. 1985;32(4):429-434.' },
  beers:       { citation: 'AGS Beers Criteria. Drug-condition pairs are clinical facts; original brief notes by project author. AGS publishes the authoritative formatted list.' },

  // ---- Group H: Workflow ----
  prep:         { source: null },
  'prior-auth': { source: null },

  // ---- Group I: Field Medicine ----
  'peds-weight-dose': { citation: 'FDA labeling and standard prehospital pediatric resuscitation literature. Reference only.',
                        source: { dataset: 'prehospital-meds', label: 'FDA prehospital drug labeling subset' },
                        example: { fields: { 'pwd-w': '10', 'pwd-r': 'epinephrine-iv-io' }, expected: 'Epinephrine 0.1 mg IV/IO' } },
  'adult-arrest-ref': { citation: 'AHA ECC 2020 guidelines. Numeric reference only; flowcharts not reproduced.',
                        source: { dataset: 'aha-reference', label: 'AHA ECC numeric reference (no flowcharts)' } },
  'peds-arrest-ref':  { citation: 'AHA ECC 2020 guidelines. Numeric reference only; flowcharts not reproduced.',
                        source: { dataset: 'aha-reference', label: 'AHA ECC numeric reference (no flowcharts)' } },
  defib:              { citation: 'AHA ECC 2020 guidelines defibrillation energy ranges (numeric only).',
                        source: { dataset: 'aha-reference', label: 'AHA ECC numeric reference (no flowcharts)' },
                        example: { fields: { 'df-pop': 'adult', 'df-scn': 'vf-pvt', 'df-wave': 'biphasic', 'df-n': '1' }, expected: 'Adult biphasic VF/pVT: 120-200 J' } },
  cincinnati:         { citation: 'Kothari RU, Pancioli A, Liu T, Brott T, Broderick J. Cincinnati Prehospital Stroke Scale: reproducibility and validity. Acad Emerg Med. 1997;4(9):986-990.',
                        example: { fields: { 'cps-face': '1', 'cps-arm': '0', 'cps-speech': '0' }, expected: 'POSITIVE (1 of 3)' } },
  fast:               { citation: 'Kleindorfer DO, et al. Designing a message for public stroke education using the FAST mnemonic. Stroke. 2007;38(10):2864-2868. BE-FAST: Aroor S, Singh R, Goldstein LB. BE-FAST: reducing the proportion of strokes missed using the FAST mnemonic. Stroke. 2017;48(2):479-481.',
                        example: { fields: { 'fast-face': '1' }, expected: 'FAST: POSITIVE' } },

  'field-triage':     { citation: 'CDC. Guidelines for Field Triage of Injured Patients. MMWR Recommendations and Reports. Current edition.',
                        source: { dataset: 'field-triage', label: 'CDC Field Triage Guidelines' },
                        example: { fields: { 'ft-gcs-le-13': '1' }, expected: 'Highest-level trauma center (Step 1).' } },
  'start-triage':     { citation: 'Super G, et al. START: Simple Triage and Rapid Treatment. Newport Beach Fire Department / Hoag Hospital, 1983. Public-domain MCI triage protocol.',
                        source: { dataset: 'mci-triage', label: 'START / JumpSTART algorithm reference' },
                        example: { fields: { 'st-walk': '1' }, expected: 'Minor (green): patient can walk.' } },
  'jumpstart-triage': { citation: 'Romig LE. JumpSTART pediatric MCI triage tool. CHOC Children\'s Hospital. Public-domain pediatric variant of START.',
                        source: { dataset: 'mci-triage', label: 'START / JumpSTART algorithm reference' },
                        example: { fields: { 'js-walk': '1' }, expected: 'Minor (green): child can walk.' } },
  bsa_burn:           { citation: 'Lund CC, Browder NC. The estimation of areas of burns. Surg Gynecol Obstet. 1944;79:352-358. Rule of Nines: standard adult body-region distribution.',
                        example: { fields: { 'bb-method': 'nines', 'bb-n-trunk-anterior': '1' }, expected: 'TBSA 18% (anterior trunk only).' } },
  'burn-fluid':       { citation: 'Baxter CR, Shires T. Physiological response to crystalloid resuscitation of severe burns. Ann N Y Acad Sci. 1968;150(3):874-894 (Parkland). Reiss E, et al. Modified Brooke formula.',
                        example: { fields: { 'bf-w': '70', 'bf-bsa': '20', 'bf-h': '0' }, expected: 'Parkland 5600 mL/24h (2800 mL first 8h); Brooke 2800 mL/24h.' } },
  hypothermia:        { citation: 'Wilderness Medical Society guidelines and standard medical literature.',
                        source: { dataset: 'environmental', label: 'Environmental staging reference' } },
  'heat-illness':     { citation: 'Wilderness Medical Society guidelines and standard medical literature.',
                        source: { dataset: 'environmental', label: 'Environmental staging reference' } },
  'peds-ett':         { citation: 'Cuffed: age/4 + 3.5 mm. Uncuffed: age/4 + 4 mm. Depth at the lip = 3 x tube size in cm. Standard pediatric airway formulas; verify against bedside assessment.',
                        example: { fields: { 'pet-age': '4', 'pet-cuffed': 'uncuffed' }, expected: 'Tube 5.0 mm uncuffed, depth 15 cm.' } },
  toxidromes:         { citation: 'CDC ATSDR toxicological profiles and standard medical toxicology references; original brief notes by the project author.',
                        source: { dataset: 'toxidromes', label: 'ATSDR / CDC toxidrome reference' } },
  naloxone:           { citation: 'Naloxone HCl FDA labeling. CDC opioid overdose guidance. Repeat q2-3 min until adequate respirations.',
                        source: { dataset: 'prehospital-meds', label: 'FDA prehospital drug labeling subset' },
                        example: { fields: { 'nx-pop': 'adult', 'nx-route': 'in' }, expected: 'Initial: 4 mg intranasal (1 spray each nostril).' } },
  'ems-doc':          { citation: 'Templated workflow tool. Specific agency documentation requirements govern.' },
};
