// Per-utility metadata: inline citation (spec-v2 5.1), test-with-example
// values (spec-v2 5.3), and primary data source for the inline source stamp
// (spec-v2 5.2).
//
// The router renders these in a uniform block above each utility body, so
// the citation, example, and source stamp are present and styled the same
// way on every view without each renderer having to remember to add them.

export const META = {
  // ---- Group A: Code lookups (data source stamps only; no formula). ----
  icd10:           { source: { dataset: 'icd10cm', label: 'CMS / NCHS ICD-10-CM' } },
  hcpcs:           { source: { dataset: 'hcpcs', label: 'CMS HCPCS Level II' } },
  cpt:             { source: { dataset: 'mpfs',  label: 'CMS Medicare Physician Fee Schedule (structural rows; no AMA descriptors)' } },
  ndc:             { source: { dataset: 'ndc',   label: 'FDA National Drug Code Directory' } },
  'pos-codes':     { source: { dataset: 'crosswalks', label: 'CMS Place of Service codes' } },
  'modifier-codes':{ source: { dataset: 'crosswalks', label: 'CMS / X12 modifier codes' } },
  'revenue-codes': { source: { dataset: 'crosswalks', label: 'CMS UB-04 revenue codes' } },
  carc:            { source: { dataset: 'crosswalks', label: 'X12 Claim Adjustment Reason Codes' } },
  rarc:            { source: { dataset: 'crosswalks', label: 'X12 Remittance Advice Remark Codes' } },
  ncci:            { source: { dataset: 'ncci', label: 'CMS NCCI Procedure-to-Procedure edits' } },
  mue:             { source: { dataset: 'mue',  label: 'CMS Medically Unlikely Edits' } },
  lcd:             { source: { dataset: 'coverage', label: 'CMS Medicare Coverage Database (LCD/NCD)' } },

  // ---- Group A: v4 extensions (utilities 82-93) ----
  'hcpcs-mod':      { source: { dataset: 'hcpcs-modifiers', label: 'CMS HCPCS Level II Modifier file' } },
  'ncci-ptp':       { source: { dataset: 'ncci', label: 'CMS NCCI Procedure-to-Procedure edits' },
                      example: { fields: { codeA: '99213', codeB: '93000' }, expected: 'No PTP conflict in the bundled subset' } },
  'mue-cap':        { source: { dataset: 'mue', label: 'CMS Medically Unlikely Edits' } },
  'pos-lookup':     { source: { dataset: 'pos-codes', label: 'CMS Place of Service codes' } },
  'tob-decode':     { source: { dataset: 'tob-codes', label: 'NUBC Type of Bill structural digits (numeric only)' },
                      example: { fields: { q: '0111' }, expected: 'Hospital, Inpatient (Part A), Admit Through Discharge' } },
  'rev-table':      { source: { dataset: 'revenue-codes', label: 'NUBC Revenue Code summary (numeric only)' } },
  'nubc-codes':     { source: { dataset: 'nubc-special-codes', label: 'NUBC Condition / Occurrence / Value codes (numeric only)' } },
  'drg-lookup':     { source: { dataset: 'drg', label: 'CMS IPPS MS-DRG (Final Rule)' } },
  'apc-lookup':     { source: { dataset: 'apc', label: 'CMS OPPS APC Addendum' } },
  'pcs-lookup':     { source: { dataset: 'icd10-pcs', label: 'CMS ICD-10-PCS' } },
  'rxnorm-lookup':  { source: { dataset: 'rxnorm', label: 'NLM RxNorm' } },
  'ndc-rxnorm':     { source: { dataset: 'rxnorm', label: 'FDA NDC + NLM RxNorm crosswalk' } },

  // ---- Group B: Pricing ----
  mpfs:  { source: { dataset: 'mpfs',  label: 'CMS Medicare Physician Fee Schedule' },
           example: { fields: { 'mpfs-code': '99213', 'mpfs-loc': '0000099' }, expected: 'Allowable for 99213 in Rest of US' } },
  nadac: { source: { dataset: 'nadac', label: 'CMS NADAC weekly file' },
           example: { fields: { q: 'lisinopril', qty: '30' }, expected: 'NADAC per-unit pricing for lisinopril' } },
  ratio: { source: { dataset: 'mpfs', label: 'CMS Medicare Physician Fee Schedule' },
           example: { fields: { 'r-code': '99213', 'r-charge': '350', 'r-loc': '0000099' }, expected: 'Charge $350 vs Medicare ratio' } },
  'hospital-prices': { source: { dataset: 'hospital-prices', label: 'Bundled hospital machine-readable price files (curated subset)' } },
  oop:   { source: null,
           example: { fields: { allowed: '1000', deductible: '500', deductibleMet: '250', coinsurance: '20', copay: '0', oopMax: '5000', oopMet: '1000' }, expected: 'Patient responsibility: $400.00' } },

  // ---- Group B: v4 extensions (utilities 94-104) ----
  dmepos:                 { source: { dataset: 'dmepos', label: 'CMS DMEPOS Fee Schedule (subset)' },
                            example: { fields: { 'd-code': 'E0114' }, expected: 'Crutches non-CB rate $39.10; CA CB rate $36.50' } },
  clfs:                   { source: { dataset: 'clfs', label: 'CMS Clinical Laboratory Fee Schedule (subset)' } },
  asp:                    { source: { dataset: 'asp', label: 'CMS ASP quarterly file (subset)' },
                            example: { fields: { 'a-code': 'J1885' }, expected: 'Ketorolac per 15 mg, ASP $0.66' } },
  asc:                    { source: { dataset: 'asc', label: 'CMS ASC Addendum (subset)' } },
  'wage-index':           { source: { dataset: 'wage-index', label: 'CMS IPPS/OPPS Wage Index (subset)' } },
  gpci:                   { source: { dataset: 'gpci', label: 'CMS GPCI table' } },
  'medicare-deductibles': { source: { dataset: 'cms-deductibles', label: 'CMS annual notice; SSA IRMAA notice' },
                            example: { fields: {}, expected: 'Part B deductible and IRMAA brackets for the bundled CY' } },
  'aca-thresholds':       { source: { dataset: 'aca-thresholds', label: 'CMS / HHS Notice of Benefit and Payment Parameters' } },
  'hsa-fsa':              { source: { dataset: 'hsa-fsa-limits', label: 'IRS Revenue Procedure (HSA/FSA/HDHP)' },
                            example: { fields: {}, expected: 'HSA/FSA/HDHP limits for the bundled CY' } },
  fpl:                    { source: { dataset: 'fpl', label: 'HHS Poverty Guidelines' },
                            example: { fields: { 'fpl-h': '1', 'fpl-r': 'contiguous48' }, expected: '100% FPL for a 1-person household (contiguous 48)' } },
  'irs-mileage':          { source: { dataset: 'irs-mileage', label: 'IRS standard mileage rates' } },

  // ---- Group C: Patient tools ----
  decoder:        { source: null },
  insurance:      { source: null },
  'eob-decoder':  { source: { dataset: 'crosswalks', label: 'X12 CARC and RARC code lists' } },
  'no-surprises': { source: { dataset: 'no-surprises', label: 'CMS / HHS No Surprises Act regulatory text' } },
  gfe:            { citation: 'Public Health Service Act Section 2799B-7 (No Surprises Act). Federal Patient-Provider Dispute Resolution threshold is $400 over the Good Faith Estimate.',
                    source: { dataset: 'no-surprises', label: 'CMS / HHS No Surprises Act regulatory text' },
                    example: { fields: { 'gfe-est': '1000', 'gfe-bill': '1500', 'gfe-status': 'uninsured' }, expected: 'Eligible: bill exceeds GFE by $500' } },
  'state-rights': { source: { dataset: 'state-rights', label: 'State AG publications and NCLC summaries (curated)' } },

  // ---- Group C: v4 extensions (utilities 105-114) ----
  'insurance-card':      { source: null,
                           citation: 'Original plain-English explanations by the project author. No external lookup is performed.' },
  'abn-explainer':       { source: null,
                           citation: 'CMS Form CMS-R-131 (Advance Beneficiary Notice). Plain-English summaries by the project author; CMS publishes the authoritative form and instructions.' },
  'msn-decoder':         { citation: 'CMS Medicare Summary Notice format. Reference parsing only.' },
  'idr-eligibility':     { citation: 'No Surprises Act (Public Health Service Act Section 2799), 45 CFR 149. Federal IDR scope; does not displace state IDR processes.' },
  'appeal-letter':       { citation: 'Educational template. Plan-specific appeal procedures govern. Not legal advice.' },
  'hipaa-roa':           { citation: 'HIPAA Privacy Rule, 45 CFR 164.524. Right of Access; 30-day response requirement with one 30-day extension; cost-based fee cap.' },
  'birthday-rule':       { citation: 'Standard insurance industry rule for two-parent dependent coverage; some self-funded ERISA plans interpret differently. Reference only.' },
  'cobra-timeline':      { citation: 'Consolidated Omnibus Budget Reconciliation Act, 29 USC 1162: 18-month standard maximum; 29-month disability extension; 36 months for divorce, death, Medicare entitlement of covered employee.' },
  'medicare-enrollment': { citation: 'Medicare IEP (7 months around 65th birthday); GEP (Jan 1 - Mar 31 annually); Part B SEP for loss of employer coverage (8 months). Reference only.' },
  'aca-sep':             { citation: '45 CFR 155.420. SEP windows and qualifying life events under the ACA.' },

  // ---- Group D: Provider lookup ----
  npi:       { source: { dataset: 'npi', label: 'CMS NPPES NPI registry (compact subset)' } },
  oig:       { source: { dataset: 'enforcement', label: 'HHS OIG List of Excluded Individuals/Entities' } },
  'opt-out': { source: { dataset: 'enforcement', label: 'CMS Medicare Opt-Out Affidavits' } },

  // ---- Group D: v4 extensions (utilities 115-116) ----
  'dea-validator':  { source: { dataset: 'dea-rules', label: 'DEA registration checksum rule (DEA Diversion Control)' },
                      citation: 'DEA registration numbers: 2 letters + 7 digits. Checksum: (d1+d3+d5) + 2*(d2+d4+d6) mod 10 = d7.',
                      example: { fields: { 'dea-q': 'AB1234563' }, expected: 'Valid checksum (1+3+5)+2*(2+4+6)=9+24=33 mod 10 = 3' } },
  'nucc-taxonomy':  { source: { dataset: 'nucc-taxonomy', label: 'NUCC Health Care Provider Taxonomy' } },

  // ---- Group E: Clinical math (citations + examples) ----
  'unit-converter':    { citation: 'Standard SI and US customary unit definitions.',
                         example: { fields: { kind: 'weight', val: '70', from: 'kg', to: 'lb' }, expected: '70 kg = 154.32 lb' } },
  bmi:                 { citation: 'Quetelet 1835; Keys A, et al. Indices of relative weight and obesity. J Chronic Dis. 1972;25(6).',
                         example: { fields: { w: '70', h: '1.75' }, expected: 'BMI 22.9 (Normal)' } },
  bsa:                 { citation: 'Du Bois D, Du Bois EF. Arch Intern Med. 1916;17:863. Mosteller RD. N Engl J Med. 1987;317(17):1098.',
                         example: { fields: { w: '70', h: '175' }, expected: 'Du Bois ~1.85 m^2; Mosteller ~1.84 m^2' } },
  map:                 { citation: 'Standard physiology: MAP = ((2 * DBP) + SBP) / 3.',
                         example: { fields: { s: '120', d: '80' }, expected: 'MAP 93.3 mmHg' } },
  'anion-gap':         { citation: 'Emmett M, Narins RG. Clinical use of the anion gap. Medicine (Baltimore). 1977;56(1):38-54.',
                         example: { fields: { na: '140', cl: '100', hco3: '24', alb: '4' }, expected: 'AG 16; corrected AG 16' } },
  'corrected-calcium': { citation: 'Payne RB, et al. Interpretation of serum calcium in patients with abnormal serum proteins. BMJ. 1973;4(5893):643-646.',
                         example: { fields: { ca: '8.0', alb: '2.0' }, expected: 'Corrected Ca 9.6 mg/dL' } },
  'corrected-sodium':  { citation: 'Katz MA. NEJM. 1973. Hillier TA, Abbott RD, Barrett EJ. Am J Med. 1999;106(4):399-403.',
                         example: { fields: { na: '130', g: '600' }, expected: 'Corrected Na 138 (1.6); 142 (2.4)' } },
  'aa-gradient':       { citation: 'West JB. Respiratory Physiology: The Essentials. PAO2 = (FiO2 * (760-47)) - (PaCO2 / 0.8).',
                         example: { fields: { fio2: '0.21', paco2: '40', pao2: '90' }, expected: 'A-a gradient ~9.7 mmHg' } },
  egfr:                { citation: 'Inker LA, Eneanya ND, Coresh J, et al. New creatinine and cystatin C-based equations to estimate GFR without race. NEJM. 2021;385(19):1737-1749. Implements the 2021 race-free creatinine-only equation.',
                         example: { fields: { scr: '1.0', age: '60', sex: 'F' }, expected: 'eGFR ~60 mL/min/1.73m^2' } },
  'cockcroft-gault':   { citation: 'Cockcroft DW, Gault MH. Prediction of creatinine clearance from serum creatinine. Nephron. 1976;16(1):31-41.',
                         example: { fields: { age: '60', w: '80', scr: '1.0', sex: 'M' }, expected: 'CrCl 88.89 mL/min' } },
  'pack-years':        { citation: 'Standard tobacco-history measure: pack-years = packs per day x years smoked.',
                         example: { fields: { p: '1.5', y: '20' }, expected: 'Pack-years 30' } },
  'due-date':          { citation: 'Naegele rule: due date = LMP + 280 days.',
                         example: { fields: { lmp: '2025-01-01' }, expected: 'Due date 2025-10-08' } },
  qtc:                 { citation: 'Bazett 1920; Fridericia 1920; Sagie (Framingham) 1992; Hodges 1983. All four formulas reported side by side.',
                         example: { fields: { qt: '400', hr: '60' }, expected: 'All four formulas ~400 ms' } },
  'pf-ratio':          { citation: 'ARDS Definition Task Force. Berlin Definition. JAMA. 2012;307(23):2526-2533.',
                         example: { fields: { pao2: '90', fio2: '0.5' }, expected: 'P/F 180 (Moderate ARDS)' } },

  // ---- Group E: v4 extensions (utilities 117-128) ----
  'anion-gap-dd':    { citation: 'Standard chemistry references; Wrenn KD. The delta gap. Ann Emerg Med. 1990;19(11):1310-1313.',
                       example: { fields: { na: '140', cl: '100', hco3: '14', alb: '4' }, expected: 'AG 26; delta-AG 14; delta-HCO3 10; ratio 1.4 - pure AG metabolic acidosis' } },
  'corrected-ca-na': { citation: 'Payne RB BMJ 1973 (Ca); Katz NEJM 1973 / Hillier Am J Med 1999 (Na).' },
  'osmolal-gap':     { citation: 'Calculated osm = 2*Na + glucose/18 + BUN/2.8 (+ EtOH/4.6). Gap >10 raises suspicion of toxic alcohols.' },
  'aa-pf-suite':     { citation: 'West JB. Respiratory Physiology. ARDS Berlin Definition: JAMA 2012;307(23):2526.' },
  winters:           { citation: "Winter et al. The fall of serum bicarbonate in metabolic acidosis. Arch Intern Med 1967;120(2):151-156.",
                       example: { fields: { 'wf-hco3': '14', 'wf-paco2': '29' }, expected: "Expected PaCO2 27-31; appropriate respiratory compensation" } },
  'shock-index':     { citation: 'Allgower & Burri 1967 (shock index). Standard physiology for MAP and PP.' },
  'bw-bsa-suite':    { citation: 'Devine 1974 (IBW); 0.4 AdjBW rule; Mosteller NEJM 1987; Du Bois 1916.' },
  'egfr-suite':      { citation: 'Inker LA et al. NEJM 2021 (CKD-EPI race-free); Levey AS et al. Ann Intern Med 1999 (MDRD); Cockcroft-Gault Nephron 1976.',
                       example: { fields: { 'es-scr': '1.0', 'es-age': '60', 'es-w': '70', 'es-sex': 'M' }, expected: 'CKD-EPI 2021 ~89; MDRD ~77; Cockcroft-Gault ~78 mL/min' } },
  'fena-feurea':     { citation: 'Espinel CH JAMA 1976 (FENa); Carvounis CP Kidney Int 2002 (FEUrea).' },
  'maint-fluids':    { citation: 'Holliday MA, Segar WE. Pediatrics 1957. 4-2-1 maintenance rule.',
                       example: { fields: { 'mf-w': '70' }, expected: 'Maintenance: 110 mL/hr (40 + 20 + 50)' } },
  'qtc-suite':       { citation: 'Bazett 1920; Fridericia 1920; Sagie (Framingham) 1992; Hodges 1983.',
                       example: { fields: { 'qs-qt': '400', 'qs-hr': '60' }, expected: 'All four formulas ~400 ms' } },
  'preg-dating':     { citation: 'Naegele rule (LMP+280); Robinson-Fleming CRL formula; ACOG Practice Bulletin redating thresholds (T1: 7d; T2: 14d; T3: 21d).' },

  // ---- Group F: Medication math ----
  'drip-rate':         { citation: 'Standard infusion arithmetic: rate (mL/hr) = volume * 60 / duration; gtts/min = volume * drop factor / duration.',
                         example: { fields: { v: '1000', t: '480', df: '15' }, expected: '125 mL/hr; 31 gtts/min' } },
  'weight-dose':       { citation: 'Standard weight-based dose: total = weight * per-kg dose. Verify against your formulary.',
                         example: { fields: { w: '70', d: '5', u: 'mg/kg' }, expected: 'Total 350 mg' } },
  'conc-rate':         { citation: 'Standard infusion math: rate (mL/hr) = (dose per minute / concentration per mL) * 60. Bag presets per common institutional protocols.',
                         example: { fields: { dv: '0.1', du: 'mcg/kg/min', w: '70', cv: '0.064', cu: 'mg/mL' }, expected: 'Norepi at 0.1 mcg/kg/min, 70 kg, 64 mcg/mL: ~6.56 mL/hr' } },
  'peds-dose':         { citation: 'AAP, NLM/DailyMed, manufacturer labels. Reference table only.' },
  'insulin-drip':      { citation: 'Example protocols only. Use your institution\'s active insulin protocol.' },
  'anticoag-reversal': { citation: 'Standard reversal references; verify against your institution\'s protocol and current literature.' },
  'high-alert':        { citation: 'Identities are factual. ISMP maintains the authoritative list and formatting: https://www.ismp.org/' },

  // ---- Group F: v4 extensions (utilities 129-135) ----
  'opioid-mme':     { source: { dataset: 'mme-factors', label: 'CDC 2022 Opioid MME conversion factors' },
                      citation: 'CDC Clinical Practice Guideline for Prescribing Opioids - United States, 2022. MMWR Recomm Rep. 2022;71(3):1-95.',
                      example: { fields: {}, expected: 'Morphine 30 mg q4h = 180 MME (above the 90 MME CDC threshold)' } },
  'steroid-equiv':  { source: { dataset: 'steroid-equiv', label: 'Standard pharmacology references (project-author table)' },
                      example: { fields: { 'st-dose': '5' }, expected: 'Prednisone 5 mg = methylpred 4 mg (default selectors)' } },
  'benzo-equiv':    { source: { dataset: 'benzo-equiv', label: 'Ashton benzodiazepine equivalence table (public)' },
                      citation: 'Ashton CH. Benzodiazepines: How They Work and How to Withdraw. https://www.benzo.org.uk/manual/' },
  'abx-renal':      { source: { dataset: 'abx-renal', label: 'FDA labels via DailyMed (subset)' },
                      example: { fields: { 'abx-crcl': '70' }, expected: 'Cefepime 1-2 g q8-12h at default selector' } },
  vasopressor:      { source: { dataset: 'vasopressor-doses', label: 'FDA vasopressor labels (subset)' },
                      citation: 'Standard infusion math: rate (mL/hr) = (dose per min / concentration per mL) * 60.' },
  'tpn-macro':      { source: { dataset: 'tpn-rules', label: 'Standard nutrition references' },
                      citation: 'Dextrose 3.4 kcal/g; protein 4 kcal/g; lipid (20% emulsion) 2 kcal/mL.',
                      example: { fields: { 'tpn-vol': '1500', 'tpn-d': '20', 'tpn-aa': '5', 'tpn-lipid': '10' }, expected: '1620 kcal: 300 g dextrose / 75 g protein / 30 g lipid' } },
  'iv-to-po':       { source: { dataset: 'iv-to-po', label: 'FDA labels (subset)' },
                      citation: 'Bioavailability values per FDA labeling. Verify against current institutional formulary.' },

  // ---- Group G: Scoring ----
  gcs:         { citation: 'Teasdale G, Jennett B. Assessment of coma and impaired consciousness. Lancet. 1974;2(7872):81-84.',
                 example: { fields: { eye: '3', verbal: '4', motor: '5' }, expected: 'GCS 12' } },
  apgar:       { citation: 'Apgar V. A proposal for a new method of evaluation of the newborn infant. Curr Res Anesth Analg. 1953;32(4):260-267.',
                 example: { fields: { appearance: '2', pulse: '2', grimace: '2', activity: '2', respiration: '2' }, expected: 'APGAR 10' } },
  'peds-vitals': { source: { dataset: 'clinical', label: 'PALS reference values; AHA' } },
  'lab-ranges':  { source: { dataset: 'clinical', label: 'Common adult reference ranges; lab-specific ranges supersede.' } },
  abg:         { citation: 'Acid-base interpretation per standard physiology; Winter formula compensation; ARDS Berlin definition for P/F bands.',
                 example: { fields: { pH: '7.30', paco2: '30', hco3: '14' }, expected: 'Metabolic acidosis with appropriate respiratory compensation' } },
  'wells-pe':  { citation: 'Wells PS, et al. Derivation of a simple clinical model to categorize patients\' probability of pulmonary embolism. Thromb Haemost. 2000;83(3):416-420.' },
  'wells-dvt': { citation: 'Wells PS, et al. Value of assessment of pretest probability of deep-vein thrombosis. Lancet. 1997;350(9094):1795-1798.' },
  chads:       { citation: 'Lip GYH, et al. Refining clinical risk stratification for predicting stroke and thromboembolism in atrial fibrillation. Chest. 2010;137(2):263-272.' },
  hasbled:     { citation: 'Pisters R, et al. A novel user-friendly score (HAS-BLED). Chest. 2010;138(5):1093-1100.' },
  nihss:       { citation: 'Brott T, Adams HP Jr, et al. Measurements of acute cerebral infarction: a clinical examination scale. Stroke. 1989;20(7):864-870. Public-domain instrument maintained by NIH/NINDS.' },
  asa:         { source: { dataset: 'clinical', label: 'ASA Physical Status Classification; original short summaries by project author.' } },
  mallampati:  { citation: 'Mallampati SR, et al. A clinical sign to predict difficult tracheal intubation. Can Anaesth Soc J. 1985;32(4):429-434.' },
  beers:       { citation: 'AGS Beers Criteria. Drug-condition pairs are clinical facts; original brief notes by project author. AGS publishes the authoritative formatted list.' },

  // ---- Group G: v4 extensions waves 1-2 (utilities 136-145) ----
  timi:             { citation: 'Antman EM, et al. The TIMI Risk Score for Unstable Angina/Non-ST Elevation MI. JAMA. 2000;284(7):835-842.' },
  grace:            { citation: 'Granger CB, et al. GRACE Project. Arch Intern Med. 2003;163(19):2345-2353. Simplified-points implementation.' },
  heart:            { citation: 'Six AJ, Backus BE, Kelder JC. HEART score. Neth Heart J. 2008;16(6):191-196.' },
  perc:             { citation: 'Kline JA, et al. PERC rule. J Thromb Haemost. 2004;2(8):1247-1255. Use only if clinical pretest probability is low.' },
  'wells-pe-geneva':{ citation: 'Wells PS, et al. Thromb Haemost. 2000;83(3):416-420 (Wells PE). Le Gal G, et al. Ann Intern Med. 2006;144(3):165-171 (revised Geneva).' },
  'curb-65':        { citation: 'Lim WS, et al. Defining community acquired pneumonia severity. Thorax. 2003;58(5):377-382.' },
  psi:              { citation: 'Fine MJ, et al. Pneumonia Severity Index. NEJM. 1997;336(4):243-250. Reference points-only implementation; class V advisory.' },
  'qsofa-sofa':     { citation: 'Singer M, et al. Sepsis-3 (qSOFA). JAMA. 2016;315(8):801-810. Vincent JL, et al. SOFA. Intensive Care Med. 1996;22(7):707-710.' },
  'meld-childpugh': { citation: 'Kim WR, et al. MELD-3.0. Gastroenterology. 2021;161(6):1887-1895. Pugh RN, et al. Br J Surg. 1973;60(8):646-649 (Child-Pugh).' },
  'ranson-bisap':   { citation: 'Ranson JH, et al. Surg Gynecol Obstet. 1974;139(1):69-81. Wu BU, et al. BISAP. Gut. 2008;57(12):1698-1703.' },

  // ---- Group G: v4 extensions waves 3-4 (utilities 146-156) ----
  centor:               { citation: 'Centor RM, et al. Med Decis Making. 1981;1(3):239-246. McIsaac WJ, et al. CMAJ. 1998;158(1):75-83.' },
  'wells-dvt-caprini':  { citation: 'Wells PS, et al. Lancet. 1997;350(9094):1795-1798 (Wells DVT). Caprini JA. Dis Mon. 2005;51(2-3):70-78.' },
  bishop:               { citation: 'Bishop EH. Pelvic scoring for elective induction. Obstet Gynecol. 1964;24:266-268.' },
  'alvarado-pas':       { citation: 'Alvarado A. Ann Emerg Med. 1986;15(5):557-564 (MANTRELS). Samuel M. J Pediatr Surg. 2002;37(6):877-881 (PAS).' },
  mrs:                  { citation: 'Modified Rankin Scale; UK-TIA Study Group 1988. Reference instrument; not auto-computed.' },
  phq9:                 { citation: 'Kroenke K, Spitzer RL, Williams JBW. PHQ-9. J Gen Intern Med. 2001;16(9):606-613.' },
  gad7:                 { citation: 'Spitzer RL, et al. GAD-7. Arch Intern Med. 2006;166(10):1092-1097.' },
  auditc:               { citation: 'Bush K, et al. AUDIT-C. Arch Intern Med. 1998;158(16):1789-1795.' },
  cage:                 { citation: 'Ewing JA. CAGE Questionnaire. JAMA. 1984;252(14):1905-1907.' },
  epds:                 { citation: 'Cox JL, Holden JM, Sagovsky R. EPDS. Br J Psychiatry. 1987;150:782-786.' },
  'mini-cog':           { citation: 'Borson S, et al. Mini-Cog. Int J Geriatr Psychiatry. 2000;15(11):1021-1027.' },

  // ---- Group G: v4 extensions waves 5-6 (utilities 157-160) ----
  ciwa:    { citation: 'Sullivan JT, et al. Assessment of alcohol withdrawal: the revised CIWA-Ar. Br J Addict. 1989;84(11):1353-1357.' },
  cows:    { citation: 'Wesson DR, Ling W. The Clinical Opiate Withdrawal Scale (COWS). J Psychoactive Drugs. 2003;35(2):253-259.' },
  ascvd:   { citation: 'Goff DC Jr, et al. 2013 ACC/AHA Guideline on the Assessment of Cardiovascular Risk: Pooled Cohort Equations. Circulation. 2014;129(25 Suppl 2):S49-73. PCE retains race-stratified equations (white vs African-American).' },
  prevent: { citation: 'Khan SS, et al. Development and Validation of the AHA PREVENT Equations. Circulation. 2024;149(6):430-449. PREVENT is race-FREE; differs from PCE on this point. Base 10-yr total CVD equation only (no statin / antihypertensive use, UACR, HbA1c, or SDI terms).' },

  // ---- Group H: Workflow ----
  prep:         { source: null },
  'prior-auth': { source: null },

  // ---- Group H: v4 extensions (utilities 161-165) ----
  'hipaa-auth':      { citation: 'HIPAA Privacy Rule, 45 CFR 164.508. Required-element template; covered entities may add their own elements.' },
  roi:               { citation: 'Patient-authorized release of records. Many providers require their own ROI form; this template can be attached or used as the basis.' },
  'discharge-instr': { citation: 'Reference template only. Institutional discharge protocols and condition-specific guidelines govern the required content.' },
  'specialty-visit': { citation: 'Generic per-specialty question banks compiled by the project author. Tailor to the visit.' },
  'wallet-card':     { citation: 'Patient-maintained medication / health summary. Not a substitute for a pharmacist-reviewed list.' },

  // ---- Group I: Field Medicine ----
  'peds-weight-dose': { citation: 'FDA labeling and standard prehospital pediatric resuscitation literature. Reference only.',
                        source: { dataset: 'prehospital-meds', label: 'FDA prehospital drug labeling subset' },
                        example: { fields: { 'pwd-w': '10', 'pwd-r': 'epinephrine-iv-io' }, expected: 'Epinephrine 0.1 mg IV/IO' } },
  'adult-arrest-ref': { citation: 'AHA ECC 2020 guidelines. Numeric reference only; flowcharts not reproduced.',
                        source: { dataset: 'aha-reference', label: 'AHA ECC numeric reference (no flowcharts)' } },
  'peds-arrest-ref':  { citation: 'AHA ECC 2020 guidelines. Numeric reference only; flowcharts not reproduced.',
                        source: { dataset: 'aha-reference', label: 'AHA ECC numeric reference (no flowcharts)' } },
  defib:              { citation: 'AHA ECC 2020 guidelines defibrillation energy ranges (numeric only).',
                        source: { dataset: 'aha-reference', label: 'AHA ECC numeric reference (no flowcharts)' },
                        example: { fields: { 'df-pop': 'adult', 'df-scn': 'vf-pvt', 'df-wave': 'biphasic', 'df-n': '1' }, expected: 'Adult biphasic VF/pVT: 120-200 J' } },
  cincinnati:         { citation: 'Kothari RU, Pancioli A, Liu T, Brott T, Broderick J. Cincinnati Prehospital Stroke Scale: reproducibility and validity. Acad Emerg Med. 1997;4(9):986-990.',
                        example: { fields: { 'cps-face': '1', 'cps-arm': '0', 'cps-speech': '0' }, expected: 'POSITIVE (1 of 3)' } },
  fast:               { citation: 'Kleindorfer DO, et al. Designing a message for public stroke education using the FAST mnemonic. Stroke. 2007;38(10):2864-2868. BE-FAST: Aroor S, Singh R, Goldstein LB. BE-FAST: reducing the proportion of strokes missed using the FAST mnemonic. Stroke. 2017;48(2):479-481.',
                        example: { fields: { 'fast-face': '1' }, expected: 'FAST: POSITIVE' } },

  'field-triage':     { citation: 'CDC. Guidelines for Field Triage of Injured Patients. MMWR Recommendations and Reports. Current edition.',
                        source: { dataset: 'field-triage', label: 'CDC Field Triage Guidelines' },
                        example: { fields: { 'ft-gcs-le-13': '1' }, expected: 'Highest-level trauma center (Step 1).' } },
  'start-triage':     { citation: 'Super G, et al. START: Simple Triage and Rapid Treatment. Newport Beach Fire Department / Hoag Hospital, 1983. Public-domain MCI triage protocol.',
                        source: { dataset: 'mci-triage', label: 'START / JumpSTART algorithm reference' },
                        example: { fields: { 'st-walk': '1' }, expected: 'Minor (green): patient can walk.' } },
  'jumpstart-triage': { citation: 'Romig LE. JumpSTART pediatric MCI triage tool. CHOC Children\'s Hospital. Public-domain pediatric variant of START.',
                        source: { dataset: 'mci-triage', label: 'START / JumpSTART algorithm reference' },
                        example: { fields: { 'js-walk': '1' }, expected: 'Minor (green): child can walk.' } },
  bsa_burn:           { citation: 'Lund CC, Browder NC. The estimation of areas of burns. Surg Gynecol Obstet. 1944;79:352-358. Rule of Nines: standard adult body-region distribution.',
                        example: { fields: { 'bb-method': 'nines', 'bb-n-trunk-anterior': '1' }, expected: 'TBSA 18% (anterior trunk only).' } },
  'burn-fluid':       { citation: 'Baxter CR, Shires T. Physiological response to crystalloid resuscitation of severe burns. Ann N Y Acad Sci. 1968;150(3):874-894 (Parkland). Reiss E, et al. Modified Brooke formula.',
                        example: { fields: { 'bf-w': '70', 'bf-bsa': '20', 'bf-h': '0' }, expected: 'Parkland 5600 mL/24h (2800 mL first 8h); Brooke 2800 mL/24h.' } },
  hypothermia:        { citation: 'Wilderness Medical Society guidelines and standard medical literature.',
                        source: { dataset: 'environmental', label: 'Environmental staging reference' } },
  'heat-illness':     { citation: 'Wilderness Medical Society guidelines and standard medical literature.',
                        source: { dataset: 'environmental', label: 'Environmental staging reference' } },
  'peds-ett':         { citation: 'Cuffed: age/4 + 3.5 mm. Uncuffed: age/4 + 4 mm. Depth at the lip = 3 x tube size in cm. Standard pediatric airway formulas; verify against bedside assessment.',
                        example: { fields: { 'pet-age': '4', 'pet-cuffed': 'uncuffed' }, expected: 'Tube 5.0 mm uncuffed, depth 15 cm.' } },
  toxidromes:         { citation: 'CDC ATSDR toxicological profiles and standard medical toxicology references; original brief notes by the project author.',
                        source: { dataset: 'toxidromes', label: 'ATSDR / CDC toxidrome reference' } },
  naloxone:           { citation: 'Naloxone HCl FDA labeling. CDC opioid overdose guidance. Repeat q2-3 min until adequate respirations.',
                        source: { dataset: 'prehospital-meds', label: 'FDA prehospital drug labeling subset' },
                        example: { fields: { 'nx-pop': 'adult', 'nx-route': 'in' }, expected: 'Initial: 4 mg intranasal (1 spray each nostril).' } },
  'ems-doc':          { citation: 'Templated workflow tool. Specific agency documentation requirements govern.' },

  // ---- Group I: v4 extensions (utilities 166-171) ----
  'nexus-cspine':   { citation: 'Hoffman JR, et al. NEXUS criteria. NEJM. 2000;343(2):94-99. Stiell IG, et al. Canadian C-Spine Rule. JAMA. 2001;286(15):1841-1848.' },
  'dot-erg':        { source: { dataset: 'dot-erg', label: 'PHMSA Emergency Response Guidebook' } },
  'niosh-pg':       { source: { dataset: 'niosh-pg', label: 'CDC NIOSH Pocket Guide' } },
  'cpr-numeric':    { source: { dataset: 'cpr-aha-numeric', label: 'AHA CPR/ECC numeric reference (numeric facts only)' },
                      citation: 'AHA CPR/ECC guidelines, current edition. Numeric values only; flowcharts not reproduced.' },
  tccc:             { source: { dataset: 'tccc', label: 'CoTCCC public guidelines' },
                      citation: 'Committee on Tactical Combat Casualty Care, public guidelines.' },
  'co-cn-antidote': { citation: 'FDA labeling: Cyanokit (hydroxocobalamin) and Nithiodote (sodium nitrite + sodium thiosulfate). UHMS guidance for HBO indications.' },

  // ---- Group J (NEW): Public Health & Travel (utilities 172-180) ----
  'acip-adult':     { source: { dataset: 'acip-routine-adult', label: 'CDC ACIP routine adult immunization schedule' } },
  'acip-child':     { source: { dataset: 'acip-routine-child', label: 'CDC ACIP routine child immunization schedule' } },
  'acip-catchup':   { source: { dataset: 'acip-catchup', label: 'CDC ACIP catch-up immunization schedule' } },
  'yellow-book':    { source: { dataset: 'yellow-book', label: 'CDC Yellow Book by-country reference' } },
  tetanus:          { source: { dataset: 'tetanus', label: 'CDC tetanus prophylaxis decision aid' },
                      citation: 'CDC tetanus prophylaxis recommendations (current edition).' },
  'rabies-pep':     { source: { dataset: 'rabies-pep', label: 'CDC rabies post-exposure prophylaxis decision aid' },
                      citation: 'CDC ACIP rabies PEP recommendations (current edition).' },
  'bbp-exposure':   { source: { dataset: 'bbp-exposure', label: 'CDC HIV/HBV/HCV bloodborne pathogen exposure recommendations' },
                      citation: 'CDC USPHS guidance for occupational and non-occupational HIV PEP; HBV/HCV exposure management.' },
  'tb-testing':     { source: { dataset: 'tb-tst-igra', label: 'CDC TB testing interpretation' },
                      citation: 'CDC TST cutoffs (5 / 10 / 15 mm) by risk category; IGRA interpretation.' },
  'sti-screening':  { source: { dataset: 'sti-screening', label: 'CDC STI Screening Recommendations' } },

  // ---- Group K (NEW): Lab Reference (utilities 181-184) ----
  'lab-adult':      { source: { dataset: 'lab-ranges-adult', label: 'NIH MedlinePlus adult lab reference ranges' },
                      citation: 'Reference ranges vary by lab; lab-specific ranges supersede.' },
  'lab-peds':       { source: { dataset: 'lab-ranges-peds', label: 'Pediatric lab reference ranges by age band' } },
  'tdm-levels':     { source: { dataset: 'therapeutic-drug-levels', label: 'FDA labels via DailyMed - therapeutic drug levels' } },
  'tox-levels':     { source: { dataset: 'tox-levels', label: 'NLM WISER toxicology level reference' },
                      citation: 'Levels are stated as "associated with clinical toxicity per published references" - not treatment recommendations.' },

  // ---- Group L (NEW): Forms & Numbers Literacy (utilities 185-187) ----
  cms1500:          { source: { dataset: 'cms-1500-fields', label: 'CMS-1500 form (project-original plain-English summaries)' } },
  ub04:             { source: { dataset: 'ub04-fields', label: 'UB-04 form (project-original plain-English summaries)' } },
  'eob-glossary':   { source: { dataset: 'eob-glossary', label: 'Project-original EOB jargon glossary' } },

  // ---- Group M (NEW): Eligibility & Benefits (utilities 188-191) ----
  'medicaid-state': { source: { dataset: 'medicaid-state', label: 'State Medicaid agency files (numeric thresholds only)' } },
  'va-eligibility': { source: { dataset: 'va-eligibility', label: 'VA eligibility quick categories' } },
  'tricare-picker': { source: { dataset: 'tricare-plans', label: 'TRICARE plan rules' } },
  'ihs-eligibility':{ source: { dataset: 'ihs-eligibility', label: 'IHS eligibility quick reference' } },

  // ---- Group N (NEW): Literacy Helpers (utilities 192-194) ----
  'unit-converter-v4': { citation: 'Standard SI <-> conventional conversion factors. NIH/NLM and IFCC references for HbA1c.',
                         example: { fields: { 'uc-cat': 'glucose', 'uc-v1': '90' }, expected: '90 mg/dL = 5.0 mmol/L' } },
  'time-to-dose':      { citation: 'Plain time math. Frequency abbreviations per standard pharmacy nomenclature.' },
  'peds-weight-conv':  { citation: '1 lb = 0.453592 kg. Reference newborn / infant weight bands per AAP.' },

  // ---- Group O (NEW): Patient Safety (utilities 195-197) ----
  'high-alert-card':   { citation: 'Identities are factual. ISMP maintains the authoritative formatted list at https://www.ismp.org/.' },
  'drug-recalls':      { source: { dataset: 'drug-recalls', label: 'FDA drug recalls (weekly snapshot)' },
                         citation: 'Snapshot of api.fda.gov/drug/enforcement.json. Up to one week behind upstream.' },
  'vaccine-recalls':   { source: { dataset: 'vaccine-lot-recalls', label: 'FDA / CDC vaccine lot recalls' } },
};
