// Per-utility metadata: inline citation (spec-v2 5.1), test-with-example
// values (spec-v2 5.3), and primary data source for the inline source stamp
// (spec-v2 5.2).
//
// The router renders these in a uniform block above each utility body, so
// the citation, example, and source stamp are present and styled the same
// way on every view without each renderer having to remember to add them.

export const META = {
  // ---- Group A: Code lookups (data source stamps only; no formula). ----
  icd10:           { source: { dataset: 'icd10cm', label: 'CMS / NCHS ICD-10-CM' },
                     citation: 'ICD-10-CM Tabular List of Diseases and Injuries; CMS / NCHS public-domain release. Annual fiscal-year update (October).',
                     example: { fields: { q: 'I10' }, expected: 'I10 - Essential (primary) hypertension.' } },
  hcpcs:           { source: { dataset: 'hcpcs', label: 'CMS HCPCS Level II' },
                     citation: 'HCPCS Level II Code Set; CMS public-domain release. Quarterly maintenance.',
                     example: { fields: { q: 'J3490' }, expected: 'J3490 - Unclassified drugs.' } },
  cpt:             { source: { dataset: 'mpfs',  label: 'CMS Medicare Physician Fee Schedule (structural rows; no AMA descriptors)' },
                     citation: 'CPT descriptors are owned by the American Medical Association and are not bundled. Structural rows shown are from the CMS Medicare Physician Fee Schedule (PFS) public file.',
                     example: { fields: { q: '99213' }, expected: '99213 - structural PFS row; descriptor available via the AMA free public CPT lookup.' } },
  ndc:             { source: { dataset: 'ndc',   label: 'FDA National Drug Code Directory' },
                     citation: 'FDA National Drug Code Directory; FDA public-domain release. Updated daily upstream.',
                     example: { fields: { q: 'aspirin' }, expected: 'List of aspirin-containing NDCs from the bundled subset.' } },
  'pos-codes':     { source: { dataset: 'crosswalks', label: 'CMS Place of Service codes' },
                     citation: 'CMS Place of Service Code Set for Professional Claims (HIPAA-mandated, 45 CFR 162.1002).',
                     example: { fields: { q: '11' }, expected: '11 - Office.' } },
  'modifier-codes':{ source: { dataset: 'crosswalks', label: 'CMS / X12 modifier codes' },
                     citation: 'CMS HCPCS Level II modifiers and X12 N 837P/I modifier code lists.',
                     example: { fields: { q: '25' }, expected: '25 - Significant, separately identifiable E/M service by the same physician on the same day.' } },
  'revenue-codes': { source: { dataset: 'crosswalks', label: 'CMS UB-04 revenue codes' },
                     citation: 'NUBC UB-04 Revenue Code structural digits (numeric only; NUBC narrative descriptors not bundled).',
                     example: { fields: { q: '450' }, expected: '450 - Emergency room (general).' } },
  carc:            { source: { dataset: 'crosswalks', label: 'X12 Claim Adjustment Reason Codes' },
                     citation: 'X12 Claim Adjustment Reason Codes (CARC), maintained by the Code Maintenance Committee under HIPAA 45 CFR 162.',
                     example: { fields: { q: '45' }, expected: '45 - Charge exceeds fee schedule / maximum allowable or contracted/legislated fee arrangement.' } },
  rarc:            { source: { dataset: 'crosswalks', label: 'X12 Remittance Advice Remark Codes' },
                     citation: 'X12 Remittance Advice Remark Codes (RARC), maintained by CMS under HIPAA 45 CFR 162.',
                     example: { fields: { q: 'N143' }, expected: 'N143 - remark text per the bundled X12 RARC list.' } },

  // ---- Group A: v4 extensions (utilities 82-93) ----
  'hcpcs-mod':      { source: { dataset: 'hcpcs-modifiers', label: 'CMS HCPCS Level II Modifier file' },
                      citation: 'CMS HCPCS Level II modifiers; public-domain release. Modifier semantics per CMS HCPCS coding guidelines.',
                      example: { fields: { q: '25' }, expected: '25 - Significant, separately identifiable E/M service.' } },
  'pos-lookup':     { source: { dataset: 'pos-codes', label: 'CMS Place of Service codes' },
                      citation: 'CMS Place of Service Code Set for Professional Claims (HIPAA-mandated, 45 CFR 162.1002).',
                      example: { fields: { q: '11' }, expected: '11 - Office.' } },
  'tob-decode':     { source: { dataset: 'tob-codes', label: 'NUBC Type of Bill structural digits (numeric only)' },
                      citation: 'NUBC UB-04 Type of Bill, structural digits per the NUBC Official UB-04 Data Specifications (numeric only; NUBC narrative descriptors not bundled).',
                      example: { fields: { q: '0111' }, expected: 'Hospital, Inpatient (Part A), Admit Through Discharge' } },
  'rev-table':      { source: { dataset: 'revenue-codes', label: 'NUBC Revenue Code summary (numeric only)' },
                      citation: 'NUBC UB-04 Revenue Codes, structural numeric reference per the NUBC Official UB-04 Data Specifications.',
                      example: { fields: { q: '450' }, expected: '450 - Emergency room (general).' } },
  'nubc-codes':     { source: { dataset: 'nubc-special-codes', label: 'NUBC Condition / Occurrence / Value codes (numeric only)' },
                      citation: 'NUBC Condition, Occurrence, and Value codes per the NUBC Official UB-04 Data Specifications (numeric only).',
                      example: { fields: { q: '02' }, expected: 'Condition / Occurrence / Value entries matching "02".' } },
  'drg-lookup':     { source: { dataset: 'drg', label: 'CMS IPPS MS-DRG (Final Rule)' },
                      citation: 'CMS Inpatient Prospective Payment System MS-DRG definitions, current Final Rule. Severity rules per the MS-DRG Definitions Manual.',
                      example: { fields: { q: '291' }, expected: '291 - Heart failure & shock with MCC.' } },
  'apc-lookup':     { source: { dataset: 'apc', label: 'CMS OPPS APC Addendum' },
                      citation: 'CMS Outpatient Prospective Payment System Ambulatory Payment Classifications, current Addendum A/B (CMS public release).',
                      example: { fields: { q: '5012' }, expected: '5012 - Level 2 Examinations and Related Services (per current OPPS Addendum A).' } },
  'pcs-lookup':     { source: { dataset: 'icd10-pcs', label: 'CMS ICD-10-PCS' },
                      citation: 'ICD-10-PCS Tables and Index; CMS public-domain release. Annual fiscal-year update.',
                      example: { fields: { q: '0DTJ4ZZ' }, expected: '0DTJ4ZZ - Resection of appendix, percutaneous endoscopic approach.' } },
  'rxnorm-lookup':  { source: { dataset: 'rxnorm', label: 'NLM RxNorm' },
                      citation: 'RxNorm normalized clinical drug nomenclature; NLM/NIH public-domain release. Updated monthly upstream.',
                      example: { fields: { q: 'aspirin' }, expected: 'RxNorm entries matching "aspirin" from the bundled subset.' } },
  'ndc-rxnorm':     { source: { dataset: 'rxnorm', label: 'FDA NDC + NLM RxNorm crosswalk' },
                      citation: 'NDC -> RxNorm CUI crosswalk derived from the NLM RxNorm release and the FDA National Drug Code Directory.',
                      example: { fields: { q: 'aspirin' }, expected: 'NDC + RxNorm crosswalk entries matching "aspirin".' } },

  // ---- Group B: Pricing ----

  // ---- Group B: v4 extensions (utilities 94-104) ----

  // ---- Group C: Patient tools ----
  decoder:        { citation: 'Code patterns per CMS billing-code conventions: ICD-10-CM (3-7 alphanumeric, dot after 3), CPT (5 numeric), HCPCS Level II (1 letter + 4 digits), NPI (10-digit Luhn-checksum, 45 CFR 162.406).',
                    example: { fields: { bill: 'Patient bill\nDOS 2026-04-12  Office visit 99213  $185.00\nDx I10  J3490 administered  $42.00\nNPI 1234567893  POS 11' },
                               expected: 'Decoder finds 99213 (possible CPT), J3490 (HCPCS), I10 (ICD-10), POS 11, Luhn-valid NPI; total $227.00.' } },
  insurance:      { citation: 'Field naming follows the NUBC UB-04 institutional claim form and CMS-1500 professional claim (OMB-approved 0938-1197 / 0938-1197). NPI per 45 CFR 162.406.',
                    example: { fields: { memberId: 'W123456789', groupId: '0001', planName: 'Gold PPO 1500', planType: 'PPO', bin: '003858', pcn: 'A4', rxGroup: 'RXANTHEM', phone: '1-800-555-0100', providerPhone: '1-800-555-0199' },
                               expected: 'Card fields populated; the worked-example panel below explains each field.' } },
  'eob-decoder':  { source: { dataset: 'crosswalks', label: 'X12 CARC and RARC code lists' },
                    citation: 'X12 Claim Adjustment Reason Codes and Remittance Advice Remark Codes, maintained under HIPAA 45 CFR 162. Plain-English summaries by the project author.',
                    example: { fields: { eob: 'Allowed: $185.00\nPlan paid: $148.00\nAdjustment: $37.00\nPatient responsibility: $37.00\nCARC 45  RARC N143' },
                               expected: 'EOB summary lists allowed, plan-paid, adjustment, patient responsibility, plus CARC 45 and RARC N143 with their definitions.' } },
  'no-surprises': { source: { dataset: 'no-surprises', label: 'CMS / HHS No Surprises Act regulatory text' },
                    citation: 'No Surprises Act, Public Health Service Act Section 2799 (added by Title I of Division BB of the Consolidated Appropriations Act, 2021); 45 CFR 149. Federal protections; state surprise-billing laws may add to (not displace) the federal floor.',
                    example: { fields: { 'nsa-sel': 'er-out-of-network' }, expected: 'Out-of-network emergency care: covered by the No Surprises Act per PHSA Section 2799A-1.' } },

  // ---- Group C: v4 extensions (utilities 105-114) ----
  'insurance-card':      { source: null,
                           citation: 'Original plain-English explanations by the project author. No external lookup is performed.',
                           example: { fields: { 'ic-member': 'W123456789', 'ic-group': '0001', 'ic-plan': 'Gold PPO 1500', 'ic-type': 'PPO', 'ic-bin': '003858', 'ic-pcn': 'A4', 'ic-rxgroup': 'RXANTHEM', 'ic-csphone': '1-800-555-0100', 'ic-provphone': '1-800-555-0199' },
                                      expected: 'Print-ready insurance reference card lists each field with its plain-English explanation.' } },
  'abn-explainer':       { source: null,
                           citation: 'CMS Form CMS-R-131 (Advance Beneficiary Notice). Plain-English summaries by the project author; CMS publishes the authoritative form and instructions.' },
  'msn-decoder':         { citation: 'CMS Medicare Summary Notice format. Reference parsing only.',
                           example: { fields: { msn: 'Medicare-approved amount: $185.00\nMedicare paid: $148.00\nProvider adjustment: $37.00\nMaximum you may be billed: $0.00' },
                                      expected: 'MSN summary shows approved $185.00, paid $148.00, adjustment $37.00, max billable $0.00.' } },
  'idr-eligibility':     { citation: 'No Surprises Act (Public Health Service Act Section 2799), 45 CFR 149. Federal IDR scope; does not displace state IDR processes.' },
  'appeal-letter':       { citation: 'Educational template. Plan-specific appeal procedures govern. Not legal advice.',
                           example: { fields: { 'al-pt': 'Jane Doe', 'al-id': 'W123456789', 'al-dos': '2026-04-12', 'al-prov': 'Acme Internal Medicine', 'al-svc': 'MRI lumbar spine without contrast', 'al-dx': 'M54.5', 'al-plan': 'Anthem Gold PPO', 'al-denial': '2026-04-25', 'al-reason': 'Not medically necessary' },
                                      expected: 'Click "Build printable letter" to render an appeal letter addressed to the plan with the denial reason quoted back.' } },
  'hipaa-roa':           { citation: 'HIPAA Privacy Rule, 45 CFR 164.524. Right of Access; 30-day response requirement with one 30-day extension; cost-based fee cap.',
                           example: { fields: { 'roa-pt': 'Jane Doe', 'roa-dob': '1985-03-12', 'roa-fac': 'Acme Internal Medicine', 'roa-range': '2024-01-01 to 2025-01-01', 'roa-recs': 'Office visit notes, lab results, imaging reports', 'roa-fmt': 'electronic (PDF)', 'roa-deliver': 'patient portal' },
                                      expected: 'Click "Build printable request" to render a 45 CFR 164.524 letter citing the 30-day response requirement and the cost-based fee cap.' } },
  'birthday-rule':       { citation: 'Standard insurance industry rule for two-parent dependent coverage; some self-funded ERISA plans interpret differently. Reference only.',
                           example: { fields: { 'br-a-dob': '1985-03-12', 'br-b-dob': '1986-08-21', 'br-cust': 'shared', 'br-court': '' },
                                      expected: 'Primary: Parent A. Reason: earlier birthday in the calendar year (March 12 < August 21).' } },
  'cobra-timeline':      { citation: 'Consolidated Omnibus Budget Reconciliation Act, 29 USC 1162: 18-month standard maximum; 29-month disability extension; 36 months for divorce, death, Medicare entitlement of covered employee.',
                           example: { fields: { 'cb-date': '2026-03-15', 'cb-type': 'job-loss-involuntary' },
                                      expected: '18-month max: election deadline 2026-05-14; first payment 45 days after election; coverage end 2027-09-15.' } },
  'medicare-enrollment': { citation: 'Medicare IEP (7 months around 65th birthday); GEP (Jan 1 - Mar 31 annually); Part B SEP for loss of employer coverage (8 months). Reference only.',
                           example: { fields: { 'me-dob': '1961-08-15', 'me-scenario': '' },
                                      expected: 'IEP 2026-05-01 through 2026-11-30 (covers 65th birthday in August 2026); GEP each Jan 1 - Mar 31; Part D LEP applies if Part D enrollment is delayed.' } },
  'aca-sep':             { citation: '45 CFR 155.420. SEP windows and qualifying life events under the ACA.',
                           example: { fields: { 'sep-evt': 'loss-of-coverage' },
                                      expected: 'Loss of qualifying coverage: 60-day window before AND after the event; coverage starts the first of the month after plan selection.' } },

  // ---- Group D: Provider lookup ----

  // ---- Group D: v4 extensions (utilities 115-116) ----

  // ---- Group E: Clinical math (citations + examples) ----
  'unit-converter':    { citation: 'Standard SI and US customary unit definitions.',
                         example: { fields: { kind: 'weight', val: '70', from: 'kg', to: 'lb' }, expected: '70 kg = 154.32 lb' } },
  bmi:                 { citation: 'Quetelet 1835; Keys A, et al. Indices of relative weight and obesity. J Chronic Dis. 1972;25(6).',
                         example: { fields: { w: '70', h: '1.75' }, expected: 'BMI 22.9 (Normal)' } },
  bsa:                 { citation: 'Du Bois D, Du Bois EF. Arch Intern Med. 1916;17:863. Mosteller RD. N Engl J Med. 1987;317(17):1098.',
                         example: { fields: { w: '70', h: '175' }, expected: 'Du Bois ~1.85 m^2; Mosteller ~1.84 m^2' } },
  map:                 { citation: 'Standard physiology: MAP = ((2 * DBP) + SBP) / 3.',
                         example: { fields: { s: '120', d: '80' }, expected: 'MAP 93.3 mmHg' } },
  'anion-gap':         { citation: 'Emmett M, Narins RG. Clinical use of the anion gap. Medicine (Baltimore). 1977;56(1):38-54.',
                         example: { fields: { na: '140', cl: '100', hco3: '24', alb: '4' }, expected: 'AG 16; corrected AG 16' } },
  'corrected-calcium': { citation: 'Payne RB, et al. Interpretation of serum calcium in patients with abnormal serum proteins. BMJ. 1973;4(5893):643-646.',
                         example: { fields: { ca: '8.0', alb: '2.0' }, expected: 'Corrected Ca 9.6 mg/dL' } },
  'corrected-sodium':  { citation: 'Katz MA. NEJM. 1973. Hillier TA, Abbott RD, Barrett EJ. Am J Med. 1999;106(4):399-403.',
                         example: { fields: { na: '130', g: '600' }, expected: 'Corrected Na 138 (1.6); 142 (2.4)' } },
  'aa-gradient':       { citation: 'West JB. Respiratory Physiology: The Essentials. PAO2 = (FiO2 * (760-47)) - (PaCO2 / 0.8).',
                         example: { fields: { fio2: '0.21', paco2: '40', pao2: '90' }, expected: 'A-a gradient ~9.7 mmHg' } },
  egfr:                { citation: 'Inker LA, Eneanya ND, Coresh J, et al. New creatinine and cystatin C-based equations to estimate GFR without race. NEJM. 2021;385(19):1737-1749. Implements the 2021 race-free creatinine-only equation.',
                         example: { fields: { scr: '1.0', age: '60', sex: 'F' }, expected: 'eGFR ~91 mL/min/1.73m^2' } },
  'cockcroft-gault':   { citation: 'Cockcroft DW, Gault MH. Prediction of creatinine clearance from serum creatinine. Nephron. 1976;16(1):31-41.',
                         example: { fields: { age: '60', w: '80', scr: '1.0', sex: 'M' }, expected: 'CrCl 88.89 mL/min' } },
  'pack-years':        { citation: 'Standard tobacco-history measure: pack-years = packs per day x years smoked.',
                         example: { fields: { p: '1.5', y: '20' }, expected: 'Pack-years 30' } },
  'due-date':          { citation: 'Naegele rule: due date = LMP + 280 days.',
                         example: { fields: { lmp: '2025-01-01' }, expected: 'Due date 2025-10-08' } },
  qtc:                 { citation: 'Bazett 1920; Fridericia 1920; Sagie (Framingham) 1992; Hodges 1983. All four formulas reported side by side.',
                         example: { fields: { qt: '400', hr: '60' }, expected: 'All four formulas ~400 ms' } },
  'pf-ratio':          { citation: 'ARDS Definition Task Force. Berlin Definition. JAMA. 2012;307(23):2526-2533.',
                         example: { fields: { pao2: '90', fio2: '0.5' }, expected: 'P/F 180 (Moderate ARDS)' } },

  // ---- Group E: v4 extensions (utilities 117-128) ----
  'anion-gap-dd':    { citation: 'Standard chemistry references; Wrenn KD. The delta gap. Ann Emerg Med. 1990;19(11):1310-1313.',
                       example: { fields: { na: '140', cl: '100', hco3: '14', alb: '4' }, expected: 'AG 26; delta-AG 14; delta-HCO3 10; ratio 1.4 - pure AG metabolic acidosis' } },
  'corrected-ca-na': { citation: 'Payne RB BMJ 1973 (Ca); Katz NEJM 1973 / Hillier Am J Med 1999 (Na).',
                       example: { fields: { ca: '8.0', 'cca-alb': '2.0', 'csna-na': '130', glu: '600' },
                                  expected: 'Corrected Ca 9.6 mg/dL; corrected Na (Katz) 138, (Hillier) 142.' } },
  'osmolal-gap':     { citation: 'Calculated osm = 2*Na + glucose/18 + BUN/2.8 (+ EtOH/4.6). Gap >10 raises suspicion of toxic alcohols.',
                       example: { fields: { measured: '300', 'og-na': '140', 'og-glu': '90', 'og-bun': '14', 'og-etoh': '0' },
                                  expected: 'Calculated osm ~290; gap ~10 (within normal range).' } },
  'aa-pf-suite':     { citation: 'West JB. Respiratory Physiology. ARDS Berlin Definition: JAMA 2012;307(23):2526.',
                       example: { fields: { 'sf-fio2': '0.21', 'sf-pao2': '90', 'sf-paco2': '40', 'sf-age': '40' },
                                  expected: 'A-a gradient ~9.7 mmHg (expected ~14 by age); P/F ratio 429 (Normal).' } },
  winters:           { citation: "Albert MS, Dell RB, Winters RW. Quantitative displacement of acid-base equilibrium in metabolic acidosis. Ann Intern Med 1967;66(2):312-322.",
                       example: { fields: { 'wf-hco3': '14', 'wf-paco2': '29' }, expected: "Expected PaCO2 27-31; appropriate respiratory compensation" } },
  'shock-index':     { citation: 'Allgower & Burri 1967 (shock index). Standard physiology for MAP and PP.',
                       example: { fields: { 'si-sbp': '120', 'si-dbp': '80', 'si-hr': '110' },
                                  expected: 'MAP 93.3; PP 40; shock index 0.92; modified shock index 1.18.' } },
  'bw-bsa-suite':    { citation: 'Devine 1974 (IBW); 0.4 AdjBW rule; Mosteller NEJM 1987; Du Bois 1916.',
                       example: { fields: { 'bw-hin': '69', 'bw-kg': '85', 'bw-sex': 'M' },
                                  expected: 'IBW ~70.5 kg; AdjBW ~76.3 kg; BSA Mosteller ~2.00 m^2; BSA Du Bois ~2.01 m^2.' } },
  'egfr-suite':      { citation: 'Inker LA et al. NEJM 2021 (CKD-EPI race-free); Levey AS et al. Ann Intern Med 1999 (MDRD); Cockcroft-Gault Nephron 1976.',
                       example: { fields: { 'es-scr': '1.0', 'es-age': '60', 'es-w': '70', 'es-sex': 'M' }, expected: 'CKD-EPI 2021 ~89; MDRD ~77; Cockcroft-Gault ~78 mL/min' } },
  'fena-feurea':     { citation: 'Espinel CH JAMA 1976 (FENa); Carvounis CP Kidney Int 2002 (FEUrea).',
                       example: { fields: { 'fn-una': '20', 'fn-pna': '140', 'fn-ucr': '50', 'fn-pcr': '2.0', 'fu-uu': '300', 'fu-pu': '60' },
                                  expected: 'FENa ~0.57% (prerenal); FEUrea ~20% (prerenal).' } },
  'maint-fluids':    { citation: 'Holliday MA, Segar WE. Pediatrics 1957. 4-2-1 maintenance rule.',
                       example: { fields: { 'mf-w': '70' }, expected: 'Maintenance: 110 mL/hr (40 + 20 + 50)' } },
  'qtc-suite':       { citation: 'Bazett 1920; Fridericia 1920; Sagie (Framingham) 1992; Hodges 1983.',
                       example: { fields: { 'qs-qt': '400', 'qs-hr': '60' }, expected: 'All four formulas ~400 ms' } },
  'preg-dating':     { citation: 'Naegele rule (LMP+280); Robinson-Fleming CRL formula; ACOG Practice Bulletin redating thresholds (T1: 7d; T2: 14d; T3: 21d).',
                       example: { fields: { 'pd-lmp': '2025-12-23', 'pd-crl': '50', 'pd-us': '2026-03-12' },
                                  expected: 'LMP-derived EDD 2026-09-29; CRL-derived GA at ultrasound ~11w 5d; small T1 discordance (~3 days), within accepted limit.' } },

  // ---- Group F: Medication math ----
  'drip-rate':         { citation: 'Standard infusion arithmetic: rate (mL/hr) = volume * 60 / duration; gtts/min = volume * drop factor / duration.',
                         example: { fields: { v: '1000', t: '480', df: '15' }, expected: '125 mL/hr; 31 gtts/min' } },
  'weight-dose':       { citation: 'Standard weight-based dose: total = weight * per-kg dose. Verify against your formulary.',
                         example: { fields: { w: '70', d: '5', u: 'mg/kg' }, expected: 'Total 350 mg' } },
  'conc-rate':         { citation: 'Standard infusion math: rate (mL/hr) = (dose per minute / concentration per mL) * 60. Bag presets per common institutional protocols.',
                         example: { fields: { dv: '0.1', du: 'mcg/kg/min', w: '70', cv: '0.064', cu: 'mg/mL' }, expected: 'Norepi at 0.1 mcg/kg/min, 70 kg, 64 mcg/mL: ~6.56 mL/hr' } },
  'peds-dose':         { citation: 'AAP, NLM/DailyMed, manufacturer labels. Reference table only.' },
  'insulin-drip':      { citation: 'Example protocols only. Use your institution\'s active insulin protocol.',
                         example: { fields: { p: 'mod', bg: '180' }, expected: 'Suggested rate (example only): 2 units/hr (moderate-intensity sample protocol).' } },
  'anticoag-reversal': { citation: 'Standard reversal references; verify against your institution\'s protocol and current literature.' },
  'high-alert':        { citation: 'Identities are factual. ISMP maintains the authoritative high-alert medication list and formatting.' },

  // ---- Group F: v4 extensions (utilities 129-135) ----
  'opioid-mme':     { source: { dataset: 'mme-factors', label: 'CDC 2022 Opioid MME conversion factors' },
                      citation: 'CDC Clinical Practice Guideline for Prescribing Opioids - United States, 2022. MMWR Recomm Rep. 2022;71(3):1-95.',
                      example: { fields: {}, expected: 'Morphine 30 mg q4h = 180 MME (above the 90 MME CDC threshold)' } },
  'steroid-equiv':  { source: { dataset: 'steroid-equiv', label: 'Standard pharmacology references (project-author table)' },
                      citation: 'Glucocorticoid equipotent-dose ratios per standard pharmacology references (e.g., Goodman & Gilman; Brunton, Hilal-Dandan, Knollmann eds., 13e). Mineralocorticoid activity noted separately; verify against your formulary.',
                      example: { fields: { 'st-dose': '5', 'st-from': 'prednisone', 'st-to': 'methylprednisolone' },
                                 expected: '5 mg prednisone ~ 4 mg methylprednisolone' } },
  'benzo-equiv':    { source: { dataset: 'benzo-equiv', label: 'Ashton benzodiazepine equivalence table (public)' },
                      citation: 'Ashton CH. Benzodiazepines: How They Work and How to Withdraw (the Ashton Manual).',
                      example: { fields: { 'bz-dose': '10', 'bz-from': 'diazepam', 'bz-to': 'lorazepam' },
                                 expected: '10 mg diazepam ~ 1.0 mg lorazepam (Ashton equivalence).' } },
  'abx-renal':      { source: { dataset: 'abx-renal', label: 'FDA labels via DailyMed (subset)' },
                      citation: 'Renal-adjusted antibiotic dosing per FDA-approved labeling (DailyMed). Verify against your institution\'s antimicrobial stewardship guidance.',
                      example: { fields: { 'abx-crcl': '70' }, expected: 'Cefepime 1-2 g q8-12h at default selector' } },
  vasopressor:      { source: { dataset: 'vasopressor-doses', label: 'FDA vasopressor labels (subset)' },
                      citation: 'Standard infusion math: rate (mL/hr) = (dose per min / concentration per mL) * 60.',
                      example: { fields: { 'vp-w': '70', 'vp-conc': '64', 'vp-dose': '0.1', 'vp-rate': '6.56' },
                                 expected: 'Norepinephrine at 0.1 mcg/kg/min, 70 kg, 64 mcg/mL: ~6.56 mL/hr (forward); 6.56 mL/hr -> ~0.1 mcg/kg/min (reverse).' } },
  'tpn-macro':      { source: { dataset: 'tpn-rules', label: 'Standard nutrition references' },
                      citation: 'Dextrose 3.4 kcal/g; protein 4 kcal/g; lipid (20% emulsion) 2 kcal/mL.',
                      example: { fields: { 'tpn-vol': '1500', 'tpn-d': '20', 'tpn-aa': '5', 'tpn-lipid': '10' }, expected: '1620 kcal: 300 g dextrose / 75 g protein / 30 g lipid' } },
  'iv-to-po':       { source: { dataset: 'iv-to-po', label: 'FDA labels (subset)' },
                      citation: 'Bioavailability values per FDA labeling. Verify against current institutional formulary.' },

  // ---- Group G: Scoring ----
  gcs:         { citation: 'Teasdale G, Jennett B. Assessment of coma and impaired consciousness. Lancet. 1974;2(7872):81-84.',
                 example: { fields: { eye: '3', verbal: '4', motor: '5' }, expected: 'GCS 12' },
                 interpretation: {
                   bands: [
                     { range: '13-15', text: 'Mild brain injury per Teasdale & Jennett.' },
                     { range: '9-12',  text: 'Moderate brain injury per Teasdale & Jennett.' },
                     { range: '3-8',   text: 'Severe brain injury per Teasdale & Jennett (GCS <=8 is the conventional threshold for considering definitive airway protection).' },
                   ],
                   sourceQuoted: true,
                   sourceCitation: 'Teasdale G, Jennett B. Lancet. 1974;2(7872):81-84.',
                 } },
  apgar:       { citation: 'Apgar V. A proposal for a new method of evaluation of the newborn infant. Curr Res Anesth Analg. 1953;32(4):260-267.',
                 example: { fields: { appearance: '2', pulse: '2', grimace: '2', activity: '2', respiration: '2' }, expected: 'APGAR 10' } },
  'peds-vitals': { source: { dataset: 'clinical', label: 'PALS reference values; AHA' },
                   citation: 'AHA Pediatric Advanced Life Support (PALS) reference vital-sign ranges by age band. Numeric reference only.',
                   example: { fields: { pv: '1-3 yrs' }, expected: 'Toddler heart-rate, respiratory-rate, and SBP ranges from the PALS reference table.' } },
  'lab-ranges':  { source: { dataset: 'clinical', label: 'Common adult reference ranges; lab-specific ranges supersede.' },
                   citation: 'Common adult laboratory reference ranges per NIH MedlinePlus and Harrison\'s Principles of Internal Medicine (21e). Lab-specific reference ranges supersede.',
                   example: { fields: { q: 'sodium' }, expected: 'Sodium reference range (mEq/L) from the bundled adult lab table.' } },
  abg:         { citation: 'Acid-base interpretation per standard physiology; Winter formula compensation; ARDS Berlin definition for P/F bands.',
                 example: { fields: { pH: '7.30', paco2: '30', hco3: '14' }, expected: 'Metabolic acidosis with appropriate respiratory compensation' } },
  'wells-pe':  { citation: 'Wells PS, et al. Derivation of a simple clinical model to categorize patients\' probability of pulmonary embolism. Thromb Haemost. 2000;83(3):416-420.',
                 example: { fields: { peLikely: '1', hrOver100: '1' }, expected: 'Wells PE total 4.5 (PE-likely group, moderate probability).' },
                 interpretation: {
                   bands: [
                     { range: '<=4',  text: 'PE unlikely per the two-tier Wells PE model. Consider D-dimer to further risk-stratify per source.' },
                     { range: '>4',   text: 'PE likely per the two-tier Wells PE model. Imaging (CTPA or V/Q) per source.' },
                   ],
                   sourceQuoted: true,
                   sourceCitation: 'Wells PS, et al. Thromb Haemost. 2000;83(3):416-420; two-tier dichotomization per Wells 2001 (Ann Intern Med).',
                 } },
  'wells-dvt': { citation: 'Wells PS, et al. Value of assessment of pretest probability of deep-vein thrombosis. Lancet. 1997;350(9094):1795-1798.',
                 example: { fields: { tendernessAlongVeins: '1', entireLegSwollen: '1', calfSwellingGt3cm: '1' },
                            expected: 'Wells DVT total 3 (High probability).' },
                 interpretation: {
                   bands: [
                     { range: '<=0', text: 'Low probability of DVT per source.' },
                     { range: '1-2', text: 'Moderate probability of DVT per source.' },
                     { range: '>=3', text: 'High probability of DVT per source.' },
                   ],
                   sourceQuoted: true,
                   sourceCitation: 'Wells PS, et al. Lancet. 1997;350(9094):1795-1798, Table 3.',
                 } },
  chads:       { citation: 'Lip GYH, et al. Refining clinical risk stratification for predicting stroke and thromboembolism in atrial fibrillation. Chest. 2010;137(2):263-272.',
                 example: { fields: { hypertension: '1', ageGte65: '1', diabetes: '1' },
                            expected: 'CHA2DS2-VASc total 3 (consider anticoagulation).' },
                 interpretation: {
                   bands: [
                     { range: '0',  text: 'Low risk. Antithrombotic therapy not recommended per source.' },
                     { range: '1',  text: 'Low-moderate risk. Oral anticoagulation may be considered per source.' },
                     { range: '>=2', text: 'Moderate-to-high risk. Oral anticoagulation recommended per source.' },
                   ],
                   sourceQuoted: true,
                   sourceCitation: 'Lip GYH, et al. Chest. 2010;137(2):263-272.',
                 } },
  hasbled:     { citation: 'Pisters R, et al. A novel user-friendly score (HAS-BLED). Chest. 2010;138(5):1093-1100.',
                 example: { fields: { hypertension: '1', ageGt65: '1' },
                            expected: 'HAS-BLED total 2 (moderate bleeding risk).' },
                 interpretation: {
                   bands: [
                     { range: '0-1', text: 'Low risk of major bleeding per source (bleeds per 100 patient-years: 1.13 at score 0; 1.02 at score 1).' },
                     { range: '2',   text: 'Moderate risk of major bleeding per source (1.88 bleeds per 100 patient-years).' },
                     { range: '>=3', text: 'High risk of major bleeding per source. Caution and regular review of bleeding-risk factors advised per source.' },
                   ],
                   sourceQuoted: true,
                   sourceCitation: 'Pisters R, et al. Chest. 2010;138(5):1093-1100, Table 5.',
                 } },
  nihss:       { citation: 'Brott T, Adams HP Jr, et al. Measurements of acute cerebral infarction: a clinical examination scale. Stroke. 1989;20(7):864-870. Public-domain instrument maintained by NIH/NINDS.',
                 example: { fields: { '1a': '1', '4': '1', '5': '2', '9': '1' },
                            expected: 'NIHSS total 5 (Moderate stroke).' },
                 interpretation: {
                   bands: [
                     { range: '0',     text: 'No stroke symptoms per NIH/NINDS interpretation guide.' },
                     { range: '1-4',   text: 'Minor stroke per NIH/NINDS interpretation guide.' },
                     { range: '5-15',  text: 'Moderate stroke per NIH/NINDS interpretation guide.' },
                     { range: '16-20', text: 'Moderate-to-severe stroke per NIH/NINDS interpretation guide.' },
                     { range: '21-42', text: 'Severe stroke per NIH/NINDS interpretation guide.' },
                   ],
                   sourceQuoted: true,
                   sourceCitation: 'NIH/NINDS NIH Stroke Scale interpretation conventions per Adams HP Jr, et al. Neurology. 1999;53(1):126-131 and the public-domain NIHSS form.',
                 } },
  asa:         { source: { dataset: 'clinical', label: 'ASA Physical Status Classification; original short summaries by project author.' },
                 citation: 'American Society of Anesthesiologists Physical Status Classification System; ASA House of Delegates approved 2014, last amended December 13, 2020. Class names are ASA-defined; short plain-English summaries are by the project author.' },
  mallampati:  { citation: 'Mallampati SR, et al. A clinical sign to predict difficult tracheal intubation. Can Anaesth Soc J. 1985;32(4):429-434.' },
  beers:       { citation: 'AGS Beers Criteria. Drug-condition pairs are clinical facts; original brief notes by project author. AGS publishes the authoritative formatted list.',
                 example: { fields: { q: 'benzodiazepine' }, expected: 'Beers Criteria entries matching "benzodiazepine" (avoid in older adults; risk of falls / cognitive impairment).' } },

  // ---- Group G: v4 extensions waves 1-2 (utilities 136-145) ----
  timi:             { citation: 'Antman EM, et al. The TIMI Risk Score for Unstable Angina/Non-ST Elevation MI. JAMA. 2000;284(7):835-842.',
                      example: { fields: { 'tm-age': '1', 'tm-rf': '1', 'tm-asa': '1' },
                                 expected: 'TIMI 3 - intermediate risk band.' },
                      interpretation: {
                        bands: [
                          { range: '0-1', text: '14-day risk of all-cause mortality, new/recurrent MI, or severe ischemia requiring urgent revascularization: 4.7% per source.' },
                          { range: '2',   text: '14-day composite risk: 8.3% per source.' },
                          { range: '3',   text: '14-day composite risk: 13.2% per source.' },
                          { range: '4',   text: '14-day composite risk: 19.9% per source.' },
                          { range: '5',   text: '14-day composite risk: 26.2% per source.' },
                          { range: '6-7', text: '14-day composite risk: 40.9% per source.' },
                        ],
                        sourceQuoted: true,
                        sourceCitation: 'Antman EM, et al. JAMA. 2000;284(7):835-842, Table 3 (TIMI 11B / ESSENCE pooled cohort).',
                      } },
  grace:            { citation: 'Granger CB, et al. GRACE Project. Arch Intern Med. 2003;163(19):2345-2353. Simplified-points implementation.',
                      example: { fields: { 'gr-age': '70', 'gr-hr': '95', 'gr-sbp': '115', 'gr-cr': '1.2', 'gr-killip': '1' },
                                 expected: 'GRACE points calculation lands in the intermediate-risk band.' } },
  heart:            { citation: 'Six AJ, Backus BE, Kelder JC. HEART score. Neth Heart J. 2008;16(6):191-196.',
                      example: { fields: { 'h-hist': '1', 'h-ekg': '0', 'h-age': '1', 'h-rf': '1', 'h-trop': '0' },
                                 expected: 'HEART 3 - low-risk band (~1.7% MACE at 6 weeks).' },
                      interpretation: {
                        bands: [
                          { range: '0-3',  text: 'Low risk (~1.7% MACE at 6 weeks per Backus 2013 validation). Suitable for early discharge per source.' },
                          { range: '4-6',  text: 'Moderate risk (~16.6% MACE at 6 weeks). Admission for clinical observation per source.' },
                          { range: '7-10', text: 'High risk (~50% MACE at 6 weeks). Early invasive strategy per source.' },
                        ],
                        sourceQuoted: true,
                        sourceCitation: 'Backus BE, Six AJ, Kelder JC, et al. A prospective validation of the HEART score. Int J Cardiol. 2013;168(3):2153-2158.',
                      } },
  perc:             { citation: 'Kline JA, et al. PERC rule. J Thromb Haemost. 2004;2(8):1247-1255. Use only if clinical pretest probability is low.',
                      example: { fields: { 'pc-age': '1' },
                                 expected: 'PERC 1 positive feature (age >= 50): rule-out does NOT apply.' },
                      interpretation: {
                        bands: [
                          { range: '0 features positive', text: 'PERC negative. In patients with low pretest probability, PE can be excluded without further testing per source.' },
                          { range: '>=1 feature positive', text: 'PERC positive. Rule-out does not apply; further evaluation per source.' },
                        ],
                        sourceQuoted: true,
                        sourceCitation: 'Kline JA, et al. J Thromb Haemost. 2004;2(8):1247-1255.',
                      } },
  'wells-pe-geneva':{ citation: 'Wells PS, et al. Thromb Haemost. 2000;83(3):416-420 (Wells PE). Le Gal G, et al. Ann Intern Med. 2006;144(3):165-171 (revised Geneva).',
                      example: { fields: { 'wp-alt': '1', 'wp-hr': '1', 'gv-hr': '105' },
                                 expected: 'Wells PE 4.5 (PE-likely); Geneva ~3 (low/intermediate).' } },
  'curb-65':        { citation: 'Lim WS, et al. Defining community acquired pneumonia severity. Thorax. 2003;58(5):377-382.',
                      example: { fields: { 'cu-conf': '1', 'cu-age': '1' },
                                 expected: 'CURB-65 2 (consider hospitalization).' },
                      interpretation: {
                        bands: [
                          { range: '0-1', text: 'Low severity (30-day mortality ~1.5%). Likely suitable for outpatient treatment per source.' },
                          { range: '2',   text: 'Intermediate severity (mortality ~9.2%). Short hospital stay or closely supervised outpatient treatment per source.' },
                          { range: '3-5', text: 'Severe pneumonia (mortality ~22%). Manage as severe; assess for ICU admission, especially with score 4-5, per source.' },
                        ],
                        sourceQuoted: true,
                        sourceCitation: 'Lim WS, et al. Thorax. 2003;58(5):377-382, Table 4.',
                      } },
  psi:              { citation: 'Fine MJ, et al. Pneumonia Severity Index. NEJM. 1997;336(4):243-250. Reference points-only implementation; class V advisory.',
                      example: { fields: { 'ps-age': '70', 'ps-sex': 'M', 'ps-rr': '1' },
                                 expected: 'PSI ~90 - Class III (short observation typically considered).' } },
  'qsofa-sofa':     { citation: 'Singer M, et al. Sepsis-3 (qSOFA). JAMA. 2016;315(8):801-810. Vincent JL, et al. SOFA. Intensive Care Med. 1996;22(7):707-710.',
                      example: { fields: { 'q-rr': '1', 'q-am': '1', 's-resp': '1', 's-cv': '1' },
                                 expected: 'qSOFA 2 (high risk for poor outcome); SOFA 2.' } },
  'meld-childpugh': { citation: 'Kim WR, et al. MELD-3.0. Gastroenterology. 2021;161(6):1887-1895. Pugh RN, et al. Br J Surg. 1973;60(8):646-649 (Child-Pugh).',
                      example: { fields: { 'm-bili': '2.0', 'm-inr': '1.5', 'm-cr': '1.3', 'm-na': '135', 'm-alb': '3.0', 'm-sex': 'M', 'cp-asc': 'mild', 'cp-enc': 'none' },
                                 expected: 'MELD-3.0 ~17; Child-Pugh ~7 (Class B).' } },
  'ranson-bisap':   { citation: 'Ranson JH, et al. Surg Gynecol Obstet. 1974;139(1):69-81. Wu BU, et al. BISAP. Gut. 2008;57(12):1698-1703.',
                      example: { fields: { 'r-age': '1', 'r-wbc': '1', 'b-bun': '1', 'b-age': '1' },
                                 expected: 'Ranson 2; BISAP 2 (intermediate severity).' } },

  // ---- Group G: v4 extensions waves 3-4 (utilities 146-156) ----
  centor:               { citation: 'Centor RM, et al. Med Decis Making. 1981;1(3):239-246. McIsaac WJ, et al. CMAJ. 1998;158(1):75-83.',
                          example: { fields: { 'ce-exud': '1', 'ce-aden': '1', 'ce-fever': '1', 'ce-cough': '1', 'ce-age': '12' },
                                     expected: 'Centor 4; McIsaac 5 (high probability of GAS pharyngitis; consider testing or empiric treatment).' },
                          interpretation: {
                            bands: [
                              { range: '<=1 (McIsaac)', text: 'Low probability of GAS pharyngitis. No further testing or antibiotics per source.' },
                              { range: '2-3 (McIsaac)', text: 'Intermediate probability. Rapid antigen detection test or throat culture per source.' },
                              { range: '4-5 (McIsaac)', text: 'High probability of GAS pharyngitis. Empiric treatment may be considered per source; testing remains an option.' },
                            ],
                            sourceQuoted: true,
                            sourceCitation: 'McIsaac WJ, et al. CMAJ. 1998;158(1):75-83, Table 4 management bands.',
                          } },
  'wells-dvt-caprini':  { citation: 'Wells PS, et al. Lancet. 1997;350(9094):1795-1798 (Wells DVT). Caprini JA. Dis Mon. 2005;51(2-3):70-78.',
                          example: { fields: { 'wd-tender': '1', 'wd-leg': '1', 'wd-calf': '1', 'cap-pts': '5' },
                                     expected: 'Wells DVT 3 (High); Caprini 5 (high VTE risk).' } },
  bishop:               { citation: 'Bishop EH. Pelvic scoring for elective induction. Obstet Gynecol. 1964;24:266-268.',
                          example: { fields: { 'bp-d': '3', 'bp-e': '60', 'bp-s': '-1', 'bp-c': 'medium', 'bp-p': 'anterior' },
                                     expected: 'Bishop 9 (favorable; induction success likely).' } },
  'alvarado-pas':       { citation: 'Alvarado A. Ann Emerg Med. 1986;15(5):557-564 (MANTRELS). Samuel M. J Pediatr Surg. 2002;37(6):877-881 (PAS).',
                          example: { fields: { 'a-mig': '1', 'a-anx': '1', 'a-rlq': '1', 'a-wbc': '1', 'p-rlq': '1', 'p-mig': '1', 'p-wbc': '1' },
                                     expected: 'Alvarado 6 (compatible with appendicitis); PAS 5 (intermediate).' } },
  mrs:                  { citation: 'Modified Rankin Scale; UK-TIA Study Group 1988. Reference instrument; not auto-computed.' },
  phq9:                 { citation: 'Kroenke K, Spitzer RL, Williams JBW. PHQ-9. J Gen Intern Med. 2001;16(9):606-613.',
                          interpretation: {
                            bands: [
                              { range: '0-4',   text: 'None / minimal depression per source.' },
                              { range: '5-9',   text: 'Mild depression per source.' },
                              { range: '10-14', text: 'Moderate depression per source.' },
                              { range: '15-19', text: 'Moderately severe depression per source.' },
                              { range: '20-27', text: 'Severe depression per source.' },
                            ],
                            sourceQuoted: true,
                            sourceCitation: 'Kroenke K, et al. J Gen Intern Med. 2001;16(9):606-613, Table 4.',
                          } },
  gad7:                 { citation: 'Spitzer RL, et al. GAD-7. Arch Intern Med. 2006;166(10):1092-1097.',
                          interpretation: {
                            bands: [
                              { range: '0-4',   text: 'Minimal anxiety per source.' },
                              { range: '5-9',   text: 'Mild anxiety per source.' },
                              { range: '10-14', text: 'Moderate anxiety per source.' },
                              { range: '15-21', text: 'Severe anxiety per source.' },
                            ],
                            sourceQuoted: true,
                            sourceCitation: 'Spitzer RL, et al. Arch Intern Med. 2006;166(10):1092-1097.',
                          } },
  auditc:               { citation: 'Bush K, et al. AUDIT-C. Arch Intern Med. 1998;158(16):1789-1795.' },
  cage:                 { citation: 'Ewing JA. CAGE Questionnaire. JAMA. 1984;252(14):1905-1907.' },
  epds:                 { citation: 'Cox JL, Holden JM, Sagovsky R. EPDS. Br J Psychiatry. 1987;150:782-786.' },
  'mini-cog':           { citation: 'Borson S, et al. Mini-Cog. Int J Geriatr Psychiatry. 2000;15(11):1021-1027.',
                          example: { fields: { 'mc-w': '2', 'mc-clock': '1' },
                                     expected: 'Mini-Cog 4/5 - Negative for cognitive impairment screen.' } },

  // ---- Group G: v4 extensions waves 5-6 (utilities 157-160) ----
  ciwa:    { citation: 'Sullivan JT, et al. Assessment of alcohol withdrawal: the revised CIWA-Ar. Br J Addict. 1989;84(11):1353-1357.',
             example: { fields: { 'cw-nau': '2', 'cw-tre': '2', 'cw-swt': '2', 'cw-anx': '2', 'cw-agi': '1', 'cw-tac': '0', 'cw-aud': '0', 'cw-vis': '0', 'cw-hea': '1', 'cw-ori': '0' },
                        expected: 'CIWA-Ar 10 (moderate withdrawal, 8-15 band; symptom-triggered protocol typically considers active treatment).' },
             interpretation: {
               bands: [
                 { range: '0-9',   text: 'Minimal-to-mild alcohol withdrawal per source.' },
                 { range: '10-15', text: 'Moderate alcohol withdrawal per source.' },
                 { range: '16-19', text: 'Moderate-to-severe alcohol withdrawal per source.' },
                 { range: '>=20',  text: 'Severe alcohol withdrawal per source.' },
               ],
               sourceQuoted: true,
               sourceCitation: 'Sullivan JT, et al. Br J Addict. 1989;84(11):1353-1357; severity bands per Mayo-Smith MF. JAMA. 1997;278(2):144-151 expert consensus on symptom-triggered therapy.',
             } },
  cows:    { citation: 'Wesson DR, Ling W. The Clinical Opiate Withdrawal Scale (COWS). J Psychoactive Drugs. 2003;35(2):253-259.',
             example: { fields: { 'co-pul': '1', 'co-swt': '2', 'co-rest': '1', 'co-pup': '1', 'co-jt': '2', 'co-rn': '2', 'co-gi': '2', 'co-tre': '1', 'co-yaw': '1', 'co-anx': '2', 'co-goose': '0' },
                        expected: 'COWS 15 (moderate withdrawal).' },
             interpretation: {
               bands: [
                 { range: '5-12',  text: 'Mild opioid withdrawal per source.' },
                 { range: '13-24', text: 'Moderate opioid withdrawal per source.' },
                 { range: '25-36', text: 'Moderately severe opioid withdrawal per source.' },
                 { range: '>=37',  text: 'Severe opioid withdrawal per source.' },
               ],
               sourceQuoted: true,
               sourceCitation: 'Wesson DR, Ling W. J Psychoactive Drugs. 2003;35(2):253-259, scoring key on COWS form.',
             } },
  ascvd:   { citation: 'Goff DC Jr, et al. 2013 ACC/AHA Guideline on the Assessment of Cardiovascular Risk: Pooled Cohort Equations. Circulation. 2014;129(25 Suppl 2):S49-73. PCE retains race-stratified equations (white vs African-American).',
             example: { fields: { 'as-age': '55', 'as-tc': '213', 'as-hdl': '50', 'as-sbp': '120', 'as-sex': 'M', 'as-race': 'white' },
                        expected: 'ASCVD PCE ~5-7% 10-year risk (borderline to low risk; race/treated/smoke/dm modifiers shift the band).' } },
  prevent: { citation: 'Khan SS, et al. Development and Validation of the AHA PREVENT Equations. Circulation. 2024;149(6):430-449. PREVENT is race-FREE; differs from PCE on this point. Base 10-yr total CVD equation only (no statin / antihypertensive use, UACR, HbA1c, or SDI terms).',
             example: { fields: { 'pv-age': '55', 'pv-tc': '200', 'pv-hdl': '50', 'pv-sbp': '120', 'pv-bmi': '25', 'pv-egfr': '90', 'pv-sex': 'M' },
                        expected: 'PREVENT 10-year total CVD risk lands in the borderline / low band for a healthy 55-year-old.' } },

  // ---- Group H: Workflow ----
  prep:         { citation: 'Question scaffolds are derived from AHRQ "Questions to Ask Your Doctor" patient-engagement guides (Agency for Healthcare Research and Quality; ahrq.gov/questions).',
                  example: { fields: { visit: 'annual physical', topic: 'cholesterol' },
                             expected: 'Click "Generate questions" to render an AHRQ-derived list for the annual physical with cholesterol-related prompts.' } },
  'prior-auth': { citation: 'Field set follows the CMS Prior Authorization rule (CMS-0057-F, 89 FR 8758) and the AMA model prior-authorization request data fields. Generic checklist; payer-specific forms supersede.',
                  example: { fields: { proc: 'imaging-mri-msk' },
                             expected: 'Click "Generate checklist" to render the MRI musculoskeletal prior-authorization document set.' } },

  // ---- Group H: v4 extensions (utilities 161-165) ----
  'hipaa-auth':      { citation: 'HIPAA Privacy Rule, 45 CFR 164.508. Required-element template; covered entities may add their own elements.',
                       example: { fields: { 'ha-pt': 'Jane Doe', 'ha-plan': 'Acme Health Plan', 'ha-info': 'medical records 2024-2025', 'ha-rcpt': 'New Provider Internal Medicine', 'ha-purpose': 'continuity of care', 'ha-exp': '2027-05-15' },
                                  expected: 'Click "Build printable authorization" for a 45 CFR 164.508 letter listing patient, plan, info, recipient, purpose, and expiration.' } },
  roi:               { citation: 'Patient-authorized release of records. Many providers require their own ROI form; this template can be attached or used as the basis.',
                       example: { fields: { 'roi-pt': 'Jane Doe', 'roi-dob': '1985-03-12', 'roi-from': 'Acme Internal Medicine', 'roi-to': 'New Provider Internal Medicine', 'roi-dr': '2024-01-01 to 2025-01-01', 'roi-rec': 'office notes, labs, imaging', 'roi-del': 'secure email' },
                                  expected: 'Click "Build printable ROI request" to render a release-of-information letter.' } },
  'discharge-instr': { citation: 'Reference template only. Institutional discharge protocols and condition-specific guidelines govern the required content.',
                       example: { fields: { 'di-dx': 'Community-acquired pneumonia', 'di-fu': '2026-05-22 with PCP', 'di-rp': 'Fever > 102 F\nWorsening shortness of breath\nChest pain', 'di-meds': 'Amoxicillin 500 mg PO TID x 7 days', 'di-notes': 'Rest, hydration, complete the antibiotic course.' },
                                  expected: 'Click "Build printable discharge instructions" to render a discharge sheet with diagnosis, follow-up, return precautions, meds, and notes.' } },
  'specialty-visit': { citation: 'Generic per-specialty question banks compiled by the project author. Tailor to the visit.',
                       example: { fields: { 'sv-spec': 'cardiology', 'sv-ctx': 'palpitations workup' },
                                  expected: 'Click "Build printable question list" to render a cardiology-visit prep sheet.' } },
  'wallet-card':     { citation: 'Patient-maintained medication / health summary. Not a substitute for a pharmacist-reviewed list.',
                       example: { fields: { 'wc-name': 'Jane Doe', 'wc-ec': 'John Doe 555-0100', 'wc-pp': 'Acme Internal Medicine 555-0199', 'wc-rx': 'Acme Pharmacy 555-0150', 'wc-allergies': 'Penicillin', 'wc-conditions': 'Hypertension\nType 2 diabetes', 'wc-meds': 'Lisinopril 10 mg daily\nMetformin 500 mg BID' },
                                  expected: 'Click "Build printable wallet card" to render a folded reference card with allergies, conditions, meds, and contacts.' } },

  // ---- Group I: Field Medicine ----
  'peds-weight-dose': { citation: 'FDA labeling and standard prehospital pediatric resuscitation literature. Reference only.',
                        source: { dataset: 'prehospital-meds', label: 'FDA prehospital drug labeling subset' },
                        example: { fields: { 'pwd-w': '10', 'pwd-r': 'epinephrine-iv-io' }, expected: 'Epinephrine 0.1 mg IV/IO' } },
  'adult-arrest-ref': { citation: 'AHA ECC 2020 guidelines. Numeric reference only; flowcharts not reproduced.',
                        source: { dataset: 'aha-reference', label: 'AHA ECC numeric reference (no flowcharts)' } },
  'peds-arrest-ref':  { citation: 'AHA ECC 2020 guidelines. Numeric reference only; flowcharts not reproduced.',
                        source: { dataset: 'aha-reference', label: 'AHA ECC numeric reference (no flowcharts)' } },
  defib:              { citation: 'AHA ECC 2020 guidelines defibrillation energy ranges (numeric only).',
                        source: { dataset: 'aha-reference', label: 'AHA ECC numeric reference (no flowcharts)' },
                        example: { fields: { 'df-pop': 'adult', 'df-scn': 'vf-pvt', 'df-wave': 'biphasic', 'df-n': '1' }, expected: 'Adult biphasic VF/pVT: 120-200 J' } },
  cincinnati:         { citation: 'Kothari RU, Pancioli A, Liu T, Brott T, Broderick J. Cincinnati Prehospital Stroke Scale: reproducibility and validity. Acad Emerg Med. 1997;4(9):986-990.',
                        example: { fields: { 'cps-face': '1', 'cps-arm': '0', 'cps-speech': '0' }, expected: 'POSITIVE (1 of 3)' } },
  fast:               { citation: 'Kleindorfer DO, et al. Designing a message for public stroke education using the FAST mnemonic. Stroke. 2007;38(10):2864-2868. BE-FAST: Aroor S, Singh R, Goldstein LB. BE-FAST: reducing the proportion of strokes missed using the FAST mnemonic. Stroke. 2017;48(2):479-481.',
                        example: { fields: { 'fast-face': '1' }, expected: 'FAST: POSITIVE' } },

  'field-triage':     { citation: 'CDC. Guidelines for Field Triage of Injured Patients. MMWR Recommendations and Reports. Current edition.',
                        source: { dataset: 'field-triage', label: 'CDC Field Triage Guidelines' },
                        example: { fields: { 'ft-gcs-le-13': '1' }, expected: 'Highest-level trauma center (Step 1).' } },
  'start-triage':     { citation: 'Super G, et al. START: Simple Triage and Rapid Treatment. Newport Beach Fire Department / Hoag Hospital, 1983. Public-domain MCI triage protocol.',
                        source: { dataset: 'mci-triage', label: 'START / JumpSTART algorithm reference' },
                        example: { fields: { 'st-walk': '1' }, expected: 'Minor (green): patient can walk.' } },
  'jumpstart-triage': { citation: 'Romig LE. JumpSTART pediatric MCI triage tool. CHOC Children\'s Hospital. Public-domain pediatric variant of START.',
                        source: { dataset: 'mci-triage', label: 'START / JumpSTART algorithm reference' },
                        example: { fields: { 'js-walk': '1' }, expected: 'Minor (green): child can walk.' } },
  bsa_burn:           { citation: 'Lund CC, Browder NC. The estimation of areas of burns. Surg Gynecol Obstet. 1944;79:352-358. Rule of Nines: standard adult body-region distribution.',
                        example: { fields: { 'bb-method': 'nines', 'bb-n-trunk-anterior': '1' }, expected: 'TBSA 18% (anterior trunk only).' } },
  'burn-fluid':       { citation: 'Baxter CR, Shires T. Physiological response to crystalloid resuscitation of severe burns. Ann N Y Acad Sci. 1968;150(3):874-894 (Parkland). Reiss E, et al. Modified Brooke formula.',
                        example: { fields: { 'bf-w': '70', 'bf-bsa': '20', 'bf-h': '0' }, expected: 'Parkland 5600 mL/24h (2800 mL first 8h); Brooke 2800 mL/24h.' } },
  hypothermia:        { citation: 'Wilderness Medical Society guidelines and standard medical literature.',
                        source: { dataset: 'environmental', label: 'Environmental staging reference' } },
  'heat-illness':     { citation: 'Wilderness Medical Society guidelines and standard medical literature.',
                        source: { dataset: 'environmental', label: 'Environmental staging reference' } },
  'peds-ett':         { citation: 'Cuffed: age/4 + 3.5 mm. Uncuffed: age/4 + 4 mm. Depth at the lip = 3 x tube size in cm. Standard pediatric airway formulas; verify against bedside assessment.',
                        example: { fields: { 'pet-age': '4', 'pet-cuffed': 'uncuffed' }, expected: 'Tube 5.0 mm uncuffed, depth 15 cm.' } },
  toxidromes:         { citation: 'CDC ATSDR toxicological profiles and standard medical toxicology references; original brief notes by the project author.',
                        source: { dataset: 'toxidromes', label: 'ATSDR / CDC toxidrome reference' } },
  naloxone:           { citation: 'Naloxone HCl FDA labeling. CDC opioid overdose guidance. Repeat q2-3 min until adequate respirations.',
                        source: { dataset: 'prehospital-meds', label: 'FDA prehospital drug labeling subset' },
                        example: { fields: { 'nx-pop': 'adult', 'nx-route': 'in' }, expected: 'Initial: 4 mg intranasal (1 spray each nostril).' } },
  'ems-doc':          { citation: 'Templated workflow tool. Specific agency documentation requirements govern.',
                        example: { fields: { 'ed-rt': 'cardiac-arrest' },
                                   expected: 'Click "Generate checklist" to render the cardiac-arrest run-type documentation prompts.' } },

  // ---- Group I: v4 extensions (utilities 166-171) ----
  'nexus-cspine':   { citation: 'Hoffman JR, et al. NEXUS criteria. NEJM. 2000;343(2):94-99. Stiell IG, et al. Canadian C-Spine Rule. JAMA. 2001;286(15):1841-1848.',
                      example: { fields: { 'nx-tender': '1', 'nx-intox': '1', 'nx-alert': '1', 'nx-focal': '1', 'nx-distract': '1' },
                                 expected: 'All five low-risk criteria met -> NEXUS: cervical spine imaging NOT required.' } },
  'dot-erg':        { source: { dataset: 'dot-erg', label: 'PHMSA Emergency Response Guidebook' },
                      citation: 'US DOT PHMSA Emergency Response Guidebook (current edition). UN/NA-number lookups; isolation and protective-action distances per ERG green pages.' },
  'niosh-pg':       { source: { dataset: 'niosh-pg', label: 'CDC NIOSH Pocket Guide' },
                      citation: 'CDC NIOSH Pocket Guide to Chemical Hazards (NIOSH Publication 2005-149, current online release). Exposure limits, IDLH values, and PPE class per NIOSH.' },
  'cpr-numeric':    { source: { dataset: 'cpr-aha-numeric', label: 'AHA CPR/ECC numeric reference (numeric facts only)' },
                      citation: 'AHA CPR/ECC guidelines, current edition. Numeric values only; flowcharts not reproduced.' },
  tccc:             { source: { dataset: 'tccc', label: 'CoTCCC public guidelines' },
                      citation: 'Committee on Tactical Combat Casualty Care, public guidelines.' },
  'co-cn-antidote': { citation: 'FDA labeling: Cyanokit (hydroxocobalamin) and Nithiodote (sodium nitrite + sodium thiosulfate). UHMS guidance for HBO indications.' },

  // ---- Group J (NEW): Public Health & Travel (utilities 172-180) ----
  tetanus:          { source: { dataset: 'tetanus', label: 'CDC tetanus prophylaxis decision aid' },
                      citation: 'CDC tetanus prophylaxis recommendations (current edition).' },
  'rabies-pep':     { source: { dataset: 'rabies-pep', label: 'CDC rabies post-exposure prophylaxis decision aid' },
                      citation: 'CDC ACIP rabies PEP recommendations (current edition).' },
  'bbp-exposure':   { source: { dataset: 'bbp-exposure', label: 'CDC HIV/HBV/HCV bloodborne pathogen exposure recommendations' },
                      citation: 'CDC USPHS guidance for occupational and non-occupational HIV PEP; HBV/HCV exposure management.' },
  'tb-testing':     { source: { dataset: 'tb-tst-igra', label: 'CDC TB testing interpretation' },
                      citation: 'CDC TST cutoffs (5 / 10 / 15 mm) by risk category; IGRA interpretation.',
                      example: { fields: { 'tb-mm': '12', 'tb-risk': '10' },
                                 expected: 'TST: 12 mm vs cutoff 10 mm -> POSITIVE.' } },
  'sti-screening':  { source: { dataset: 'sti-screening', label: 'CDC STI Screening Recommendations' },
                      citation: 'CDC Sexually Transmitted Infections Treatment Guidelines, 2021 (MMWR Recomm Rep 2021;70(4):1-187) and current CDC screening recommendations by population.' },

  // ---- Group K (NEW): Lab Reference (utilities 181-184) ----
  'lab-adult':      { source: { dataset: 'lab-ranges-adult', label: 'NIH MedlinePlus adult lab reference ranges' },
                      citation: 'Reference ranges vary by lab; lab-specific ranges supersede.' },
  'lab-peds':       { source: { dataset: 'lab-ranges-peds', label: 'Pediatric lab reference ranges by age band' },
                      citation: 'Pediatric laboratory reference ranges by age band per Nelson Textbook of Pediatrics (current edition) and Harriet Lane Handbook (current edition). Lab-specific reference ranges supersede.' },
  'tdm-levels':     { source: { dataset: 'therapeutic-drug-levels', label: 'FDA labels via DailyMed - therapeutic drug levels' },
                      citation: 'Therapeutic drug monitoring target/peak/trough ranges per FDA-approved labeling (DailyMed) and standard pharmacology references. Institutional protocols and assay-specific ranges supersede.' },
  'tox-levels':     { source: { dataset: 'tox-levels', label: 'NLM WISER toxicology level reference' },
                      citation: 'Levels are stated as "associated with clinical toxicity per published references" - not treatment recommendations.' },

  // ---- Group L (NEW): Forms & Numbers Literacy (utilities 185-187) ----
  cms1500:          { source: { dataset: 'cms-1500-fields', label: 'CMS-1500 form (project-original plain-English summaries)' },
                      citation: 'CMS-1500 (02/12) Health Insurance Claim Form, OMB Control No. 0938-1197. The 02/12 revision is the current paper form in use since April 1, 2014; field labels are CMS-defined; plain-English summaries are by the project author.' },
  ub04:             { source: { dataset: 'ub04-fields', label: 'UB-04 form (project-original plain-English summaries)' },
                      citation: 'NUBC UB-04 (CMS-1450) institutional claim form, per the NUBC Official UB-04 Data Specifications. Field labels are NUBC-defined; plain-English summaries are by the project author.' },
  'eob-glossary':   { source: { dataset: 'eob-glossary', label: 'Project-original EOB jargon glossary' },
                      citation: 'Plain-English Explanation of Benefits glossary. Underlying terms map to X12 835 remittance fields and CMS / state EOB content requirements; original glossary entries by the project author.' },

  // ---- Group M (NEW): Eligibility & Benefits (utilities 188-191) ----

  // ---- Group N (NEW): Literacy Helpers (utilities 192-194) ----
  'unit-converter-v4': { citation: 'Standard SI <-> conventional conversion factors. NIH/NLM and IFCC references for HbA1c.',
                         example: { fields: { 'uc-cat': 'glucose', 'uc-v1': '90' }, expected: '90 mg/dL = 5.0 mmol/L' } },
  'time-to-dose':      { citation: 'Plain time math. Frequency abbreviations per standard pharmacy nomenclature.',
                         example: { fields: { 'td-time': '14:00', 'td-freq': 'q6h' },
                                    expected: 'Next four doses at 20:00, 02:00, 08:00, 14:00.' } },
  'peds-weight-conv':  { citation: '1 lb = 0.453592 kg. Reference newborn / infant weight bands per AAP.',
                         example: { fields: { 'pw-lb': '7', 'pw-oz': '5', 'pw-kg': '3.5' },
                                    expected: '7 lb 5 oz ~ 3.317 kg; 3.5 kg ~ 7 lb 11.5 oz.' } },

  // ---- Group O (NEW): Patient Safety (utilities 195-197) ----
  'high-alert-card':   { citation: 'Identities are factual. ISMP maintains the authoritative formatted high-alert medication list.' },

  // ---- spec-v5 §4: deterministic additions for the floor (T1-T17) ----
  'sodium-correction':  { citation: 'Adrogue HJ, Madias NE. Hyponatremia. NEJM 2000;342:1493-1499.',
                          example: { fields: { w: '70', sex: 'M', na: '110', infusate: '3pct-saline', tgt: '8' },
                                     expected: 'About 0.85 L of 3% saline over 24 h to raise Na by 8 mEq/L.' } },
  'free-water-deficit': { citation: 'Adrogue HJ, Madias NE. Hypernatremia. NEJM 2000;342:1493-1499.',
                          example: { fields: { w: '70', sex: 'M', na: '160', tgt: '145', hrs: '48' },
                                     expected: 'Free water deficit ~4.3 L; replace over 48 h.' } },
  'iron-ganzoni':       { citation: 'Ganzoni AM. Schweiz Med Wochenschr 1970;100:301-303.',
                          example: { fields: { w: '70', hb: '9', tgt: '15' },
                                     expected: 'Total iron deficit 1508 mg (1008 mg + 500 mg stores).' } },
  'pbw-ardsnet':        { citation: 'ARDSNet. Lower tidal volumes for ARDS. NEJM 2000;342:1301-1308. PBW per Devine 1974.',
                          example: { fields: { h: '175', sex: 'M', mlkg: '6' },
                                     expected: 'PBW ~70.5 kg, target Vt ~423 mL.' } },
  'rsbi':               { citation: 'Yang KL, Tobin MJ. RSBI. NEJM 1991;324:1445-1450.',
                          example: { fields: { rr: '24', vt: '350' },
                                     expected: 'RSBI 68.6 - likely to tolerate weaning (< 105).' } },
  'lights':             { citation: 'Light RW. Pleural effusion criteria. Ann Intern Med 1972;77:507-513.',
                          example: { fields: { pp: '4.0', sp: '6.0', pl: '250', sl: '200', uln: '222' },
                                     expected: 'Exudate (protein ratio 0.67 > 0.5).' } },
  'mentzer':            { citation: 'Mentzer WC. Lancet 1973;1:882.',
                          example: { fields: { mcv: '65', rbc: '6.0' },
                                     expected: 'Index ~10.8 - favors beta-thalassemia trait.' } },
  'saag':               { citation: 'Runyon BA. Hepatology 1992;16:240-245.',
                          example: { fields: { sa: '3.5', aa: '1.5' },
                                     expected: 'SAAG 2.0 g/dL - portal hypertension.' } },
  'r-factor':           { citation: 'Benichou C. CIOMS classification. J Hepatol 1990;11:272-276.',
                          example: { fields: { alt: '500', altu: '40', alp: '100', alpu: '120' },
                                     expected: 'Hepatocellular pattern (R = 15).' } },
  'kdigo-aki':          { citation: 'KDIGO Clinical Practice Guideline for Acute Kidney Injury. Kidney Int Suppl 2012;2:1-138.',
                          example: { fields: { base: '1.0', cur: '3.5' },
                                     expected: 'KDIGO AKI Stage 3 (3.5x baseline).' } },
  'sgarbossa':          { citation: 'Smith SW et al. Modified Sgarbossa criteria. Ann Emerg Med 2012;60:766-776.',
                          example: { fields: { a: '1' }, expected: 'Positive (concordant ST elevation >=1 mm in at least one lead).' } },
  'rcri':               { citation: 'Lee TH et al. Revised Cardiac Risk Index. Circulation 1999;100:1043-1049.',
                          example: { fields: { highRiskSurgery: '1', ischemicHeartDisease: '1' },
                                     expected: 'RCRI 2 factors -> ~6.6% major cardiac event risk (Class III per Lee 1999).' } },
  'pews':               { citation: 'Monaghan A. Detecting and managing deterioration in children. Paediatr Nurs 2005;17:32-35.',
                          example: { fields: { Behavior: '2', Cardiovascular: '2', Respiratory: '1' },
                                     expected: 'Total 5 - Escalate: bedside provider review.' } },
  'em-time':            { citation: 'AMA CPT 2021 office/outpatient E/M time bands. Code descriptors are AMA-owned and not bundled.',
                          example: { fields: { enc: 'new', t: '45' }, expected: 'Code 99204 (45 min, new patient; AMA 2021 bands).' } },
  'ndc-convert':        { citation: 'CMS NDC billing guidance (5-4-2 billing format) and FDA Structured Product Labeling.',
                          example: { fields: { n: '1234-5678-90' }, expected: 'Billing 11: 01234-5678-90 / FDA 10: 1234-5678-90.' } },
  'avpu-gcs':           { citation: 'McNarry AF, Goldhill DR. Comparison of AVPU and GCS. Anaesthesia 2004;59:34-37.',
                          example: { fields: { lvl: 'P' }, expected: 'P -> typical GCS 8 (range 7-9).' } },
  'sbar-template':      { citation: 'Institute for Healthcare Improvement (IHI) SBAR communication toolkit.',
                          example: { fields: { s: 'Mrs. Chen in 412B, post-op day 1, complaining of chest pressure.', b: '68F, CABG yesterday, hx HTN/DM, on aspirin / atorvastatin.', a: 'Vitals stable but new ST changes on telemetry; concerned for ischemia.', r: 'Request bedside evaluation, repeat ECG, troponin.' },
                                     expected: 'Pre-formatted SBAR ready to copy.' } },

  // ---- spec-v6 §1: HIPAA + corrected AG ----
  'corrected-anion-gap': {
    citation: 'Figge J, Jabor A, Kazda A, Fencl V. Anion gap and hypoalbuminemia. Crit Care Med 1998;26(11):1807-1810. AG correction = +2.5 mEq/L per 1 g/dL drop in albumin from 4.0.',
    example: { fields: { na: '140', cl: '106', hco3: '24', alb: '2.0' },
               expected: 'Measured AG 10 (looks normal); corrected AG 15 (elevated -- consider HAGMA workup).' },
  },
  'breach-clock': {
    citation: 'HIPAA Breach Notification Rule, 45 CFR §§164.404, 164.406, 164.408. Individual + media + HHS deadlines computed from the discovery date.',
    example: { fields: { d: '2026-03-15', n: '600' },
               expected: 'Discovery 2026-03-15, >=500 affected: individual + media + HHS notice all due 2026-05-14.' },
  },
  'abcd2': {
    citation: 'Johnston SC, Rothwell PM, Nguyen-Huynh MN, et al. Validation and refinement of scores to predict very early stroke risk after transient ischaemic attack. Lancet 2007;369(9558):283-292.',
    example: { fields: { age: '70', sbp: '150', dbp: '90', clin: 'weakness', dur: '90', diab: '1' },
               expected: 'ABCD2 7/7 - High risk (2-day stroke risk ~8.1%).' },
    interpretation: {
      bands: [
        { range: '0-3', text: 'Low risk; 2-day stroke risk 1.0% per source.' },
        { range: '4-5', text: 'Moderate risk; 2-day stroke risk 4.1% per source.' },
        { range: '6-7', text: 'High risk; 2-day stroke risk 8.1% per source.' },
      ],
      sourceQuoted: true,
      sourceCitation: 'Johnston SC, et al. Lancet 2007;369(9558):283-292, Table 3.',
    },
  },

  // ---- spec-v12 §3.1 wave 12-1: early-warning bundle ----
  news2: {
    citation: 'Royal College of Physicians. National Early Warning Score (NEWS) 2: Standardising the assessment of acute-illness severity in the NHS - Updated report of a working party. London: RCP, 2017.',
    specialties: ['nursing-general', 'emergency-medicine', 'critical-care', 'pulmonology'],
    example: {
      fields: { 'n2-rr': '14', 'n2-spo2': '98', 'n2-scale2': '0', 'n2-o2': '0', 'n2-sbp': '124', 'n2-pulse': '78', 'n2-acvpu': 'A', 'n2-temp': '37.0' },
      expected: 'NEWS2 0 - Low band (continue routine monitoring per RCP 2017 Table 2).',
    },
    interpretation: {
      bands: [
        { range: '0', text: 'Minimum 12-hourly monitoring; continue routine monitoring per RCP 2017 Table 2.' },
        { range: '1-4', text: 'Minimum 4-6-hourly monitoring; registered nurse assesses whether escalation is required per RCP 2017 Table 2.' },
        { range: 'single parameter scoring 3', text: 'Minimum 1-hourly monitoring; urgent review by clinician with competencies in acute illness per RCP 2017 Table 2.' },
        { range: '>=5', text: 'Minimum 1-hourly monitoring; urgent review and consider continuous monitoring and critical-care review per RCP 2017 Table 2.' },
        { range: '>=7', text: 'Continuous monitoring; emergency assessment by critical-care team; usually transfer to higher-acuity area per RCP 2017 Table 2.' },
      ],
      sourceQuoted: true,
      sourceCitation: 'Royal College of Physicians. NEWS2. London: RCP, 2017, Table 2.',
    },
  },
  mews: {
    citation: 'Subbe CP, Kruger M, Rutherford P, Gemmel L. Validation of a modified Early Warning Score in medical admissions. QJM. 2001;94(10):521-526.',
    specialties: ['nursing-general', 'emergency-medicine', 'critical-care'],
    example: {
      fields: { 'me-sbp': '120', 'me-pulse': '78', 'me-rr': '14', 'me-temp': '37.0', 'me-avpu': 'A' },
      expected: 'MEWS 0 - low band (0-2) per Subbe 2001 Table 2.',
    },
    interpretation: {
      bands: [
        { range: '0-2', text: 'Low risk band per Subbe 2001 Table 2.' },
        { range: '3', text: 'Low-intermediate risk band per Subbe 2001 Table 2.' },
        { range: '4', text: 'Intermediate risk band per Subbe 2001 Table 2.' },
        { range: '>=5', text: 'Increased risk of death, ICU admission, and HDU admission per Subbe 2001 Table 2.' },
      ],
      sourceQuoted: true,
      sourceCitation: 'Subbe CP, et al. QJM. 2001;94(10):521-526, Table 2.',
    },
  },

  // ---- spec-v12 §3.2 wave 12-2: VTE risk & severity bundle ----
  pesi: {
    citation: 'Aujesky D, Obrosky DS, Stone RA, et al. Derivation and validation of a prognostic model for pulmonary embolism. Am J Respir Crit Care Med. 2005;172(8):1041-1046.',
    specialties: ['pulmonology', 'emergency-medicine', 'cardiology', 'critical-care'],
    example: {
      fields: { 'pe-age': '50', 'pe-sex': 'F', 'pe-hr': '0', 'pe-sbp': '0', 'pe-rr': '0', 'pe-tmp': '0', 'pe-ams': '0', 'pe-sao2': '0', 'pe-ca': '0', 'pe-hf': '0', 'pe-cld': '0' },
      expected: 'PESI 50 - Class I (very low risk; 30-day mortality 0.0-1.6% per Aujesky 2005 Table 4).',
    },
    interpretation: {
      bands: [
        { range: 'I (<=65)', text: '30-day mortality 0.0-1.6% per Aujesky 2005 Table 4 (Class I).' },
        { range: 'II (66-85)', text: '30-day mortality 1.7-3.5% per Aujesky 2005 Table 4 (Class II).' },
        { range: 'III (86-105)', text: '30-day mortality 3.2-7.1% per Aujesky 2005 Table 4 (Class III).' },
        { range: 'IV (106-125)', text: '30-day mortality 4.0-11.4% per Aujesky 2005 Table 4 (Class IV).' },
        { range: 'V (>125)', text: '30-day mortality 10.0-24.5% per Aujesky 2005 Table 4 (Class V).' },
      ],
      sourceQuoted: true,
      sourceCitation: 'Aujesky D, et al. Am J Respir Crit Care Med. 2005;172(8):1041-1046, Table 4.',
    },
  },
  spesi: {
    citation: 'Jimenez D, Aujesky D, Moores L, et al. Simplification of the pulmonary embolism severity index for prognostication in patients with acute symptomatic pulmonary embolism. Arch Intern Med. 2010;170(15):1383-1389.',
    specialties: ['pulmonology', 'emergency-medicine', 'cardiology'],
    example: {
      fields: { 'sp-age80': '0', 'sp-ca': '0', 'sp-ccp': '0', 'sp-hr': '0', 'sp-sbp': '0', 'sp-sao2': '0' },
      expected: 'sPESI 0 - low risk; 30-day all-cause mortality 1.0% per Jimenez 2010 Table 3.',
    },
    interpretation: {
      bands: [
        { range: '0', text: 'Low risk; 30-day all-cause mortality 1.0% per Jimenez 2010 Table 3.' },
        { range: '>=1', text: 'Not-low risk; 30-day all-cause mortality 10.9% per Jimenez 2010 Table 3.' },
      ],
      sourceQuoted: true,
      sourceCitation: 'Jimenez D, et al. Arch Intern Med. 2010;170(15):1383-1389, Table 3.',
    },
  },
  padua: {
    citation: 'Barbar S, Noventa F, Rossetto V, et al. A risk assessment model for the identification of hospitalized medical patients at risk for venous thromboembolism: the Padua Prediction Score. J Thromb Haemost. 2010;8(11):2450-2457.',
    specialties: ['hematology', 'nursing-general', 'geriatrics'],
    example: {
      fields: { 'pa-ca': '0', 'pa-vte': '0', 'pa-mob': '0', 'pa-thr': '0', 'pa-trauma': '0', 'pa-age': '0', 'pa-hf': '0', 'pa-mi': '0', 'pa-inf': '0', 'pa-bmi': '0', 'pa-horm': '0' },
      expected: 'Padua 0 - low risk; 90-day VTE 0.3% without prophylaxis per Barbar 2010 Table 4.',
    },
    interpretation: {
      bands: [
        { range: '<4', text: 'Low risk; 90-day VTE 0.3% without prophylaxis per Barbar 2010 Table 4.' },
        { range: '>=4', text: 'High risk; 90-day VTE 11.0% if untreated per Barbar 2010 Table 4. Prophylaxis-eligible per Barbar 2010 Results.' },
      ],
      sourceQuoted: true,
      sourceCitation: 'Barbar S, et al. J Thromb Haemost. 2010;8(11):2450-2457, Table 4.',
    },
  },

  // ---- spec-v12 §3.3 wave 12-3: upper & lower GI-bleeding bundle ----
  gbs: {
    citation: 'Blatchford O, Murray WR, Blatchford M. A risk score to predict need for treatment for upper-gastrointestinal haemorrhage. Lancet. 2000;356(9238):1318-1321.',
    specialties: ['gastroenterology', 'emergency-medicine', 'hematology'],
    example: {
      fields: { 'gb-bun': '14', 'gb-hgb': '15', 'gb-sex': 'M', 'gb-sbp': '120', 'gb-pulse': '0', 'gb-mel': '0', 'gb-syn': '0', 'gb-hep': '0', 'gb-cf': '0' },
      expected: 'GBS 0 - low risk; can be considered for outpatient management per Blatchford 2000 §Results (cutoff endorsed by NICE CG141 2012).',
    },
    interpretation: {
      bands: [
        { range: '0', text: 'Low risk; can be considered for outpatient management per Blatchford 2000 §Results.' },
        { range: '>=1', text: 'Not in the Blatchford 2000 low-risk group; inpatient assessment per source.' },
      ],
      sourceQuoted: true,
      sourceCitation: 'Blatchford O, et al. Lancet. 2000;356(9238):1318-1321, Table 1 (weights) and §Results (outpatient-management cutoff endorsed by NICE CG141 2012).',
    },
  },
  rockall: {
    citation: 'Rockall TA, Logan RFA, Devlin HB, Northfield TC. Risk assessment after acute upper gastrointestinal haemorrhage. Gut. 1996;38(3):316-321.',
    specialties: ['gastroenterology', 'emergency-medicine'],
    example: {
      fields: { 'rk-age': '0', 'rk-shock': '0', 'rk-co': '0', 'rk-dx': '0', 'rk-stig': '0', 'rk-pre': '0' },
      expected: 'Complete Rockall 0 - low risk; mortality 0.1-0.4% per Rockall 1996 Figure 2.',
    },
    interpretation: {
      bands: [
        { range: '0-2', text: 'Low risk; mortality 0.1-0.4% per Rockall 1996 Figure 2.' },
        { range: '3-4', text: 'Intermediate risk; mortality 5.3-11.2% per Rockall 1996 Figure 2.' },
        { range: '5-7', text: 'High risk; mortality 24.6-39.6% per Rockall 1996 Figure 2.' },
        { range: '8+', text: 'Very high risk; mortality >=40% per Rockall 1996 Figure 2.' },
      ],
      sourceQuoted: true,
      sourceCitation: 'Rockall TA, et al. Gut. 1996;38(3):316-321, Figure 2. Pre-endoscopy variant per Vreeburg EM, et al. Gastroenterology. 1999/NICE CG141 endorsement.',
    },
  },
  aims65: {
    citation: 'Saltzman JR, Tabak YP, Hyett BH, Sun X, Travis AC, Johannes RS. A simple risk score accurately predicts in-hospital mortality, length of stay, and cost in acute upper GI bleeding. Gastrointest Endosc. 2011;74(6):1215-1224.',
    specialties: ['gastroenterology', 'emergency-medicine'],
    example: {
      fields: { 'am-alb': '0', 'am-inr': '0', 'am-am': '0', 'am-sbp': '0', 'am-age': '0' },
      expected: 'AIMS65 0 - in-hospital mortality 0.3% per Saltzman 2011 Table 4.',
    },
    interpretation: {
      bands: [
        { range: '0', text: 'In-hospital mortality 0.3% per Saltzman 2011 Table 4.' },
        { range: '1', text: 'In-hospital mortality 1.2% per Saltzman 2011 Table 4.' },
        { range: '2', text: 'In-hospital mortality 5.3% per Saltzman 2011 Table 4.' },
        { range: '3', text: 'In-hospital mortality 10.3% per Saltzman 2011 Table 4.' },
        { range: '4', text: 'In-hospital mortality 16.5% per Saltzman 2011 Table 4.' },
        { range: '5', text: 'In-hospital mortality 24.5% per Saltzman 2011 Table 4.' },
      ],
      sourceQuoted: true,
      sourceCitation: 'Saltzman JR, et al. Gastrointest Endosc. 2011;74(6):1215-1224, Table 4.',
    },
  },
  oakland: {
    citation: 'Oakland K, Jairath V, Uberoi R, et al. Derivation and validation of a novel risk score for safe discharge after acute lower gastrointestinal bleeding: a modelling study. Lancet Gastroenterol Hepatol. 2017;2(9):635-643.',
    specialties: ['gastroenterology', 'emergency-medicine'],
    example: {
      fields: { 'ok-age': '35', 'ok-sex': 'F', 'ok-prior': '0', 'ok-dre': '0', 'ok-hr': '65', 'ok-sbp': '165', 'ok-hgb': '17' },
      expected: 'Oakland 0 - safe for outpatient management (95% probability of safe discharge per Oakland 2017; cutoff endorsed by BSG 2019).',
    },
    interpretation: {
      bands: [
        { range: '<=8', text: 'Safe for outpatient management; 95% probability of safe discharge per Oakland 2017 (cutoff endorsed by BSG 2019).' },
        { range: '>8', text: 'Not in the safe-discharge band; inpatient assessment per Oakland 2017.' },
      ],
      sourceQuoted: true,
      sourceCitation: 'Oakland K, et al. Lancet Gastroenterol Hepatol. 2017;2(9):635-643, Table 2 (weights) and Figure 3 (<=8 safe-discharge cutoff endorsed by BSG 2019).',
    },
  },

  // ---- spec-v12 §3.4 wave 12-4: hepatology & liver-fibrosis bundle ----
  fib4: {
    citation: 'Sterling RK, Lissen E, Clumeck N, et al. Development of a simple noninvasive index to predict significant fibrosis in patients with HIV/HCV coinfection. Hepatology. 2006;43(6):1317-1325.',
    specialties: ['hepatology', 'gastroenterology', 'infectious-disease'],
    example: {
      fields: { 'fib4-age': '55', 'fib4-ast': '60', 'fib4-alt': '40', 'fib4-plt': '150' },
      expected: 'FIB-4 3.48 - rules in advanced fibrosis (PPV 65% per Sterling 2006).',
    },
    interpretation: {
      bands: [
        { range: '<1.45', text: 'Rules out advanced fibrosis (NPV 90% per Sterling 2006).' },
        { range: '1.45-3.25', text: 'Indeterminate; consider further evaluation per Sterling 2006.' },
        { range: '>3.25', text: 'Rules in advanced fibrosis (PPV 65% per Sterling 2006).' },
      ],
      sourceQuoted: true,
      sourceCitation: 'Sterling RK, et al. Hepatology. 2006;43(6):1317-1325, Table 4 (cutoffs).',
    },
  },
  apri: {
    citation: 'Wai CT, Greenson JK, Fontana RJ, et al. A simple noninvasive index can predict both significant fibrosis and cirrhosis in patients with chronic hepatitis C. Hepatology. 2003;38(2):518-526.',
    specialties: ['hepatology', 'gastroenterology', 'infectious-disease'],
    example: {
      fields: { 'apri-ast': '60', 'apri-uln': '40', 'apri-plt': '150' },
      expected: 'APRI 1.00 - predicts significant fibrosis per Wai 2003 (WHO 2014 HCV guideline endorsement).',
    },
    interpretation: {
      bands: [
        { range: '<=0.7', text: 'Below the Wai 2003 significant-fibrosis cutoff.' },
        { range: '>0.7', text: 'Predicts significant fibrosis per Wai 2003 (WHO 2014 HCV guideline endorsement).' },
        { range: '>1.0', text: 'Predicts cirrhosis per Wai 2003 (WHO 2014 HCV guideline endorsement).' },
      ],
      sourceQuoted: true,
      sourceCitation: 'Wai CT, et al. Hepatology. 2003;38(2):518-526, Table 4 (cutoffs); WHO 2014 HCV guideline endorsement for resource-limited settings.',
    },
  },
  'maddrey-lille': {
    citation: 'Maddrey WC, et al. Corticosteroid therapy of alcoholic hepatitis. Gastroenterology. 1978;75(2):193-199. Lille model: Louvet A, et al. Hepatology. 2007;45(6):1348-1354.',
    specialties: ['hepatology', 'gastroenterology', 'critical-care'],
    example: {
      fields: { 'ml-pt': '20', 'ml-ctrl': '12', 'ml-bili': '10', 'ml-age': '50', 'ml-alb': '3.0', 'ml-cr': '0.9', 'ml-b0': '10', 'ml-b7': '6', 'ml-ptl': '20' },
      expected: 'Maddrey DF 46.8 - severe alcoholic hepatitis per Maddrey 1978 §Results; Lille model also computed.',
    },
    interpretation: {
      bands: [
        { range: 'DF <32', text: 'Not in the severe alcoholic hepatitis band per Maddrey 1978 §Results.' },
        { range: 'DF >=32', text: 'Severe alcoholic hepatitis per Maddrey 1978 §Results; corticosteroid therapy commonly considered.' },
        { range: 'Lille <0.45', text: 'Predicts response to steroids (6-month survival ~85% per Louvet 2007).' },
        { range: 'Lille >=0.45', text: 'Predicts non-response to steroids (6-month survival ~25% per Louvet 2007).' },
      ],
      sourceQuoted: true,
      sourceCitation: 'Maddrey WC, et al. Gastroenterology. 1978;75(2):193-199 (DF formula and >=32 cutoff). Louvet A, et al. Hepatology. 2007;45(6):1348-1354 (Lille equation and 0.45 cutoff).',
    },
  },

  // ---- spec-v6 §3.3: lab result interpreter ----
  'lab-interpret': {
    citation: 'Reference ranges per MedlinePlus, ARUP, Harrison\'s Principles of Internal Medicine (21e), ADA 2024 Standards of Care, 2018 ACC/AHA Cholesterol Guideline, and ATA 2014. Plain-English narratives by the project author.',
    example: { fields: { 'lab-a1c': '5.4' },
               expected: 'A1C 5.4% within range (4.0-5.6%).' },
  },
};
