// spec-v864: reading a methemoglobin level, and the two tests that lie about it.
//
// Sources:
//   Wright RO, Lewander WJ, Woolf AD. Methemoglobinemia: etiology, pharmacology, and clinical
//   management. Ann Emerg Med. 1999;34(5):646-656.
//   Skold A, Cosco DL, Klein R. Methemoglobinemia: pathogenesis, diagnosis, and management.
//   South Med J. 2011;104(11):757-761.
//
//     under 3%     within the range seen normally
//     3-15%        often little more than discoloration
//     15-20%       cyanosis; blood is chocolate-brown and does not redden in air
//     20-50%       headache, fatigue, dizziness, breathlessness
//     50-70%       seizures, arrhythmia, coma, metabolic acidosis
//     over 70%     often fatal
//
//   Methylene blue is given for symptoms, or at 30% and above without them.
//
// PULSE OXIMETRY AND THE BLOOD GAS BOTH LIE, AND THAT IS WHY THIS TILE EXISTS. A pulse oximeter
// reads two wavelengths and methemoglobin absorbs at both, so the reading drifts toward roughly
// 85% and stops there however high the level goes. The arterial PaO2 is NORMAL, because it
// measures oxygen dissolved in plasma and says nothing about what the hemoglobin can carry.
// Only co-oximetry measures methemoglobin. The gap between a co-oximeter saturation and a pulse
// oximeter reading is the finding.
//
// METHYLENE BLUE IN G6PD DEFICIENCY. It works through NADPH from the pentose phosphate pathway,
// so in G6PD deficiency it does not reduce the methemoglobin and it can cause hemolysis.
//
// METHYLENE BLUE IS A MONOAMINE OXIDASE INHIBITOR, and it has precipitated serotonin toxicity in
// patients on serotonergic drugs.
//
// Pure: no DOM, no clock, no network.

export const METHB_NOTE = 'Methemoglobin is hemoglobin whose iron has been oxidized so that it cannot carry oxygen, and it also shifts the remaining hemoglobin so that it releases oxygen less readily. Levels under about 3 percent are within the range seen normally; 3 to 15 percent often produces little more than discoloration; 15 to 20 percent produces cyanosis with blood that is chocolate-brown and does not redden on exposure to air; 20 to 50 percent produces headache, fatigue, dizziness and breathlessness; 50 to 70 percent produces seizures, arrhythmia, coma and metabolic acidosis; and over 70 percent is often fatal. Methylene blue is given for symptoms, or at 30 percent and above without them. Two routine tests lie about this diagnosis. A pulse oximeter reads two wavelengths and methemoglobin absorbs at both, so its reading drifts toward roughly 85 percent and stops there however high the level climbs, which means a falling oximeter that will not correct on oxygen is a clue rather than a reassurance. The arterial blood gas is worse: the measured oxygen tension is normal, because it reports oxygen dissolved in plasma and says nothing about what the hemoglobin can carry, and a saturation calculated from it will look normal too. Only co-oximetry measures methemoglobin, and the gap between a co-oximeter saturation and a pulse oximeter reading is itself the finding. Two things about the antidote matter as much as the level. Methylene blue works through NADPH generated by the pentose phosphate pathway, so in glucose-6-phosphate dehydrogenase deficiency it does not reduce the methemoglobin and it can cause hemolysis. And methylene blue is a monoamine oxidase inhibitor that has precipitated serotonin toxicity in patients taking serotonergic drugs. It reads a measured level against published bands. It does not prescribe methylene blue, set a dose, or replace the regional poison center.';

function num(v) {
  if (v === null || v === undefined || v === '') return null;
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
}

function on(v) {
  return v === true || v === 'true' || v === 'yes' || v === 1 || v === '1';
}

const BANDS = [
  { max: 3, label: 'within the range seen normally', effect: 'No effect is expected at this level.' },
  { max: 15, label: 'a low level', effect: 'Often little more than discoloration at this level.' },
  { max: 20, label: 'a level that produces cyanosis', effect: 'Cyanosis, with blood that is chocolate-brown and does not redden on exposure to air.' },
  { max: 50, label: 'a symptomatic level', effect: 'Headache, fatigue, dizziness and breathlessness are expected in this range.' },
  { max: 70, label: 'a severe level', effect: 'Seizures, arrhythmia, coma and metabolic acidosis are described in this range.' },
  { max: Infinity, label: 'a level that is often fatal', effect: 'Levels above 70 percent are often fatal.' },
];

const TREAT_WITHOUT_SYMPTOMS = 30;
const OXIMETER_PLATEAU = 85;

export function methemoglobin(input = {}) {
  const o = input && typeof input === 'object' ? input : {};

  const level = num(o.level);
  if (level === null) {
    return { valid: false, message: 'Enter the methemoglobin level as a percentage, measured by co-oximetry.' };
  }
  if (level < 0 || level > 100) {
    return { valid: false, message: 'The methemoglobin level is outside its range of 0 to 100 percent.' };
  }
  const spo2 = num(o.spo2);
  if (spo2 !== null && (spo2 < 0 || spo2 > 100)) {
    return { valid: false, message: 'The pulse oximeter reading is outside its range of 0 to 100 percent.' };
  }
  const pao2 = num(o.pao2);
  if (pao2 !== null && (pao2 < 0 || pao2 > 700)) {
    return { valid: false, message: 'The arterial oxygen tension is outside a plausible range of 0 to 700 mmHg.' };
  }

  const symptoms = on(o.symptoms);
  const g6pd = on(o.g6pd);
  const serotonergic = on(o.serotonergic);

  const graded = BANDS.find((b) => level < b.max);
  const treatmentIndicated = symptoms || level >= TREAT_WITHOUT_SYMPTOMS;

  const state = `${level} percent, ${graded.label}`;

  const treatmentNote = treatmentIndicated
    ? (symptoms
      ? `Symptoms were entered, and methylene blue is given for symptoms whatever the level. At ${level} percent that indication stands on the symptoms.`
      : `At ${level} percent, which is ${TREAT_WITHOUT_SYMPTOMS} percent or above, methylene blue is given even without symptoms.`)
    : `At ${level} percent with no symptoms entered, this is below the ${TREAT_WITHOUT_SYMPTOMS} percent at which methylene blue is given in the absence of symptoms. Removing the oxidizing agent is the first step at any level.`;

  // The two tests that lie. Stated on every result, because the reassurance is the harm.
  const oximeterNote = spo2 !== null
    ? `A pulse oximeter reading of ${spo2} percent does not measure this. The oximeter reads two wavelengths and methemoglobin absorbs at both, so the reading drifts toward about ${OXIMETER_PLATEAU} percent and stops there however high the level climbs. It does not correct on oxygen.`
    : `A pulse oximeter does not measure this. It reads two wavelengths and methemoglobin absorbs at both, so the reading drifts toward about ${OXIMETER_PLATEAU} percent and stops there however high the level climbs, and it does not correct on oxygen.`;

  const gasNote = pao2 !== null
    ? `An arterial oxygen tension of ${pao2} mmHg says nothing about this. It measures oxygen dissolved in plasma, not what the hemoglobin can carry, so it is normal in methemoglobinemia and a saturation calculated from it is normal too. Only co-oximetry measures methemoglobin.`
    : 'The arterial oxygen tension is normal in methemoglobinemia, because it measures oxygen dissolved in plasma rather than what the hemoglobin can carry, and a saturation calculated from it is normal too. Only co-oximetry measures methemoglobin.';

  const carrying = Math.round((100 - level) * 10) / 10;
  const gap = spo2 !== null ? Math.round((spo2 - carrying) * 10) / 10 : null;
  const gapNote = spo2 !== null && level >= 3
    ? (gap > 0
      ? `The pulse oximeter reads ${spo2} percent while only ${carrying} percent of the hemoglobin can carry oxygen, so it is over-reading by ${gap} percentage points. That gap is the finding, and it widens as the level climbs because the oximeter stops near ${OXIMETER_PLATEAU} percent while the true fraction keeps falling.`
      : `The pulse oximeter reads ${spo2} percent against ${carrying} percent of the hemoglobin able to carry oxygen. The oximeter is not over-reading here, but it still cannot measure the level: it stops near ${OXIMETER_PLATEAU} percent, so it will over-read as soon as the true fraction falls below that.`)
    : null;

  const g6pdNote = g6pd && treatmentIndicated
    ? 'Methylene blue works through NADPH from the pentose phosphate pathway. In G6PD deficiency it does not reduce the methemoglobin, and it can cause hemolysis. This is the contraindication that matters most here.'
    : g6pd
      ? 'G6PD deficiency was entered. Methylene blue would not work here and could cause hemolysis, so it matters before any decision to give it.'
      : treatmentIndicated
        ? 'G6PD status was not entered. Methylene blue works through NADPH from the pentose phosphate pathway, so in G6PD deficiency it does not reduce the methemoglobin and can cause hemolysis.'
        : null;

  const serotonergicNote = serotonergic && treatmentIndicated
    ? 'Methylene blue is a monoamine oxidase inhibitor and has precipitated serotonin toxicity in patients taking serotonergic drugs. That does not by itself withhold it in a life-threatening case, but it is weighed.'
    : null;

  const scopeNote = 'This reads a measured level against published bands. It does not prescribe methylene blue, set a dose, or replace the regional poison center.';

  return {
    valid: true,
    level,
    spo2,
    pao2,
    symptoms,
    g6pd,
    serotonergic,
    effect: graded.effect,
    treatmentIndicated,
    oxygenCarrying: carrying,
    gap,
    state,
    treatmentNote,
    oximeterNote,
    gasNote,
    gapNote,
    g6pdNote,
    serotonergicNote,
    scopeNote,
    abnormal: level >= 3,
    bandLabel: graded.label.charAt(0).toUpperCase() + graded.label.slice(1),
    band: `Methemoglobin ${state}.`,
    detail: `Under 3 percent is within the range seen normally; 3 to 15 percent often produces little more than discoloration; 15 to 20 percent produces cyanosis; 20 to 50 percent produces headache, fatigue, dizziness and breathlessness; 50 to 70 percent produces seizures, arrhythmia, coma and acidosis; and over 70 percent is often fatal. Methylene blue is given for symptoms, or at ${TREAT_WITHOUT_SYMPTOMS} percent and above without them.`,
    note: METHB_NOTE,
  };
}
