// spec-v4 §6: shared printable-template renderer.
//
// Config: { title, sections: [{ heading, paragraphs?: [string], items?: [string] }],
//           warnings?: [string] }

import { el, clear } from './dom.js';

// --- Pure helpers ---

export function validateSections(sections) {
  if (!Array.isArray(sections)) throw new TypeError('sections must be an array');
  for (const s of sections) {
    if (!s || typeof s !== 'object') throw new TypeError('section must be an object');
    if (!s.heading) throw new TypeError('section missing heading');
    if (s.paragraphs && !Array.isArray(s.paragraphs)) throw new TypeError('paragraphs must be an array');
    if (s.items && !Array.isArray(s.items)) throw new TypeError('items must be an array');
  }
  return true;
}

// --- Render ---

export function renderPrintable(rootEl, config) {
  const { title, sections, warnings = [] } = config;
  validateSections(sections);
  clear(rootEl);

  const article = el('article', { class: 'printable' });

  const header = el('header', { class: 'printable-header' });
  // Use h2 here so the page only has one h1 (the route's tool name). Multiple
  // h1s per document is a recurring axe/Lighthouse warning and confuses
  // screen-reader heading navigation. WCAG 2.1 SC 1.3.1 + WAI heading guidance.
  header.appendChild(el('h2', { text: title || '' }));
  article.appendChild(header);

  for (const w of warnings) {
    article.appendChild(el('p', { class: 'printable-warning', role: 'note', text: w }));
  }

  for (const s of sections) {
    const sec = el('section', { class: 'printable-section' });
    sec.appendChild(el('h3', { text: s.heading }));
    for (const p of (s.paragraphs || [])) {
      sec.appendChild(el('p', { text: p }));
    }
    if (s.items && s.items.length) {
      const ul = el('ul');
      for (const item of s.items) ul.appendChild(el('li', { text: String(item) }));
      sec.appendChild(ul);
    }
    article.appendChild(sec);
  }

  const footer = el('footer', { class: 'printable-footer' });
  footer.appendChild(el('p', { class: 'printable-source muted', text: 'Generated by sophiewell.com. No data was sent or stored.' }));
  article.appendChild(footer);

  rootEl.appendChild(article);

  const printBtn = el('button', { type: 'button', id: 'print-btn', class: 'print-btn', text: 'Print' });
  printBtn.addEventListener('click', () => {
    if (typeof window !== 'undefined' && typeof window.print === 'function') window.print();
  });
  rootEl.appendChild(printBtn);

  return { print: () => { if (typeof window !== 'undefined') window.print(); } };
}
