// The tile name, read out of the `UTILITIES` array literal in app.js.
//
// Every static surface is generated by regexing that array rather than by
// importing it, because app.js is a browser module that touches the DOM at
// load. The pattern each of them used, `name: '([^']+)'`, stops at the first
// quote character -- including the escaped one inside a name:
//
//   { id: 'cdai-crohns', name: 'CDAI (Crohn\'s Disease Activity Index)', ... }
//
// which yielded `CDAI (Crohn\`. That reached the reader: the browser tab and
// every search result for two tiles read "CDAI (Crohn\ - Free, in your
// browser", a stray backslash and a bracket left open. The tiles themselves
// were always right -- the app reads the real array.
//
// The body below is the same one `check-mcp-catalog.mjs` already uses: a
// character or an escape pair, repeated, so a `\'` is consumed as one unit
// instead of ending the match. The escapes are then undone, since `\'` in a
// JavaScript literal is just an apostrophe.
const NAME = /name:\s*'((?:\\.|[^'])*)'/;

export function tileName(line) {
  const m = line.match(NAME);
  return m ? m[1].replace(/\\(.)/g, '$1') : null;
}
