// spec-v183 MCP wave 10: adapters for lib/ltcga-v174.js — delirium, depression & agitation instruments — Nu-DESC, DOSS, the Cornell Scale (CSDD), the interRAI ABS, and the CMAI.
// dom keys mirror views/group-v174.js; the compute arg names are the
// verbatim keys those renderers pass. Kind is number for graded / free-numeric
// inputs and enum for the yes/no and sex selects. Default makeToArgs round-trips.

import * as F from '../../lib/ltcga-v174.js';

export default [
  {
    id: 'nu-desc',
    summary: 'Nursing Delirium Screening Scale: five nurse-observed features each 0/1/2. Total 0–10; ≥ 2 is a positive delirium screen.',
    compute: F.nuDesc,
    fields: [
    { dom: 'nudesc-disorientation', arg: 'disorientation', kind: 'number', required: true, label: 'Disorientation' },
    { dom: 'nudesc-behavior', arg: 'inappropriateBehavior', kind: 'number', required: true, label: 'Inappropriate Behavior' },
    { dom: 'nudesc-communication', arg: 'inappropriateCommunication', kind: 'number', required: true, label: 'Inappropriate Communication' },
    { dom: 'nudesc-illusions', arg: 'illusionsHallucinations', kind: 'number', required: true, label: 'Illusions Hallucinations' },
    { dom: 'nudesc-psychomotor', arg: 'psychomotorRetardation', kind: 'number', required: true, label: 'Psychomotor Retardation' },
    ],
  },
  {
    id: 'doss',
    summary: 'Delirium Observation Screening Scale: 13 shift-observed behaviors marked present/absent. ≥ 3 suggests delirium.',
    compute: F.doss,
    fields: [
    { dom: 'doss-dozes', arg: 'dozesOff', kind: 'number', required: true, label: 'Dozes Off' },
    { dom: 'doss-distracted', arg: 'distracted', kind: 'number', required: true, label: 'Distracted' },
    { dom: 'doss-attention', arg: 'noAttention', kind: 'number', required: true, label: 'No Attention' },
    { dom: 'doss-unfinished', arg: 'unfinishedAnswers', kind: 'number', required: true, label: 'Unfinished Answers' },
    { dom: 'doss-mismatch', arg: 'mismatchedAnswers', kind: 'number', required: true, label: 'Mismatched Answers' },
    { dom: 'doss-slow', arg: 'slowReactions', kind: 'number', required: true, label: 'Slow Reactions' },
    { dom: 'doss-elsewhere', arg: 'thinksElsewhere', kind: 'number', required: true, label: 'Thinks Elsewhere' },
    { dom: 'doss-timeofday', arg: 'unknownTimeOfDay', kind: 'number', required: true, label: 'Unknown Time Of Day' },
    { dom: 'doss-recall', arg: 'noRecentRecall', kind: 'number', required: true, label: 'No Recent Recall' },
    { dom: 'doss-restless', arg: 'restlessPicking', kind: 'number', required: true, label: 'Restless Picking' },
    { dom: 'doss-tubes', arg: 'pullsTubes', kind: 'number', required: true, label: 'Pulls Tubes' },
    { dom: 'doss-emotion', arg: 'suddenEmotion', kind: 'number', required: true, label: 'Sudden Emotion' },
    { dom: 'doss-perception', arg: 'seesHearsThings', kind: 'number', required: true, label: 'Sees Hears Things' },
    ],
  },
  {
    id: 'cornell-csdd',
    summary: 'Cornell Scale for Depression in Dementia: 19 items rated absent (0), mild (1), or severe (2). Total 0–38; > 10 probable major depression.',
    compute: F.cornellCsdd,
    fields: [
    { dom: 'csdd-anxiety', arg: 'anxiety', kind: 'number', required: true, label: 'Anxiety' },
    { dom: 'csdd-sadness', arg: 'sadness', kind: 'number', required: true, label: 'Sadness' },
    { dom: 'csdd-reactivity', arg: 'noReactivity', kind: 'number', required: true, label: 'No Reactivity' },
    { dom: 'csdd-irritability', arg: 'irritability', kind: 'number', required: true, label: 'Irritability' },
    { dom: 'csdd-agitation', arg: 'agitation', kind: 'number', required: true, label: 'Agitation' },
    { dom: 'csdd-retardation', arg: 'retardation', kind: 'number', required: true, label: 'Retardation' },
    { dom: 'csdd-complaints', arg: 'physicalComplaints', kind: 'number', required: true, label: 'Physical Complaints' },
    { dom: 'csdd-interest', arg: 'lossOfInterest', kind: 'number', required: true, label: 'Loss Of Interest' },
    { dom: 'csdd-appetite', arg: 'appetiteLoss', kind: 'number', required: true, label: 'Appetite Loss' },
    { dom: 'csdd-weight', arg: 'weightLoss', kind: 'number', required: true, label: 'Weight Loss' },
    { dom: 'csdd-energy', arg: 'lackOfEnergy', kind: 'number', required: true, label: 'Lack Of Energy' },
    { dom: 'csdd-diurnal', arg: 'diurnalVariation', kind: 'number', required: true, label: 'Diurnal Variation' },
    { dom: 'csdd-fallasleep', arg: 'difficultyFallingAsleep', kind: 'number', required: true, label: 'Difficulty Falling Asleep' },
    { dom: 'csdd-awakenings', arg: 'multipleAwakenings', kind: 'number', required: true, label: 'Multiple Awakenings' },
    { dom: 'csdd-earlywake', arg: 'earlyAwakening', kind: 'number', required: true, label: 'Early Awakening' },
    { dom: 'csdd-suicide', arg: 'suicide', kind: 'number', required: true, label: 'Suicide' },
    { dom: 'csdd-selfblame', arg: 'selfDepreciation', kind: 'number', required: true, label: 'Self Depreciation' },
    { dom: 'csdd-pessimism', arg: 'pessimism', kind: 'number', required: true, label: 'Pessimism' },
    { dom: 'csdd-delusions', arg: 'delusions', kind: 'number', required: true, label: 'Delusions' },
    ],
  },
  {
    id: 'interrai-abs',
    summary: 'interRAI Aggressive Behavior Scale: four behaviors rated 0 (not exhibited) to 3 (daily). Total 0–12.',
    compute: F.interraiAbs,
    fields: [
    { dom: 'abs-verbal', arg: 'verbalAbuse', kind: 'number', required: true, label: 'Verbal Abuse' },
    { dom: 'abs-physical', arg: 'physicalAbuse', kind: 'number', required: true, label: 'Physical Abuse' },
    { dom: 'abs-social', arg: 'sociallyInappropriate', kind: 'number', required: true, label: 'Socially Inappropriate' },
    { dom: 'abs-resists', arg: 'resistsCare', kind: 'number', required: true, label: 'Resists Care' },
    ],
  },
  {
    id: 'cmai',
    summary: 'Cohen-Mansfield Agitation Inventory: 29 agitated behaviors rated 1 (never) to 7 (several times an hour). Frequency quantifier, floor 29, ceiling 203.',
    compute: F.cmai,
    fields: [
    { dom: 'cmai-pacing', arg: 'pacing', kind: 'number', required: true, label: 'Pacing' },
    { dom: 'cmai-dressing', arg: 'dressing', kind: 'number', required: true, label: 'Dressing' },
    { dom: 'cmai-spitting', arg: 'spitting', kind: 'number', required: true, label: 'Spitting' },
    { dom: 'cmai-cursing', arg: 'cursing', kind: 'number', required: true, label: 'Cursing' },
    { dom: 'cmai-requests', arg: 'requests', kind: 'number', required: true, label: 'Requests' },
    { dom: 'cmai-repetitive', arg: 'repetitive', kind: 'number', required: true, label: 'Repetitive' },
    { dom: 'cmai-hitting', arg: 'hitting', kind: 'number', required: true, label: 'Hitting' },
    { dom: 'cmai-kicking', arg: 'kicking', kind: 'number', required: true, label: 'Kicking' },
    { dom: 'cmai-grabbing', arg: 'grabbing', kind: 'number', required: true, label: 'Grabbing' },
    { dom: 'cmai-pushing', arg: 'pushing', kind: 'number', required: true, label: 'Pushing' },
    { dom: 'cmai-throwing', arg: 'throwing', kind: 'number', required: true, label: 'Throwing' },
    { dom: 'cmai-noises', arg: 'noises', kind: 'number', required: true, label: 'Noises' },
    { dom: 'cmai-screaming', arg: 'screaming', kind: 'number', required: true, label: 'Screaming' },
    { dom: 'cmai-biting', arg: 'biting', kind: 'number', required: true, label: 'Biting' },
    { dom: 'cmai-scratching', arg: 'scratching', kind: 'number', required: true, label: 'Scratching' },
    { dom: 'cmai-trying', arg: 'tryingToGet', kind: 'number', required: true, label: 'Trying To Get' },
    { dom: 'cmai-falling', arg: 'falling', kind: 'number', required: true, label: 'Falling' },
    { dom: 'cmai-complaining', arg: 'complaining', kind: 'number', required: true, label: 'Complaining' },
    { dom: 'cmai-negativism', arg: 'negativism', kind: 'number', required: true, label: 'Negativism' },
    { dom: 'cmai-eating', arg: 'eatingSubstances', kind: 'number', required: true, label: 'Eating Substances' },
    { dom: 'cmai-hurting', arg: 'hurting', kind: 'number', required: true, label: 'Hurting' },
    { dom: 'cmai-handling', arg: 'handlingThings', kind: 'number', required: true, label: 'Handling Things' },
    { dom: 'cmai-hiding', arg: 'hiding', kind: 'number', required: true, label: 'Hiding' },
    { dom: 'cmai-hoarding', arg: 'hoarding', kind: 'number', required: true, label: 'Hoarding' },
    { dom: 'cmai-tearing', arg: 'tearing', kind: 'number', required: true, label: 'Tearing' },
    { dom: 'cmai-mannerisms', arg: 'mannerisms', kind: 'number', required: true, label: 'Mannerisms' },
    { dom: 'cmai-verbalsex', arg: 'verbalSexual', kind: 'number', required: true, label: 'Verbal Sexual' },
    { dom: 'cmai-physicalsex', arg: 'physicalSexual', kind: 'number', required: true, label: 'Physical Sexual' },
    { dom: 'cmai-restlessness', arg: 'restlessness', kind: 'number', required: true, label: 'Restlessness' },
    ],
  },
];
