// spec-v183 MCP waves 54 + 72: adapters for lib/scoring-v6.js - the neonatal
// assessment set (Ballard maturity, Finnegan NAS, Silverman-Andersen, Downes,
// Bhutani bilirubin risk zone, quantitative blood loss, AAP phototherapy; wave
// 54) plus the pediatric/adult severity scores rendered by views/group-v10.js
// (PELOD-2, pSOFA, Burch-Wartofsky, ARISCAT, APACHE II, Braden Q; wave 72). dom
// keys mirror the renderers.

import * as F from '../../lib/scoring-v6.js';

export default [
  {
    id: 'ballard',
    summary: 'New Ballard Score: 6 neuromuscular and 6 physical maturity signs each scored -1 to 5; the summed maturity rating maps to estimated gestational age (weeks) for newborns 20-44 weeks.',
    // The lib takes two exactly-six-element numeric arrays; rebuild them from
    // the flat per-sign selects (the drug-burden-index array-rebuild precedent).
    compute: (a) => F.ballard({
      neuromuscular: [a.n0, a.n1, a.n2, a.n3, a.n4, a.n5],
      physical: [a.p0, a.p1, a.p2, a.p3, a.p4, a.p5],
    }),
    fields: [
      { dom: 'bl-n1', arg: 'n0', kind: 'enum', values: ['-1', '0', '1', '2', '3', '4', '5'], required: true, label: 'Posture', to: Number },
      { dom: 'bl-n2', arg: 'n1', kind: 'enum', values: ['-1', '0', '1', '2', '3', '4', '5'], required: true, label: 'Square window (wrist)', to: Number },
      { dom: 'bl-n3', arg: 'n2', kind: 'enum', values: ['-1', '0', '1', '2', '3', '4', '5'], required: true, label: 'Arm recoil', to: Number },
      { dom: 'bl-n4', arg: 'n3', kind: 'enum', values: ['-1', '0', '1', '2', '3', '4', '5'], required: true, label: 'Popliteal angle', to: Number },
      { dom: 'bl-n5', arg: 'n4', kind: 'enum', values: ['-1', '0', '1', '2', '3', '4', '5'], required: true, label: 'Scarf sign', to: Number },
      { dom: 'bl-n6', arg: 'n5', kind: 'enum', values: ['-1', '0', '1', '2', '3', '4', '5'], required: true, label: 'Heel to ear', to: Number },
      { dom: 'bl-p1', arg: 'p0', kind: 'enum', values: ['-1', '0', '1', '2', '3', '4', '5'], required: true, label: 'Skin', to: Number },
      { dom: 'bl-p2', arg: 'p1', kind: 'enum', values: ['-1', '0', '1', '2', '3', '4', '5'], required: true, label: 'Lanugo', to: Number },
      { dom: 'bl-p3', arg: 'p2', kind: 'enum', values: ['-1', '0', '1', '2', '3', '4', '5'], required: true, label: 'Plantar surface', to: Number },
      { dom: 'bl-p4', arg: 'p3', kind: 'enum', values: ['-1', '0', '1', '2', '3', '4', '5'], required: true, label: 'Breast', to: Number },
      { dom: 'bl-p5', arg: 'p4', kind: 'enum', values: ['-1', '0', '1', '2', '3', '4', '5'], required: true, label: 'Eye / ear', to: Number },
      { dom: 'bl-p6', arg: 'p5', kind: 'enum', values: ['-1', '0', '1', '2', '3', '4', '5'], required: true, label: 'Genitals', to: Number },
    ],
  },
  {
    id: 'finnegan',
    summary: 'Modified Finnegan Neonatal Abstinence Score: 24 weighted binary signs plus 3 graded items (sleep 0-3, fever 0-2, respiratory rate 0-2) summed for one scoring interval; >=8 or >=12 trend thresholds prompt pharmacologic treatment per protocol. Higher = worse.',
    compute: F.finnegan,
    fields: [
      { dom: 'fn-highPitchedCry', arg: 'highPitchedCry', kind: 'bool', required: true, label: 'Excessive high-pitched cry (2)' },
      { dom: 'fn-continuousCry', arg: 'continuousCry', kind: 'bool', required: false, label: 'Continuous high-pitched cry (3)' },
      { dom: 'fn-moro', arg: 'moro', kind: 'bool', required: true, label: 'Hyperactive Moro reflex (2)' },
      { dom: 'fn-markedMoro', arg: 'markedMoro', kind: 'bool', required: false, label: 'Markedly hyperactive Moro (3)' },
      { dom: 'fn-tremorsDisturbed', arg: 'tremorsDisturbed', kind: 'bool', required: false, label: 'Mild tremors when disturbed (1)' },
      { dom: 'fn-markedTremorsDisturbed', arg: 'markedTremorsDisturbed', kind: 'bool', required: false, label: 'Marked tremors when disturbed (2)' },
      { dom: 'fn-tremorsUndisturbed', arg: 'tremorsUndisturbed', kind: 'bool', required: false, label: 'Mild tremors undisturbed (3)' },
      { dom: 'fn-markedTremorsUndisturbed', arg: 'markedTremorsUndisturbed', kind: 'bool', required: false, label: 'Marked tremors undisturbed (4)' },
      { dom: 'fn-increasedTone', arg: 'increasedTone', kind: 'bool', required: false, label: 'Increased muscle tone (2)' },
      { dom: 'fn-excoriation', arg: 'excoriation', kind: 'bool', required: false, label: 'Excoriation of skin (1)' },
      { dom: 'fn-myoclonus', arg: 'myoclonus', kind: 'bool', required: false, label: 'Myoclonic jerks (3)' },
      { dom: 'fn-convulsions', arg: 'convulsions', kind: 'bool', required: false, label: 'Generalized convulsions (5)' },
      { dom: 'fn-sweating', arg: 'sweating', kind: 'bool', required: true, label: 'Sweating (1)' },
      { dom: 'fn-yawning', arg: 'yawning', kind: 'bool', required: false, label: 'Frequent yawning (1)' },
      { dom: 'fn-mottling', arg: 'mottling', kind: 'bool', required: false, label: 'Mottling (1)' },
      { dom: 'fn-nasalStuffiness', arg: 'nasalStuffiness', kind: 'bool', required: false, label: 'Nasal stuffiness (1)' },
      { dom: 'fn-sneezing', arg: 'sneezing', kind: 'bool', required: false, label: 'Sneezing (1)' },
      { dom: 'fn-nasalFlaring', arg: 'nasalFlaring', kind: 'bool', required: false, label: 'Nasal flaring (2)' },
      { dom: 'fn-excessiveSucking', arg: 'excessiveSucking', kind: 'bool', required: false, label: 'Excessive sucking (1)' },
      { dom: 'fn-poorFeeding', arg: 'poorFeeding', kind: 'bool', required: false, label: 'Poor feeding (2)' },
      { dom: 'fn-regurgitation', arg: 'regurgitation', kind: 'bool', required: false, label: 'Regurgitation (2)' },
      { dom: 'fn-projectileVomiting', arg: 'projectileVomiting', kind: 'bool', required: false, label: 'Projectile vomiting (3)' },
      { dom: 'fn-looseStools', arg: 'looseStools', kind: 'bool', required: true, label: 'Loose stools (2)' },
      { dom: 'fn-wateryStools', arg: 'wateryStools', kind: 'bool', required: false, label: 'Watery stools (3)' },
      { dom: 'fn-sleep', arg: 'sleep', kind: 'enum', values: ['0', '1', '2', '3'], required: true, label: 'Sleeps after feeding: <3 h (1) / <2 h (2) / <1 h (3)', to: Number },
      { dom: 'fn-fever', arg: 'fever', kind: 'enum', values: ['0', '1', '2'], required: true, label: 'Fever: 37.2-38.3 C (1) / >38.3 C (2)', to: Number },
      { dom: 'fn-respRate', arg: 'respRate', kind: 'enum', values: ['0', '1', '2'], required: false, label: 'Respiratory rate: >60 (1) / >60 with retractions (2)', to: Number },
    ],
  },
  {
    id: 'silverman-andersen',
    summary: 'Silverman-Andersen retraction score: 5 neonatal respiratory signs scored 0-2 each (total 0-10) grading respiratory distress; 0 none, 1-3 mild, 4-6 moderate, >=7 severe. Higher = worse.',
    compute: F.silvermanAndersen,
    fields: [
      { dom: 'sa-chest', arg: 'chestMovement', kind: 'enum', values: ['0', '1', '2'], required: true, label: 'Upper-chest / abdomen movement (synchrony)', to: Number },
      { dom: 'sa-intercostal', arg: 'intercostal', kind: 'enum', values: ['0', '1', '2'], required: true, label: 'Intercostal retraction', to: Number },
      { dom: 'sa-xiphoid', arg: 'xiphoid', kind: 'enum', values: ['0', '1', '2'], required: true, label: 'Xiphoid retraction', to: Number },
      { dom: 'sa-nares', arg: 'naresDilatation', kind: 'enum', values: ['0', '1', '2'], required: true, label: 'Nares dilatation', to: Number },
      { dom: 'sa-grunt', arg: 'grunt', kind: 'enum', values: ['0', '1', '2'], required: true, label: 'Expiratory grunt', to: Number },
    ],
  },
  {
    id: 'downes',
    summary: 'Downes score: 5 neonatal respiratory-distress parameters scored 0-2 each (total 0-10); 0-3 mild, 4-6 moderate (impending respiratory failure), >=7 severe (consider assisted ventilation). Higher = worse.',
    compute: F.downes,
    fields: [
      { dom: 'dn-rr', arg: 'respiratoryRate', kind: 'enum', values: ['0', '1', '2'], required: true, label: 'Respiratory rate', to: Number },
      { dom: 'dn-cyanosis', arg: 'cyanosis', kind: 'enum', values: ['0', '1', '2'], required: true, label: 'Cyanosis', to: Number },
      { dom: 'dn-airentry', arg: 'airEntry', kind: 'enum', values: ['0', '1', '2'], required: true, label: 'Air entry', to: Number },
      { dom: 'dn-grunting', arg: 'grunting', kind: 'enum', values: ['0', '1', '2'], required: true, label: 'Grunting', to: Number },
      { dom: 'dn-retractions', arg: 'retractions', kind: 'enum', values: ['0', '1', '2'], required: true, label: 'Retractions', to: Number },
    ],
  },
  {
    id: 'bhutani-bilirubin',
    summary: 'Bhutani 1999 hour-specific bilirubin nomogram zone (40th/75th/95th percentile tracks) plus the AAP-2022 phototherapy threshold for the entered gestational age and neurotoxicity-risk flag, for newborns 35+ weeks.',
    compute: F.bhutaniBilirubin,
    fields: [
      { dom: 'bb-hours', arg: 'ageHours', kind: 'number', required: true, label: 'Age (hours)', unit: 'hours' },
      { dom: 'bb-tsb', arg: 'tsb', kind: 'number', required: true, label: 'Total serum bilirubin', unit: 'mg/dL (canonical)' },
      { dom: 'bb-ga', arg: 'gaWeeks', kind: 'number', required: true, label: 'Gestational age (weeks, 35-44)', unit: 'weeks' },
      { dom: 'bb-risk', arg: 'riskFactors', kind: 'bool', required: false, label: 'Neurotoxicity risk factor(s) present' },
    ],
  },
  {
    id: 'qbl-pph',
    summary: 'Quantitative blood loss for obstetric hemorrhage: QBL = measured mL + (pad grams - dry tare grams) with the 1 g = 1 mL convention, flags ACOG PPH thresholds by delivery route, and tiers CMQCC admission risk-factor count.',
    compute: F.qblPph,
    fields: [
      { dom: 'qp-measured', arg: 'measuredMl', kind: 'number', required: true, label: 'Measured / collected blood (mL)', unit: 'mL', to: (v) => v || 0 },
      { dom: 'qp-pad', arg: 'padGrams', kind: 'number', required: true, label: 'Weighed pads/drapes (g)', unit: 'g', to: (v) => v || 0 },
      { dom: 'qp-tare', arg: 'dryTareGrams', kind: 'number', required: true, label: 'Dry-pad + irrigation tare (g)', unit: 'g', to: (v) => v || 0 },
      { dom: 'qp-vaginal', arg: 'vaginal', kind: 'bool', required: true, label: 'Vaginal birth' },
      { dom: 'qp-unstable', arg: 'unstable', kind: 'bool', required: false, label: 'Hemodynamic instability' },
      { dom: 'qp-risk', arg: 'riskFactors', kind: 'enum', values: ['0', '1', '2', '3', '4', '5', '6'], required: true, label: 'CMQCC admission risk factors (count)', to: Number },
    ],
  },
  {
    id: 'neo-phototherapy',
    summary: 'AAP 2022 neonatal hyperbilirubinemia thresholds: phototherapy, escalation-of-care, and exchange-transfusion TSB lines for the entered gestational age, age in hours, and neurotoxicity-risk flag, with the margin of the entered TSB to the phototherapy line.',
    // Echo the measured TSB so the margin-to-threshold is self-describing.
    compute: (a) => {
      const r = F.neoPhototherapy(a);
      return r == null ? r : { ...r, tsb: a.tsb };
    },
    fields: [
      { dom: 'np-ga', arg: 'gaWeeks', kind: 'number', required: true, label: 'Gestational age (weeks, 35-44)', unit: 'weeks' },
      { dom: 'np-hours', arg: 'ageHours', kind: 'number', required: true, label: 'Age (hours, 0-336)', unit: 'hours' },
      { dom: 'np-tsb', arg: 'tsb', kind: 'number', required: true, label: 'Total serum bilirubin', unit: 'mg/dL (canonical)' },
      { dom: 'np-risk', arg: 'riskFactors', kind: 'bool', required: false, label: 'Neurotoxicity risk factor(s) present' },
    ],
  },

  // --- wave 72: the pediatric / adult severity scores (views/group-v10.js) --
  {
    id: 'pelod2',
    summary: 'PELOD-2 pediatric organ-dysfunction score (Leteurtre 2013): GCS and pupils, lactate and MAP (age-banded), creatinine (age-banded), PaO2/FiO2 and PaCO2 and invasive ventilation, WBC and platelets; total 0-33 with the active age band reported.',
    compute: F.pelod2,
    fields: [
      { dom: 'p2-age', arg: 'ageMonths', kind: 'number', required: true, label: 'Age', unit: 'months' },
      { dom: 'p2-gcs', arg: 'gcs', kind: 'number', required: true, label: 'Glasgow Coma Scale (3-15)' },
      { dom: 'p2-pupils', arg: 'pupilsFixed', kind: 'bool', label: 'Both pupils fixed' },
      { dom: 'p2-lactate', arg: 'lactate', kind: 'number', required: true, label: 'Lactate', unit: 'mmol/L' },
      { dom: 'p2-map', arg: 'map', kind: 'number', required: true, label: 'Mean arterial pressure', unit: 'mmHg' },
      { dom: 'p2-creat', arg: 'creatinine', kind: 'number', required: true, label: 'Creatinine', unit: 'umol/L' },
      { dom: 'p2-pf', arg: 'pao2fio2', kind: 'number', required: true, label: 'PaO2/FiO2', unit: 'mmHg' },
      { dom: 'p2-paco2', arg: 'paco2', kind: 'number', required: true, label: 'PaCO2', unit: 'mmHg' },
      { dom: 'p2-vent', arg: 'invasiveVent', kind: 'bool', label: 'Invasive ventilation' },
      { dom: 'p2-wbc', arg: 'wbc', kind: 'number', required: true, label: 'WBC', unit: 'x10^3/uL' },
      { dom: 'p2-plt', arg: 'platelets', kind: 'number', required: true, label: 'Platelets', unit: 'x10^3/uL' },
    ],
  },
  {
    id: 'psofa',
    summary: 'Pediatric SOFA score (Matics 2017): PaO2/FiO2 (with ventilation), platelets, bilirubin, MAP (age-banded) with vasoactive grade, GCS, and creatinine (age-banded); total 0-24 with the active age band.',
    compute: F.psofa,
    fields: [
      { dom: 'ps-age', arg: 'ageMonths', kind: 'number', required: true, label: 'Age', unit: 'months' },
      { dom: 'ps-pf', arg: 'pao2fio2', kind: 'number', required: true, label: 'PaO2/FiO2', unit: 'mmHg' },
      { dom: 'ps-vent', arg: 'vent', kind: 'bool', label: 'Mechanically ventilated' },
      { dom: 'ps-plt', arg: 'platelets', kind: 'number', required: true, label: 'Platelets', unit: 'x10^3/uL' },
      { dom: 'ps-bili', arg: 'bilirubin', kind: 'number', required: true, label: 'Bilirubin', unit: 'mg/dL' },
      { dom: 'ps-map', arg: 'map', kind: 'number', required: true, label: 'Mean arterial pressure', unit: 'mmHg' },
      { dom: 'ps-vaso', arg: 'vasoactive', kind: 'number', label: 'Vasoactive grade (0-4)' },
      { dom: 'ps-gcs', arg: 'gcs', kind: 'number', required: true, label: 'Glasgow Coma Scale (3-15)' },
      { dom: 'ps-creat', arg: 'creatinine', kind: 'number', required: true, label: 'Creatinine', unit: 'mg/dL' },
    ],
  },
  {
    id: 'burch-wartofsky',
    summary: 'Burch-Wartofsky Point Scale for thyroid storm (Burch 1993): thermoregulatory (temperature), CNS, GI-hepatic, cardiovascular (tachycardia, CHF), atrial fibrillation, and a precipitant history, each entered as its point value; a total >= 45 is highly suggestive, 25-44 impending.',
    compute: F.burchWartofsky,
    fields: [
      { dom: 'bw-temp', arg: 'temp', kind: 'number', required: true, label: 'Temperature points (0-30)' },
      { dom: 'bw-cns', arg: 'cns', kind: 'number', required: true, label: 'CNS effects points (0-30)' },
      { dom: 'bw-gi', arg: 'gi', kind: 'number', required: true, label: 'GI-hepatic points (0-20)' },
      { dom: 'bw-hr', arg: 'hr', kind: 'number', required: true, label: 'Tachycardia points (0-25)' },
      { dom: 'bw-chf', arg: 'chf', kind: 'number', required: true, label: 'Congestive heart failure points (0-15)' },
      { dom: 'bw-afib', arg: 'afib', kind: 'bool', label: 'Atrial fibrillation (10)' },
      { dom: 'bw-precip', arg: 'precipitant', kind: 'bool', label: 'Precipitant history (10)' },
    ],
  },
  {
    id: 'ariscat',
    summary: 'ARISCAT score (Canet 2010) for postoperative pulmonary complications: age, preoperative SpO2, surgical incision site, and surgery duration entered as point values, plus respiratory infection, anemia, and emergency-procedure flags; < 26 low, 26-44 intermediate, >= 45 high risk.',
    compute: F.ariscat,
    fields: [
      { dom: 'ar-age', arg: 'agePts', kind: 'number', required: true, label: 'Age points (0/3/16)' },
      { dom: 'ar-spo2', arg: 'spo2Pts', kind: 'number', required: true, label: 'Preoperative SpO2 points (0/8/24)' },
      { dom: 'ar-incision', arg: 'incisionPts', kind: 'number', required: true, label: 'Surgical incision points (0/15/24)' },
      { dom: 'ar-duration', arg: 'durationPts', kind: 'number', required: true, label: 'Surgery duration points (0/16/23)' },
      { dom: 'ar-infection', arg: 'respInfection', kind: 'bool', label: 'Respiratory infection in the last month (17)' },
      { dom: 'ar-anemia', arg: 'anemia', kind: 'bool', label: 'Preoperative anemia (Hb <= 10 g/dL) (11)' },
      { dom: 'ar-emergency', arg: 'emergency', kind: 'bool', label: 'Emergency procedure (8)' },
    ],
  },
  {
    id: 'apache2',
    summary: 'APACHE II score (Knaus 1985): twelve acute-physiology variables (temperature, MAP, heart rate, respiratory rate, oxygenation, pH, sodium, potassium, creatinine, hematocrit, WBC, GCS) plus age points and chronic-health points; total 0-71 with the mortality band. Enter the worst first-24-hour value for each variable.',
    compute: F.apache2,
    fields: [
      { dom: 'ap-temp', arg: 'temp', kind: 'number', required: true, label: 'Temperature', unit: 'C' },
      { dom: 'ap-map', arg: 'map', kind: 'number', required: true, label: 'Mean arterial pressure', unit: 'mmHg' },
      { dom: 'ap-hr', arg: 'hr', kind: 'number', required: true, label: 'Heart rate', unit: 'bpm' },
      { dom: 'ap-rr', arg: 'rr', kind: 'number', required: true, label: 'Respiratory rate', unit: '/min' },
      { dom: 'ap-oxy', arg: 'oxy', kind: 'number', required: true, label: 'Oxygenation: PaO2', unit: 'mmHg' },
      { dom: 'ap-ph', arg: 'ph', kind: 'number', required: true, label: 'Arterial pH' },
      { dom: 'ap-na', arg: 'na', kind: 'number', required: true, label: 'Serum sodium', unit: 'mmol/L' },
      { dom: 'ap-k', arg: 'k', kind: 'number', required: true, label: 'Serum potassium', unit: 'mmol/L' },
      { dom: 'ap-creat', arg: 'creatinine', kind: 'number', required: true, label: 'Serum creatinine', unit: 'mg/dL' },
      { dom: 'ap-hct', arg: 'hct', kind: 'number', required: true, label: 'Hematocrit', unit: '%' },
      { dom: 'ap-wbc', arg: 'wbc', kind: 'number', required: true, label: 'WBC', unit: 'x10^3/uL' },
      { dom: 'ap-gcs', arg: 'gcs', kind: 'number', required: true, label: 'Glasgow Coma Scale (3-15)' },
      { dom: 'ap-age', arg: 'age', kind: 'number', required: true, label: 'Age', unit: 'years' },
      { dom: 'ap-chronic', arg: 'chronicHealth', kind: 'bool', label: 'Severe chronic-organ insufficiency / immunocompromise' },
      { dom: 'ap-nonop', arg: 'nonoperativeOrEmergency', kind: 'bool', label: 'Nonoperative or emergency postoperative admission' },
    ],
  },
  {
    id: 'braden-q',
    summary: 'Braden Q Scale for pediatric pressure-injury risk (Quigley 1996): seven subscales (mobility, activity, sensory perception, moisture, friction/shear, nutrition, tissue perfusion/oxygenation) each 1-4; total 7-28, <= 16 at risk (lower = higher risk).',
    compute: F.bradenQ,
    fields: [
      { dom: 'bq-mobility', arg: 'mobility', kind: 'number', required: true, label: 'Mobility (1-4)' },
      { dom: 'bq-activity', arg: 'activity', kind: 'number', required: true, label: 'Activity (1-4)' },
      { dom: 'bq-sensory', arg: 'sensory', kind: 'number', required: true, label: 'Sensory perception (1-4)' },
      { dom: 'bq-moisture', arg: 'moisture', kind: 'number', required: true, label: 'Moisture (1-4)' },
      { dom: 'bq-friction', arg: 'friction', kind: 'number', required: true, label: 'Friction / shear (1-4)' },
      { dom: 'bq-nutrition', arg: 'nutrition', kind: 'number', required: true, label: 'Nutrition (1-4)' },
      { dom: 'bq-perfusion', arg: 'perfusion', kind: 'number', required: true, label: 'Tissue perfusion / oxygenation (1-4)' },
    ],
  },
];
